-- Texas Exam Prep — content seed, chunk 2 of 30
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2aa5db82-0689-5f02-8850-03dec995ef82', 'ec98aec4-aec6-5d3e-93ae-dbb68098f16a', c.id, 'Homeowners Forms',
       'homeowners-forms', 'The six homeowners forms, the coverages A to F they carry, and the differences between the forms that decide which one a household needs.', 1,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2aa5db82-0689-5f02-8850-03dec995ef82', c.id, $lesson$**What this lesson covers.** The homeowners policy: how it is built, what
each of its six coverages pays for, and how the six forms differ from one
another.

**By the end you should be able to** say what Coverages A to F each cover and
how their limits relate; pick the right form for an owner, a renter or a
condominium owner; and state, for any of the six forms, whether it insures the
dwelling and the contents on a named peril or an open peril basis.

Imagine you own a house. Several different things could go wrong, and they are
not the same kind of problem:

- The house itself could burn down.
- The detached garage could be crushed by a falling tree.
- Everything inside — furniture, clothes, the television — could be stolen.
- If the house is unliveable while it is repaired, you still have to sleep
  somewhere, and that costs money you were not expecting to spend.
- A visitor could trip on your step, break a wrist, and expect you to pay for
  it.

Years ago you would have bought a separate policy for several of those. A
homeowners policy puts them all into one contract. That is what people mean
when they call it a **package**: property insurance and liability insurance
sold together.

## The two halves of the policy

Every homeowners policy is split in two.

**Section I is about your property** — your own things, damaged, destroyed or
stolen.

**Section II is about your liability** — harm you cause to somebody else.

Inside those halves are the individual **coverages**, and each one has a
letter. The letters mean the same thing on every homeowners policy sold, which
is why it is worth learning them once and for good.

### Section I — your property

| | Name | What it pays for |
| --- | --- | --- |
| **A** | Dwelling | The house itself, and anything attached to it |
| **B** | Other Structures | Separate buildings: a detached garage, a shed, a fence |
| **C** | Personal Property | Your belongings — furniture, clothes, electronics — anywhere in the world |
| **D** | Loss of Use | Your extra living costs while the house is unliveable |

**Coverage D is the one beginners find strangest**, so it is worth a moment. If
a fire makes your house unliveable, you have to live somewhere while it is
repaired. A hotel, a rented flat, meals you would have cooked at home. Coverage
D pays the **extra** cost — the difference between what you are spending now
and what you normally spend. It does not pay your mortgage, because you would
have paid that anyway.

If you rent the house out to somebody else, the same coverage pays you the
rent you are no longer collecting. That is what **fair rental value** means.

### Section II — harm you cause other people

| | Name | What it pays for |
| --- | --- | --- |
| **E** | Personal Liability | Injuries or damage you are **legally responsible** for |
| **F** | Medical Payments to Others | Medical bills for a person hurt on your property, **whether or not it was your fault** |

The phrase carrying the weight in Coverage E is *legally responsible*. It does not pay
simply because somebody was hurt at your house. It pays when you are at fault
— when the law would make you pay. Module 2 covers how fault is decided.

**Coverage F does not care about fault at all.** A guest falls over their own
feet on your path and needs stitches: Coverage F pays the bill, even though you
did nothing wrong. It exists to settle small injuries quickly and stop them
becoming arguments. The amounts are small — typically a few thousand dollars.

**Coverage F does not cover you or the people who live with you.** If you break
your own arm at home, that is your health insurance, not your homeowners
policy. Candidates get this wrong often enough that it is worth saying twice:
Medical Payments **to Others** means to others.

## How much the policy pays: limits

Every coverage has a **limit** — the most the insurance company will pay for
that kind of loss, no matter how big the loss is. You choose the limits when
you buy the policy, and higher limits cost more.

Here is the part worth remembering. **You choose Coverage A, and the other
three property coverages follow automatically** as a percentage of it:

| Coverage | Usual amount |
| --- | --- |
| **B** — Other Structures | **10%** of Coverage A |
| **C** — Personal Property | **50%** of Coverage A (40% on some forms) |
| **D** — Loss of Use | **20–30%** of Coverage A, depending on the form |

So if you insure the house for **$200,000**:

- the detached garage and fence are covered up to **$20,000**
- your belongings up to **$100,000**
- your extra living costs up to **$40,000 to $60,000**

You can pay more to raise any of them. But if you do nothing, those are the
numbers you get — which is why an exam question can ask what Coverage B is
worth when it has only told you Coverage A.

## A. Homeowners

There are six forms. They are all the same policy underneath — Section I and
Section II, Coverages A to F — and they differ in only two ways:

1. **Who the policy is for** — somebody who owns and lives in the house,
   somebody who rents, or somebody who owns a condominium.
2. **How the perils are covered** — named peril or open peril.

That second one decides most exam questions, so here it is again in plain
words. A **peril** is a cause of loss: fire, hail, theft.

- **Named peril** means the policy lists the causes it covers. Fire is on the
  list, so a fire is covered. If whatever happened is not on the list, you are
  not covered — and **you** have to show that it was.
- **Open peril** means the policy covers every cause *except* the ones it
  specifically rules out. That is broader, and if the company wants to refuse
  the claim, **the company** has to show the cause was one of the exclusions.

Open peril is the better deal, and it costs more.

| Form | Who it is for | The house (A) | Your things (C) |
| --- | --- | --- | --- |
| **HO-2** Broad | Owner who lives there | **Named peril** | **Named peril** |
| **HO-3** Special | Owner who lives there | **Open peril** | **Named peril** |
| **HO-4** Contents | **Renter** | none — they do not own it | **Named peril** |
| **HO-5** Comprehensive | Owner who lives there | **Open peril** | **Open peril** |
| **HO-6** Unit-owners | **Condominium owner** | small amount only | **Named peril** |
| **HO-8** Modified | Owner of an older home | **Named peril** | **Named peril** |

### 1. HO-2 — Broad Form

**Named peril on both sides.** The house is covered against a list of causes;
so are your belongings. Anything not on the list is not covered.

This is the plainest of the owner forms, and it is the one to measure the
others against. Every form after it either widens the peril coverage or is
written for a different kind of person.

### 2. HO-3 — Special Form

**This is the policy most homeowners actually have**, and it is lopsided on
purpose:

- **The house is open peril** — covered against everything except what the
  policy excludes.
- **Your belongings are named peril** — covered only against the listed
  causes.

That difference between the building and the contents is the single most
tested fact in this lesson. If a question describes a house on open peril and
contents on named peril, it is describing an HO-3.

Why the split? The house is a known, fixed thing an insurer can inspect. Your
belongings move, change and are easy to claim for dishonestly, so insurers are
more cautious with them.

### 3. HO-4 — Contents Form (tenants)

This is the policy a renter buys. A tenant does not own the building, so there is
**no Coverage A** — insuring the building is the landlord's job.

The tenant still gets everything else: Coverage C for their belongings,
Coverage D for somewhere to live if the flat becomes uninhabitable, and
Coverages E and F for harm they cause other people.

### 4. HO-5 — Comprehensive Form

**Take an HO-3 and upgrade the belongings to open peril as well.** That is the
entire difference. House open peril, contents open peril — the broadest of the
six, and the most expensive.

### 5. HO-6 — Unit-Owners Form

**The condominium owner's policy.**

If you own a condominium, you do not own the whole building — the owners'
association does, and the association has its own policy covering the
structure. So your Coverage A is small, often **$5,000** by default, and you
can raise it.

What your Coverage A actually covers is **what is inside your walls**:
cabinets, fixtures, flooring, and any improvements you have made. Exactly where
the association's policy stops and yours starts depends on the association's
own documents, which is why a producer reads them.

### 6. HO-8 — Modified Coverage Form

**For older homes that would cost far more to rebuild than they are worth.**

Picture a large Victorian house in a neighbourhood where houses sell for
$90,000. Rebuilding it properly — the plasterwork, the timber, the detailing —
might cost $400,000. No insurer wants to write a $400,000 policy on a $90,000
house, because the owner would then be better off if it burned down. That
temptation has a name in insurance: **moral hazard**.

HO-8 solves it by **paying to repair with ordinary modern materials** rather
than to reproduce the original. Plasterwork is replaced with plasterboard. The
house is made usable again, not restored to a museum piece. It also uses a
**shorter list of covered perils** than the other forms.

## Who can buy each form

A homeowners policy is not for everybody. To be eligible:

- You must **own the home and live in it** (HO-2, 3, 5, 8), **rent** it
  (HO-4), or **own a condominium unit** (HO-6).
- The building can house up to **four families**, and you must live in one of
  the units. Only a limited number of lodgers are allowed per unit.
- **Farms cannot use a homeowners policy.** They need a farmowners policy,
  which covers the barn, the stock and the machinery too.
- **A small business run from home** can sometimes be added on by
  endorsement — an extra document attached to the policy. A real business
  needs a commercial policy instead.

## The lists of covered perils

Named peril forms work from a list. There are two lists, and the broad list is
the basic list plus more.

**The basic list:** fire or lightning · windstorm or hail · explosion · riot
or civil commotion · aircraft · vehicles · smoke · vandalism · theft ·
volcanic eruption.

**The broad list adds:** falling objects · the weight of ice, snow or sleet ·
water or steam escaping from a system in the house · a heating or
air-conditioning system tearing apart, cracking, burning or bulging ·
freezing · sudden damage from electrical current the house generated itself.

Notice what the broad list is about: **things that go wrong inside the
building**, mostly involving water, ice and machinery. That is the easiest way
to remember which list an item belongs to.

**An open peril form has no list.** It covers everything except what it
excludes, so with an open peril form you read the exclusions instead.

## What comes free with the policy

Every homeowners policy includes some small coverages at no extra cost. They
are usually capped at modest amounts:

- **Debris removal** — clearing away what is left after a loss.
- **Reasonable repairs** — patching a hole in the roof to stop more rain
  getting in.
- **Property removed** — your belongings are covered while you are moving them
  somewhere safe.
- **Trees, shrubs and plants** — a small percentage of Coverage A, capped per
  tree, and only against a short list of causes. **Wind damage to a tree is
  not covered**, which is the trap most often set on this one.
- **Fire department service charge** — some fire services bill you for
  attending.
- **Credit cards, forgery and counterfeit money** — commonly **$500**.
- **Loss assessment** — your share when a condominium association bills all
  its owners for a loss.
- **Collapse** and **glass breakage**.
- **Ordinance or law** — a small amount towards the extra cost of rebuilding
  to current building rules.

## Limits on particular belongings

Coverage C covers your belongings, but some categories have their own much
smaller caps inside it. These are **not exclusions** — the property is
covered, just not for very much.

The usual categories are **money**, **securities and manuscripts**,
**watercraft and trailers**, and — **for theft specifically** — **jewellery,
watches and furs**, **firearms**, and **silverware**.

So if $40,000 of jewellery is stolen and the theft cap is $1,500, the policy
pays $1,500. The other $38,500 is yours to absorb.

**The fix is to schedule the property.** Scheduling means listing an item
separately on the policy with an agreed value, using an endorsement called a
**scheduled personal property floater**. Three things happen when you do:

1. The item is insured for its stated value rather than the small cap.
2. It is covered against **more** causes of loss.
3. The deductible usually disappears for that item.

**One more thing about Coverage C.** On most forms your belongings are paid at
**actual cash value** — what they were worth at the moment they were lost,
after subtracting for age and wear. A ten-year-old sofa pays a ten-year-old
sofa's worth, not the price of a new one. Paying the price of a new one is
called **replacement cost**, and on contents it is an extra you buy. Most
people who know to ask, buy it.

## Coverage D: loss of use

Two distinct parts:

- **Additional living expense** — the *increase* in ordinary living costs
  while the home is uninhabitable. Not the whole hotel bill: the increase over
  what the household would have spent anyway.
- **Fair rental value** — lost rent where part of the home was rented out.

Also payable where a **civil authority prohibits use** of the home because of
damage to *neighbouring* property by a covered peril, typically for up to two
weeks.

## Exclusions

Section I excludes, among others: **ordinance or law** (beyond the small
additional coverage), **earth movement**, **water damage** (flood, surface
water, sewer backup), **power failure** away from the premises, **neglect**,
**war**, **nuclear hazard**, **intentional loss**, and **governmental
action**. Wear and tear, mechanical breakdown, rot, mould, insects and vermin
are excluded as maintenance rather than risk.

Section II excludes **business pursuits**, **professional services**,
**motor vehicles** (with narrow exceptions for vehicles not subject to
registration, such as a ride-on mower on the premises), **aircraft**, larger
**watercraft**, **intentional injury**, and **workers' compensation**
obligations.

## How this is examined

**HO-3's asymmetry** — dwelling open peril, contents named peril.

**Which form for which insured** — renter, condominium owner, older home.

**The percentage relationships** between Coverages A, B, C and D.

**Coverage F pays without fault, and not to residents of the household.**

**Special limits** on jewellery, firearms and silverware, and that they are
limits rather than exclusions.

**Additional living expense is the increase**, not the total.

## Check yourself

1. Under an HO-3, lightning damages the house and a mysterious cause damages
   the contents. Which loss is easier to establish, and why?
2. A tenant wants coverage for belongings and liability but not the building.
   Which form?
3. Coverage A is $400,000. What are the usual limits for B and C?
4. A guest slips on the insured's steps and is injured. The insured is not
   negligent. Is anything payable?
5. A homeowner's $12,000 diamond ring is stolen. The policy has a $1,500
   special limit on theft of jewellery. What is the fix, and was the ring
   excluded?
6. Why does HO-8 exist?

## Answers

1. **The dwelling loss.** Coverage A is open peril, so the insured need only
   show a loss occurred; the insurer must prove an exclusion. Coverage C is
   named peril, so the insured must prove a listed peril caused the contents
   loss — and "mysterious cause" will not do it.
2. **HO-4.**
3. **B = $40,000** (10%), **C = $200,000** (50%).
4. **Yes** — Coverage F, medical payments to others, pays regardless of
   fault.
5. It was **limited**, not excluded — $1,500 is payable. The fix is to
   **schedule** the ring by endorsement.
6. Because for older homes replacement cost can far exceed market value,
   making full replacement cost coverage unaffordable and creating a moral
   hazard. HO-8 settles on a modified repair-cost basis instead.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2aa5db82-0689-5f02-8850-03dec995ef82', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
