-- Texas Exam Prep — content seed, chunk 2 of 28
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'How Insurance Works',
       'how-insurance-works', 'Why insurers can predict losses they cannot predict individually, and which risks they will not touch.', 2,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', c.id, $lesson$# The trick at the centre of insurance

An insurer cannot tell you whether *your* house will burn down this year.
Nobody can. Yet it will quite confidently tell you how many of one hundred
thousand similar houses will burn, and price your policy accordingly.

That is not a paradox, and the exam wants you to be able to say why.

## What insurance is

**Insurance is a contract — a device — by which one party agrees, for a
premium, to indemnify another against loss from specified perils.**

**Indemnify** means to restore the insured to the financial position they were
in immediately before the loss — no worse, and deliberately no better. It is
the principle the next lesson is built on; take it here as "make good, and no
more than good".

Two halves of that are worth separating, because the exam asks about each.

**As a contract, it transfers risk.** The insured hands the financial
consequence of a loss to the insurer and pays a known, small, certain amount
instead of facing an unknown, large, uncertain one. **Insurance is the
*transfer* technique** in the risk-management list below — that is its place
among the five, and a stem asking what "transfers risk from a person or
business to an insurance company" is asking for the word *insurance*.

**As a business, it works by pooling.** Transfer alone would just move the
problem. What makes the insurer able to accept it is that it has accepted
thousands of similar transfers, and the aggregate is predictable even though
no single one is.

So **transfer is what it does for the insured; pooling is what makes it
possible for the insurer.** The rest of this lesson is the second half.

## The law of large numbers

**The more similar exposures you observe, the closer actual losses come to
expected losses.**

Toss a coin four times and you might get four heads. Toss it four thousand
times and you will get close to half. Nothing about any individual toss became
more predictable; the *aggregate* did.

Insurance runs on exactly this. One house is unpredictable. A hundred thousand
similar houses are not. The insurer does not need to know which ones will
burn — only how many, near enough to set a price that covers the losses, the
expenses and a margin.

Two words in that sentence are doing heavy lifting. **Similar**: houses, not a
mixture of houses and oil refineries. **Many**: a handful of exposures gives
you no more certainty than one.

## What makes a risk insurable

The exam expects a list. Different textbooks phrase it differently, but the
substance is consistent, and each item is really a way of protecting the law
of large numbers.

**A large number of similar exposure units** — *homogeneous*. Without them the
mathematics does not work.

**The loss must be definite and measurable** — *measurable*, or *definite*.
You must be able to say when it happened, where, from what cause, and what it
cost. "My business felt less successful this year" is none of those things.

**The loss must be accidental** from the insured's standpoint — *accidental*,
also called *fortuitous* or *unintentional*. Outside their control. This is
the same principle that makes speculative risk uninsurable, seen from another
angle.

**The loss must not be catastrophic to the insurer** — *non-catastrophic*. If
a single event could wipe out every exposure at once, pooling has not spread
anything. This is why flood and earthquake sit outside standard property
policies, and why Texas handles windstorm on the coast through a separate
association.

**The chance of loss must be calculable** — *calculable*, or *predictable*.
You need data, or the price is a guess.

**The premium must be economically feasible** — *affordable*. If the honest
premium approaches the value of the thing insured, nobody sensible buys it. A
policy costing $90,000 a year to insure a $100,000 building has no market.

### Learn the substance, not the count

Some texts list six of these, some five, some seven. An option may appear as
one word — **calculable, affordable, non-catastrophic, homogeneous,
accidental, measurable** — or as a whole phrase, and the same idea travels
under several names: *homogeneous* and *a large number of similar exposure
units* are one item, not two.

So a question is never really asking you to count. It is asking whether a
described characteristic belongs, and **the wrong options are usually the
inversions**: that a loss must be catastrophic, or intentional, or that the
insured must be able to cause it. Each of those breaks the pooling the whole
list exists to protect. Test a candidate by asking what it would do to the law
of large numbers.

## Adverse selection

**Adverse selection is the tendency of those most likely to suffer a loss to
be the most eager to buy insurance.**

People who live on a floodplain want flood cover more than people on a hill.
Someone who has just felt a lump wants health cover more urgently than someone
who has not. Left alone, an insurer's pool fills up with exactly the exposures
it can least afford, and the pool stops resembling the population the price
was based on.

Nearly every piece of underwriting machinery exists to resist this:
applications, inspections, waiting periods, exclusions, pre-existing condition
clauses, and the underwriter's right to decline.

Do not confuse it with **moral hazard**, which the exam likes to place
nearby. Adverse selection happens *before* the policy, in who chooses to buy.
Moral hazard happens *after*, in how the insured behaves once covered.

## Where the premium goes

A premium has to cover three things: expected losses, the insurer's expenses
(commissions, salaries, taxes), and a margin for profit and contingencies. The
loss portion is often called the **pure premium**, and the amount added for
expenses and profit the **loading**.

This is worth knowing because it explains an answer that otherwise looks
strange: an insurer can be paying out less than it collects and still be
losing money, once expenses are counted.

## Risk management before insurance

Insurance is one response to risk, not the only one. The exam tests the full
set, usually by asking which one a described action represents.

- **Avoidance** — do not take the risk at all. Do not buy the building.
- **Retention** — accept it and pay losses yourself. A deductible is
  retention, and so is **choosing not to buy the cover at all** — a decision
  that the exposure is small enough to carry. Retention can be deliberate.
- **Reduction** (or control) — lower the frequency or severity. Sprinklers,
  training, locks.
- **Transfer** — move it to someone else. **Insurance is the transfer
  technique**; so is a hold harmless agreement in a contract.
- **Sharing** — spread it across a group, as partners or a pool do.

A common stem describes a business installing a sprinkler system and asks
which technique that is. It is *reduction*, not transfer — the sprinklers do
not move the risk to anybody, they make the loss smaller.

## How the policy reaches the buyer

An insurer still has to get its product in front of somebody. The
arrangements have names, and one question separates them more cleanly than
any definition: **who owns the renewals?**

That is not bookkeeping. The renewal right is the right to keep the customer —
so whoever holds it holds the relationship, and the whole structure of each
arrangement follows from it.

### Through producers

**Independent agent.** Contracts with several insurers and is not an employee
of any of them. **Owns the renewals**, so a client can be moved from one
carrier to another as terms change. The client belongs to the agency.

**Exclusive or captive agent.** Represents **one** insurer. Usually an
independent contractor rather than an employee, but **the insurer owns the
renewals** — leave, and the book stays.

**General agent or managing general agent.** Appointed to recruit, train and
supervise other producers across a territory, and paid an **override** on what
those producers write rather than only on personal production.

> **This is the one Texas licenses separately.** The blueprint names the
> **managing general agent** licence at TX.I.C.1.e, referring to 28 TAC
> §19.1201–.1206. Those rules are not among our sources, so the licence's
> requirements are not taught — see the licensing lesson in Module 5 and
> `docs/module-5-source-gaps.md`.

**Direct writer.** The producer is an **employee** of the insurer, paid salary,
commission, or both. **The insurer owns the renewals.**

### Without producers

**Direct response.** No producer at all. The insurer sells straight to the
public — post, telephone, print, broadcast, internet. There is nobody to
appoint, nobody to pay commission, and nobody to advise the buyer.

### The distinction that matters most

Cutting across all of these: **an agent represents the insurer; a broker
represents the insured.** That decides whose knowledge binds whom, and it is
treated fully in Module 2 alongside express, implied and apparent authority.

> **Marketing systems are not named on the Texas outline** — only the managing
> general agent licence is, as a licence type. They are here because a
> producer works inside one of these arrangements and should know which, not
> because the exam demands the taxonomy.

## How this is examined

**"Which of the following is not a characteristic of an insurable risk?"** —
usually with "the loss must be catastrophic" or "the insured must be able to
cause the loss" among the options. Work down the list.

**Law of large numbers questions** turn on the word *similar* or the word
*more*. The prediction improves with more exposures, and only if they resemble
one another.

**Adverse selection versus moral hazard** — ask when it happens. Before the
policy is written, it is adverse selection.

**Risk-management technique questions** describe an action and want the label.
Deductible → retention. Sprinklers → reduction. Buying a policy → transfer.
Not opening the business → avoidance.

## Check yourself

1. An insurer writes one hundred thousand homeowners policies instead of one
   hundred. What has improved, and what has not?
2. Why are floods difficult to insure through an ordinary property policy?
3. A contractor adds a clause making the client responsible for certain
   losses. Which risk-management technique is that?
4. A homeowner chooses a $2,500 deductible instead of $500. Which technique?

## Answers

1. The *predictability of the total* has improved. The predictability of any
   single house has not changed at all — that is the whole point of the law of
   large numbers.
2. One event damages an enormous number of exposures simultaneously, so the
   losses are not independent and the pool does not spread them. It is the
   "not catastrophic to the insurer" condition failing.
3. **Transfer** — the risk is moved to another party by contract. Insurance is
   not the only form of transfer.
4. **Retention** — they have chosen to carry more of each loss themselves.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Insurable Interest and Indemnity',
       'insurable-interest-and-indemnity', 'Who is allowed to insure what, and the rule that you may be made whole but never better off.', 3,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', c.id, $lesson$# Two rules that stop insurance becoming gambling

Insurance moves money to people after bad things happen. Two principles keep
that from becoming a betting shop, and between them they decide a great many
exam questions.

**Insurable interest** decides *who may buy*.
**Indemnity** decides *how much they may collect*.

## Insurable interest

**You may only insure something you would genuinely lose by.**

That is the whole rule. Everything else follows from it.

### Why it exists

Without the rule, anyone could take out a fire policy on a stranger's
warehouse and then hope for a fire. That gives a stranger a financial reason
to want the warehouse to burn — and gives the insurer no way to distinguish a
customer from an arsonist. Requiring an interest removes the motive.

It is also what separates insurance from a wager in law. A bet creates a risk
that did not exist before. Insurance transfers one that already did.

### When it must exist — the detail that is tested

Property and life insurance answer this differently, and the difference is
examined constantly.

**Property and casualty: at the time of the loss.**

You can insure a building and later sell it. If it burns after the sale, the
claim fails — not because you never had an interest, but because you no longer
had one when the loss happened.

**Life: when the policy is taken out, and not necessarily after.**

A woman insures her husband's life. They divorce. She remains the beneficiary
and the policy pays. The interest existed at inception, which is all life
insurance requires.

A neat way to hold it: **property asks "do you lose by this now?"; life asks
"did you have reason to buy this then?"**

### Who has one

- An **owner**, in their own property.
- A **lender or mortgagee**, up to the amount still owed. A bank holding a
  $200,000 mortgage has an interest of $200,000, not the value of the house.
- A **business**, in a key employee, or in property it holds for others.
- A **spouse**, in the other spouse's life; a parent in a dependent child's.
- A **tenant**, in improvements they have paid for.
- A **bailee** — a garage, a dry cleaner — in customers' property in their
  care.

### How much interest

Your interest is limited to what you stand to lose. A part-owner of a building
cannot insure the whole of it for their own benefit, and a lender cannot
recover more than the outstanding balance. This flows straight into the second
principle.

## Indemnity

**Indemnity means restoring the insured to the financial position they were in
immediately before the loss — no worse, and no better.**

The second half is the part that gets tested. If a loss could leave you better
off, somebody eventually arranges a loss.

Several familiar policy mechanisms are indemnity doing its work:

- **Actual cash value** settlements, which deduct depreciation so a
  twenty-year-old roof is not replaced with a new one at the insurer's expense.
- **Policy limits**, capping recovery at the amount insured.
- **Deductibles**, leaving part of every loss with the insured.
- **Other insurance clauses**, so two policies covering the same loss share it
  rather than each paying in full.
- **Subrogation**, letting the insurer step into the insured's shoes and
  recover from whoever caused the loss — which stops the insured collecting
  twice, once from the insurer and again from the wrongdoer.

### Where indemnity is deliberately set aside

The exam likes exceptions, and there are three worth knowing.

**Valued policies** pay an agreed amount regardless of actual value, used where
value is hard to establish after the fact — fine art, antiques.

**Replacement cost** coverage pays to replace without deducting depreciation,
which technically leaves the insured better off. It is sold anyway because
underinsurance after a total loss is a worse problem than the one it creates.

**Life insurance** is not a contract of indemnity at all. A life has no
measurable value, so the policy pays a stated sum. This is why insurable
interest is only required at inception.

## How this is examined

**"When must insurable interest exist?"** — the single most common question in
this area. Property: at the time of loss. Life: at inception.

**Fact patterns about lenders.** A mortgagee's interest is the balance
outstanding, not the property's value.

**"Which of these is not a contract of indemnity?"** — the answer is life
insurance, or a valued policy.

**Questions about collecting twice.** Subrogation and other-insurance clauses
both exist to prevent it; recognise them as indemnity in action.

## Check yourself

1. A man insures his house, then sells it. Two months later it burns. Does his
   policy respond? Why?
2. A bank holds a $150,000 mortgage on a $400,000 home. What is the extent of
   its insurable interest?
3. A woman insures her husband's life. They divorce, and she keeps paying the
   premiums. He dies. Does the policy pay?
4. An insurer pays a claim, then sues the driver who caused it. What is that
   called, and which principle does it serve?

## Answers

1. **No.** Property insurance requires an insurable interest **at the time of
   the loss**, and he no longer had one.
2. **$150,000** — the amount outstanding. A lender's interest is what it stands
   to lose, not what the property is worth.
3. **Yes.** Life insurance requires the interest only **when the policy is
   taken out**. It does not have to survive the marriage.
4. **Subrogation**, and it serves **indemnity** — without it the insured could
   recover twice for the same loss.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
