-- Texas Exam Prep — content seed, chunk 3 of 25
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Negligence and Liability',
       'negligence-and-liability', 'The four elements a claimant must prove, the defences against them, and the kinds of damages a court can award.', 6,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', c.id, $lesson$# Being at fault, precisely

Property insurance asks what something was worth. Liability insurance asks a
harder question: **were you legally responsible?**

Almost all of casualty insurance rests on negligence, and the exam tests it as
a checklist. Learn the checklist.

## The four elements

**A claimant must prove all four. Miss one and there is no negligence.**

**1. A duty owed.** The defendant owed the claimant a duty of care. Drivers owe
it to other road users; shopkeepers to customers; property owners to lawful
visitors.

**2. A breach of that duty.** They failed to act as a reasonable person would
in the circumstances. The standard is not perfection — it is reasonableness.

**3. Proximate cause.** The breach actually caused the harm, in an unbroken
chain. If something else intervened and caused it, the chain is broken.

**4. Damages.** The claimant actually suffered a loss. Carelessness that
injures nobody is not actionable.

A shop leaves a spill unmopped. A customer slips, breaks a wrist, and incurs
medical bills. Duty: the shop owes customers reasonable care. Breach: it left a
known hazard. Proximate cause: the spill caused the fall. Damages: the bills
and the injury. All four — negligence.

Change one fact. The customer sees the spill, walks round it, and goes home
unharmed. There is a duty and a breach, but no damages, and therefore no claim.

## Degrees and special forms of liability

**Gross negligence** — reckless indifference to others' safety, beyond ordinary
carelessness. It matters because it can expose a defendant to punitive damages.

**Strict liability** — liability **without proof of fault**. The claimant need
not show the defendant was careless, only that the thing caused the harm.
Product liability is the standard example; keeping a wild animal is another.

**Absolute liability** — liability **that no defence will escape**. Workers'
compensation is the clearest case: the employer pays for a workplace injury
regardless of fault, and regardless of the employee's own carelessness.
Blasting is the classic tort example.

> The blueprint lists **absolute**, **strict** and **vicarious** as three
> separate items, so this course keeps them apart even though many texts treat
> the first two as synonyms. The distinction, and why it matters, is in lesson
> 7.

**Vicarious liability** — responsibility for somebody else's negligence
because of a relationship. An employer for an employee acting within the scope
of employment; a parent for a child in some circumstances. The employer was not
careless; it is liable because the employee was.

## Defences

These come up as often as the elements.

**Comparative negligence** — the claimant's own share of fault reduces their
recovery. Most states use some version, and the details vary by state, so treat
the general principle as the examinable point here.

**Contributory negligence** — the older and harsher rule, under which any fault
by the claimant bars recovery entirely. Very few states still apply it, but it
appears in exam questions as a contrast to comparative negligence.

**Assumption of risk** — the claimant knowingly and voluntarily accepted a
known danger. Spectators at a baseball game and foul balls.

**Intervening cause** — something unforeseeable broke the chain between the
breach and the harm.

**Statute of limitations** — the claimant waited too long to bring the claim.

## Damages

Getting these labels straight is worth easy marks.

**Compensatory damages** make the claimant whole, and split in two:

- **Special damages** — specific, provable, economic losses. Medical bills,
  lost wages, the cost of repairs. You can put a receipt to them.
- **General damages** — real but not itemisable. Pain and suffering,
  disfigurement, loss of consortium.

**Punitive (exemplary) damages** punish the defendant and deter others, awarded
for gross negligence or deliberate wrongdoing rather than ordinary
carelessness. They are not compensation, and many liability policies do not
cover them.

The memory hook that survives exam pressure: **special is specific**.

## Occurrence and claims-made

Liability policies come in two triggers, and the distinction decides which
policy answers a claim.

**Occurrence** — responds to injury or damage that *happened* during the policy
period, whenever the claim is made. A 2020 policy answers a 2026 claim for a
2020 injury.

**Claims-made** — responds to claims *first made* during the policy period,
usually subject to a **retroactive date** before which injuries are not
covered. Common in professional liability, where harm may surface years later.

Because a claims-made policy stops responding when it ends, **extended
reporting periods** — "tail" coverage — exist to cover claims made after it
expires for acts committed while it was in force.

## How this is examined

**"Which element is missing?"** — a fact pattern that fails on one of the four.
Most often damages, or proximate cause.

**Special versus general damages** — sort by whether a receipt exists.

**Vicarious liability** — a stem where the person sued was not the person who
was careless.

**Occurrence versus claims-made** — ask whether the question emphasises when
the injury *happened* or when the claim was *made*.

**Strict liability** — look for inherently dangerous activity, and for the
absence of any allegation of carelessness.

## Check yourself

1. A driver runs a red light. Nobody is nearby and nothing happens. Has any
   element of negligence been satisfied, and is there a claim?
2. A delivery driver rear-ends a car while working. The employer is sued
   although it did nothing careless. What is this called?
3. A claimant is awarded $40,000 for medical bills and lost wages, and $60,000
   for pain and suffering. Label each.
4. A surgeon's 2023 operation causes harm discovered in 2026. Which policy
   responds under an occurrence form, and which under claims-made?

## Answers

1. Duty and breach are present. **Proximate cause and damages are not**, so
   there is no negligence claim. Carelessness that harms nobody is not
   actionable.
2. **Vicarious liability** — responsibility for an employee's negligence
   committed within the scope of employment.
3. $40,000 is **special damages** (specific, provable, economic). $60,000 is
   **general damages** (real but not itemisable). Both are compensatory.
4. **Occurrence:** the 2023 policy, because the injury happened then.
   **Claims-made:** the 2026 policy, because that is when the claim was first
   made — provided the retroactive date precedes 2023.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.V'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Terms the Other Lessons Assume',
       'terms-the-other-lessons-assume', 'Nine terms the blueprint names that do not belong to any one topic — and the three distinctions inside them that get tested.', 7,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', c.id, $lesson$# The vocabulary that sits between the other lessons

GK.II and GK.V are lists of **terms**, and the exam asks about them by name.
Most of them belong to a topic with a lesson of its own. These nine do not —
they are the connective tissue, and a question about one of them is usually a
definition question that you either know or do not.

Several are treated at more length later, where they do real work. This lesson
is where you find them under the name the blueprint uses.

## Direct and indirect loss

**A direct loss is physical damage to property caused by a peril.** Fire burns
the restaurant.

**An indirect loss is the financial consequence of that damage.** The
restaurant earns nothing for five months while it is rebuilt.

Indirect loss is also called **consequential loss**, and the two terms are
interchangeable on the exam.

The distinction matters because **they are covered by different coverages**. A
standard property form pays the direct loss. The indirect loss needs
**business income** and **extra expense** coverage, which is bought separately.
An insured who rebuilds and discovers the policy paid nothing for five months
of lost trading has bought one and not the other.

Examples of indirect loss: lost business income, extra expense, loss of rents,
additional living expense, spoilage following a power failure, loss of use.

> Fuller treatment: Module 3, *Commercial Property and the Package Policy*.

## Salvage value

**Salvage value is what damaged property is worth in its damaged state.**

It matters in two directions, and the exam tests the second.

**As a deduction.** Where the insurer pays a partial loss and the insured keeps
the damaged property, the salvage value may reduce the payment — the insured
still has something of value, and indemnity says they are restored, not
enriched.

**As the insurer's property.** Where the insurer **pays the loss in full**, it
generally acquires the right to the salvage. A total-loss vehicle paid out at
actual cash value becomes the insurer's to sell; a warehouse of smoke-damaged
stock paid in full becomes the insurer's to dispose of.

**Salvage rights follow payment.** That is the sentence to carry. The insurer
that pays for the item owns what is left of it, and any recovery reduces the
net cost of the claim — which is the same logic as subrogation, applied to
property instead of to a wrongdoer.

Do not confuse it with:

- **Market value** — what the property would sell for **undamaged**, which
  reflects location and demand as well as the structure.
- **Actual cash value** — replacement cost less depreciation.

> Fuller treatment of the valuation methods: lesson 4, *Valuing a Loss*.

## Vacancy and unoccupancy

Two words that mean the same thing in conversation and different things here.

**Unoccupied** — **the people are gone, the contents remain.** A family away
for three months. The building still looks lived in and still contains
everything worth stealing.

**Vacant** — **both the people and the contents are gone.** An empty house
between tenants.

**Vacancy is the one that restricts coverage.** After a building has been
vacant beyond a stated period — commonly **60 consecutive days** — several
perils are typically suspended: **vandalism and malicious mischief, glass
breakage, theft, sprinkler leakage** and **water damage**. Some forms also
reduce payment on any loss that does remain covered.

The underwriting logic is worth knowing because it explains the rule: an empty
building attracts vandalism, and a slow leak or a small fire runs for weeks
before anybody notices. The exposure genuinely changes.

The insured's fix is to tell the insurer and buy a **vacancy permit**.

> Fuller treatment: Module 3, *Dwelling Policies*.

## Blanket and specific insurance

**Specific insurance names an amount for one item at one location.**
$400,000 on the building at 14 Oak Street.

**Blanket insurance covers two or more items, or two or more locations, under
a single limit.** $1,200,000 across three warehouses, wherever the stock
happens to be.

The advantage of blanket is that it follows the property. A shifting inventory
insured specifically is over-insured at one site and under-insured at another
on any given day; insured blanket, the whole limit is available wherever the
loss occurs.

The price of it: blanket cover normally requires a **statement of values** and
a **high coinsurance percentage** — often 90% or 100% — because the insurer is
exposed at every location at once and needs the insurance-to-value discipline
that a specific limit would have provided.

> Fuller treatment: Module 3, *Commercial Property and the Package Policy*.

## Absolute, strict and vicarious liability

The blueprint names these as **three separate items**, so learn them as three.
Many texts treat "absolute" and "strict" as synonyms; this course keeps them
apart because the exam lists them apart.

**Absolute liability** — liability **that cannot be escaped by any defence**.
The defendant is liable for the harm, full stop. The classic examples are
**statutory**: workers' compensation, where the employer pays for a workplace
injury regardless of fault and regardless of the employee's own carelessness;
and some ultrahazardous activities such as **blasting**, where no amount of
care is a defence.

**Strict liability** — liability **without proof of fault**, but not
necessarily without any defence. The claimant need not show negligence; they
must still show the thing caused the harm. **Product liability** is the
standard example: a defective product makes the manufacturer liable whether or
not it was careless, though the manufacturer may still argue the product was
misused or altered. **Keeping a wild animal** is another.

The practical difference: **under strict liability the claimant is relieved of
proving fault; under absolute liability the defendant is relieved of nothing.**

**Vicarious liability** — liability for **somebody else's** negligence,
because of a relationship. An **employer** for an employee acting within the
scope of employment; a **vehicle owner** for a permissive driver; a **parent**
for a child in some circumstances.

The examinable feature: **the vicariously liable party did nothing wrong.** The
employer was not careless. Liability attaches because of the relationship, not
because of any act.

> Fuller treatment of negligence and its defences: lesson 6, *Negligence and
> Liability*.

## Binders

**A binder is temporary evidence that coverage is in force**, issued while the
policy is prepared.

- It may be **oral or written**.
- It carries the **same terms as the policy it anticipates**.
- It is **temporary** — it ends when the policy issues, when the insurer
  declines and gives notice, or at its own expiry.
- **An agent with binding authority binds the insurer**, even if the
  underwriter would have declined the risk. A broker generally cannot; a
  broker represents the buyer.

> Fuller treatment: Module 2, *The Declarations Page*.

## Certificates of insurance

**A certificate of insurance is evidence that a policy exists**, issued to
somebody who is not the insured — a landlord, a general contractor, a lender,
a client.

**It creates no coverage.** It summarises coverages, limits and dates as of
the day it was issued, and it becomes stale the moment anything changes. A
holder who wants actual rights under the policy must be added as an
**additional insured** by endorsement.

**Binder, certificate, policy** is the sequence to keep straight: a binder is
temporary **coverage**, a certificate is **proof** of somebody else's
coverage, and the policy is the contract.

## Endorsements

**An endorsement is a written amendment that adds to, deletes from or
otherwise changes the policy.** Called a rider in life insurance.

- It must be **in writing and attached**. A producer's promise does not amend
  a policy.
- It **takes precedence over conflicting printed policy language**, being the
  more specific and more recent statement of what was agreed.
- It may **broaden** coverage, **restrict** it, or merely **clarify** it.

## Deposit premium and audit

Some premiums cannot be calculated in advance, because they depend on
something not yet known — **payroll**, **sales**, **receipts**, or the number
of vehicles or employees.

For those policies:

1. The insurer estimates the exposure and charges a **deposit premium** at
   inception.
2. At the end of the policy period it conducts a **premium audit** of the
   actual figures.
3. It then issues an **additional premium** or a **return premium**.

**The insured must permit the audit and keep the records**, which is a policy
condition, not a courtesy. Refusing the audit can let the insurer estimate the
premium itself, usually unfavourably.

This is how **workers' compensation** and much **general liability** and
**commercial auto** business is rated. A business whose payroll doubles during
the year has not been underinsured — it has been under-*charged*, and the
audit corrects it.

> Fuller treatment: Module 4, *Workers' Compensation and Employers'
> Liability*.

## How this is examined

**Direct versus indirect loss**, and that they need different coverages.

**Salvage rights follow payment** — pay in full, own the remains.

**Vacant means the contents are gone too**, and it is vacancy that suspends
perils.

**Blanket covers several items or locations under one limit**, and demands a
higher coinsurance percentage.

**Vicarious liability attaches to somebody who did nothing wrong.**

**A binder creates coverage; a certificate does not.**

**An endorsement overrides conflicting printed language.**

**A deposit premium is an estimate, trued up by audit.**

## Check yourself

1. A fire closes a shop for four months. Name the direct loss and the indirect
   loss, and say which coverage pays each.
2. An insurer pays the full actual cash value on a stolen car that is later
   recovered, badly damaged. Who owns the wreck?
3. A homeowner spends six months abroad, leaving the house furnished. Vandals
   break in at month five. Vacant or unoccupied, and does it matter?
4. A wholesaler moves stock between four depots weekly. Blanket or specific,
   and what will the insurer require?
5. An employee, driving carefully, is hit by another vehicle while making a
   delivery and injures a pedestrian. On what basis might the employer be
   liable?
6. A contractor gives a property owner a certificate of insurance. Does the
   owner have coverage?
7. A contractor's payroll estimate was $400,000; the actual figure was
   $700,000. What happens at the end of the period?

## Answers

1. The **direct loss** is the fire damage to the building and contents, paid
   by the property coverage. The **indirect loss** is four months of lost
   trading, paid by **business income** (and extra expense), which must be
   bought separately.
2. **The insurer.** Salvage rights follow payment — having paid the loss in
   full, the insurer takes the salvage.
3. **Unoccupied** — the contents remained. It matters because the vacancy
   provisions, which suspend vandalism and related perils, apply to **vacant**
   buildings; an unoccupied one is generally still covered.
4. **Blanket**, so the single limit follows the stock. The insurer will
   require a **statement of values** and a **high coinsurance percentage**,
   commonly 90% or 100%.
5. **Vicariously** — the employee was acting within the scope of employment.
   Note the employer did nothing wrong; on these facts the employee may not
   have either, which is why the other driver's liability is the live issue.
6. **No.** A certificate is evidence of somebody else's coverage and creates
   none. The owner needed **additional insured** status by endorsement.
7. A **premium audit** determines the actual payroll and the insurer issues an
   **additional premium** for the difference.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
