-- Texas Exam Prep — content seed, chunk 3 of 30
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', 'ec98aec4-aec6-5d3e-93ae-dbb68098f16a', c.id, 'Dwelling Policies',
       'dwelling-policies', 'DP-1, DP-2 and DP-3 — the property-only forms for houses that do not qualify for a homeowners policy, and what each one covers.', 2,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', c.id, $lesson$**What this lesson covers.** The dwelling policy — the older, property-only
form used where a homeowners policy will not fit — and the three forms it
comes in.

**By the end you should be able to** say when a dwelling policy is written
instead of a homeowners policy, name what DP-1, DP-2 and DP-3 each cover and
on what peril basis, and say what a dwelling policy leaves out that a
homeowners policy includes.

Not every house fits a homeowners policy. The owner might not live there. The
house might be empty half the year. It might be too old, too cheap or in too
poor a condition for an insurer to want to write a full package on it.

For those, there is the **dwelling policy** — an older, plainer kind of cover.

The important difference is what it leaves out. A homeowners policy is a
package: your property *and* the harm you cause other people. **A dwelling
policy covers property only.** If the owner wants liability cover too, it is
added on separately by **endorsement** — an extra document attached to the
policy.

## When a dwelling policy is used instead

- **The owner does not live there.** A rental house is the common case: the
  landlord needs the building covered, and the tenant's belongings are the
  tenant's own problem.
- **The house is seasonal or empty** — a holiday cottage, a property between
  tenants.
- **The house does not qualify** for a homeowners policy — too low in value,
  in poor condition, or occupied in a way homeowners rules do not allow.
- **The owner only wants the building covered** and nothing else.

Dwelling policies are written on buildings housing **one to four families**,
with limits on how much business activity is allowed inside.

## The coverages

A dwelling policy uses letters like a homeowners policy does, but they are not
the same letters. This catches people out, so compare them deliberately.

| | Name | What it pays for |
| --- | --- | --- |
| **A** | Dwelling | The building itself |
| **B** | Other Structures | Detached buildings — usually **10% of Coverage A** |
| **C** | Personal Property | Belongings inside |
| **D** | Fair Rental Value | Rent the owner stops collecting while the house is unfit to live in |
| **E** | Additional Living Expense | The extra cost of living somewhere else |

Two things to hold on to:

**Loss of use is split in two here.** A homeowners policy puts lost rent and
extra living costs together in Coverage D. A dwelling policy separates them:
**D is lost rent, E is extra living costs.**

**DP-1 has no Coverage E at all.** The most basic form will pay a landlord for
the rent they are not collecting, but it will not pay for anyone to live
somewhere else. Coverage E starts at DP-2.

**Coverages B and C can lend to each other** on some forms — a slice of the
personal property limit can be moved to other structures, and the other way
round.

## B. Dwelling Policies

There are three forms. As with homeowners, they differ in how widely the
perils are covered, and they get broader — and more expensive — as you go up.

### 1. DP-1 — Basic

**The narrowest of the three.** Named peril on both the building and the
contents, with a short list.

The list starts at **fire, lightning and internal explosion**. Most owners add
two optional bundles on top:

- **Extended coverage** adds windstorm, hail, explosion, riot, aircraft,
  vehicles, smoke and volcanic eruption. Remember it as **WHARVES** if the
  letters help.
- **Vandalism and malicious mischief** can then be added after that.

Two things make DP-1 different from the other two, and both are examined:

**It pays actual cash value, not replacement cost.** If a twenty-year-old roof
burns, DP-1 pays what a twenty-year-old roof was worth — not what a new one
costs. The owner makes up the difference.

**Theft is not covered, and generally cannot be added.** If the house is
furnished and the owner wants theft cover, DP-1 is the wrong form.

### 2. DP-2 — Broad

**Named peril again, but a much longer list**, and it pays replacement cost.

DP-2 adds everything in DP-1's extended coverage, plus: falling objects; the
weight of ice, snow or sleet; water or steam escaping inside the house; a
heating system tearing apart, cracking, burning or bulging; freezing; sudden
damage from electrical current the house generated; and **damage by
burglars**.

> **"Damage by burglars" is not theft cover**, and the exam likes the
> difference.
>
> It pays for what burglars **break** — the forced door, the smashed window,
> the ransacked room. It does not pay for what they **take**.
>
> So a DP-2 owner who is burgled gets paid for the broken door and not for the
> stolen television. Covering the television needs theft coverage, added by
> endorsement.

**Loss settlement is replacement cost** on the building, provided the owner
insured it for enough.

### 3. DP-3 — Special

**The broadest, and the one most landlords buy.**

- **The building is open peril** — covered against everything except what the
  policy excludes.
- **The contents stay named peril**, on the broad list.

If that sounds familiar, it should: **it is the same split as the HO-3**, for
the same reason. The building is a fixed, inspectable thing. Contents move,
change and are easier to claim for dishonestly.

**Loss settlement is replacement cost** on the building.

### The three forms side by side

| | The building | The contents | How it pays | Theft |
| --- | --- | --- | --- | --- |
| **DP-1** | Named (basic) | Named (basic) | **Actual cash value** | No, and cannot be added |
| **DP-2** | Named (broad) | Named (broad) | **Replacement cost** | By endorsement |
| **DP-3** | **Open peril** | Named (broad) | **Replacement cost** | By endorsement |

## What a dwelling policy leaves out

**No liability cover.** If a tenant falls down the stairs and sues the
landlord, a bare dwelling policy does nothing. Personal liability and medical
payments are added by endorsement — and any sensible landlord adds them.

**No theft cover as standard.** Added by endorsement on DP-2 and DP-3. Not
available on DP-1.

**Few of the extras a homeowners policy gives free.** Debris removal, trees
and shrubs, credit card cover and the rest are thinner here or missing
altogether.

## What a landlord usually adds

- **Personal liability** and **medical payments** — the important ones.
- **Theft**, if the house is let furnished.
- **Vandalism and malicious mischief** — worth noting that this is often taken
  away again once a house has stood **empty beyond 60 days**.
- **Rental income**, beyond the fair rental value already included.
- **Automatic increase in insurance**, so the limit keeps up with building
  costs.

## Empty houses: vacancy and unoccupancy

These two words sound alike and mean different things. The exam separates
them, so learn them apart.

- **Unoccupied** — nobody is living there, but **the furniture is still in
  it**. A family away for three months.
- **Vacant** — **both the people and the furniture are gone.** An empty house
  between tenants.

**Vacancy is the one that costs you coverage.** Once a house has been vacant
beyond a stated period — usually **60 days in a row** — the policy typically
stops covering **vandalism, glass breakage, theft, sprinkler leakage and water
damage**, and some forms pay less on whatever is left.

The reasoning is practical. An empty house attracts vandals, and a leak or a
small fire can run for weeks before anyone notices.

The owner's answer is to **tell the insurer and buy a vacancy permit**.

## How this is examined

**Which form for a rental house**, and that liability must be added.

**DP-1's actual cash value settlement**, contrasted with DP-2 and DP-3's
replacement cost.

**DP-3's open peril dwelling / named peril contents split.**

**Theft is not standard** on any dwelling form.

**Vacancy versus unoccupancy**, and the 60-day suspension of vandalism and
related perils.

**Coverage D and E as separate coverages** here, combined in homeowners.

## Check yourself

1. A landlord owns a rented house and wants building coverage plus protection
   against a tenant's injury claim. What policy and what addition?
2. Under a DP-1, a covered fire destroys a 30-year-old roof. How is the loss
   settled?
3. Which dwelling form matches the HO-3's peril structure?
4. A house stands empty with all furniture removed for 75 days. Vandals break
   in and damage it. Likely outcome?
5. Is theft included in a standard DP-2?

## Answers

1. A **dwelling policy** with a **personal liability** (and medical payments)
   endorsement.
2. **Actual cash value** — replacement cost less depreciation. DP-1 offers no
   replacement cost option.
3. **DP-3** — open peril on the dwelling, named peril on contents.
4. **No coverage.** The dwelling is **vacant** (people and contents gone)
   beyond 60 days, and vandalism is among the perils suspended.
5. **No.** Theft is added by endorsement on DP-2 and DP-3, and is not
   available on DP-1.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
