-- Texas Exam Prep — content seed, chunk 4 of 25
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'The Declarations Page',
       'the-declarations-page', 'What a policy is made of, and why the first page is the one that answers most questions.', 1,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', c.id, $lesson$# The page that identifies this policy from every other one

Every policy in property and casualty is assembled from the same four parts.
Learn the four, and a question about an unfamiliar form becomes a question
about which part you are being shown.

## The four parts

Remembered as **DICE**:

- **D**eclarations — who, what, where, when, how much
- **I**nsuring agreement — what the insurer promises
- **C**onditions — the rules both sides must follow
- **E**xclusions — what is not covered

Plus **endorsements**, which amend any of the four.

The order matters logically as well as mnemonically. The insuring agreement
makes a broad promise; the exclusions carve pieces out of it; the conditions
say what each side must do to keep the promise alive; and the declarations
attach all of it to one named insured, one property, one period and one set
of numbers.

## What is on the declarations

**The declarations page is the only part of the policy unique to this
insured.** Everything else is printed the same for everybody who buys the
form. The declarations are typed.

They carry:

- **The named insured** and mailing address.
- **The policy period** — inclusive dates *and times*. Most policies begin
  and end at 12:01 a.m. standard time at the insured's address, which is why
  a policy running to "1 June" does not cover a fire at noon on 1 June.
- **The description of the property or operation** insured — address,
  construction, occupancy, or for auto, the year, make and vehicle
  identification number.
- **The coverages purchased and their limits.**
- **The deductibles.**
- **The premium.**
- **The forms and endorsements attached**, by number. This list is how you
  prove what the policy actually consists of.
- **The mortgagee or loss payee**, where one has an interest.
- **The producer** and the insurer.

A useful way to hold it: **the declarations answer "who, what, where, when
and how much." The rest of the policy answers "under what circumstances."**

## Where the declarations come from: the application

The declarations are the insurer's restatement of the **application**. The
application is the insured's request for coverage and the insurer's primary
source of underwriting information, and the answers in it are
**representations** — statements believed true when made. Sign it, and it is
usually made part of the policy by reference.

Two consequences the exam likes:

- **Read the declarations when the policy arrives.** They are the insured's
  chance to catch an error before a claim does. An address, a limit or a
  deductible that does not match what was asked for is fixed by endorsement,
  not by argument at claim time.
- **A wrong answer on the application follows you onto the declarations.**
  If the application understated the square footage, the declarations show
  the wrong value and the coinsurance clause will be measured against the
  wrong number.

## Endorsements

**An endorsement is a written amendment that adds to, deletes from or
otherwise changes the policy.** Also called a rider, mostly in life
insurance. It must be in writing and attached; a producer's promise does not
amend a policy.

What the exam wants:

- An endorsement **takes precedence over conflicting printed policy
  language**. It is the more specific and more recent statement of what the
  parties agreed.
- Endorsements can **broaden** coverage (adding a peril, scheduling an item),
  **restrict** it (excluding a hazard the underwriter will not accept), or
  merely **clarify** it.
- They usually carry a premium change, and appear on the declarations by
  form number.

## Binders

**A binder is temporary evidence that coverage is in force**, issued while
the policy is prepared.

- It may be **oral or written**, though a written one is what anybody sensible
  uses. Many states, and most insurers' own rules, require written
  confirmation within a set period.
- It carries the **same terms as the policy it anticipates** — it is not a
  separate, thinner contract.
- It is **temporary**. It ends when the policy is issued, or when the insurer
  declines and gives notice, or at its own expiry.
- An agent with **binding authority** can bind the insurer on the spot. A
  broker generally cannot; a broker represents the buyer.

That last point is the one that gets tested: **a binder issued by an agent
with binding authority creates coverage even if the insurer would later have
declined the risk.**

## Certificates of insurance

**A certificate of insurance is evidence that a policy exists** — issued to
somebody who is *not* the insured and who needs proof: a landlord, a general
contractor, a lender, a client.

It is not a policy and it is not a binder. **It creates no coverage.** It
summarises coverages, limits and dates as of the day it was issued, and it
becomes stale the moment anything changes. A certificate holder who wants
actual rights under the policy needs to be added as an **additional insured**
by endorsement — a certificate alone does not do it.

## How this is examined

**"Which part of the policy contains X?"** Limits, dates, named insured,
deductible, mortgagee → declarations. The promise to pay → insuring
agreement. Duties after a loss, cancellation, appraisal, other insurance →
conditions. What is not covered → exclusions.

**Binder questions**, testing that it is temporary, may be oral, and binds
the insurer to the same terms as the policy.

**Certificate questions**, testing that it confers no coverage on the holder.

**Endorsement precedence** — where an endorsement conflicts with the printed
form, the endorsement governs.

## Check yourself

1. Which part of the policy names the mortgagee?
2. A policy period reads "1 March 2026 to 1 March 2027". Is a loss at 3 p.m.
   on 1 March 2027 covered?
3. An agent with binding authority binds coverage by phone. The insurer's
   underwriter would have declined the risk. Is there coverage?
4. A contractor gives a property owner a certificate of insurance. The
   contractor's policy is cancelled a week later and a loss occurs. Does the
   owner have coverage under the certificate?
5. An endorsement says "windstorm excluded"; the printed form lists windstorm
   as a covered peril. Which governs?

## Answers

1. The **declarations**.
2. **No.** Coverage ended at 12:01 a.m. on 1 March 2027. The policy period is
   inclusive of its start and exclusive of anything after its stated end time.
3. **Yes.** Binding authority is the authority to obligate the insurer;
   whether the underwriter would have chosen the risk is a matter between
   agent and insurer.
4. **No.** A certificate is evidence of coverage as of its issue date and
   creates none of its own. The owner needed additional insured status.
5. The **endorsement**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Insuring Agreement, Conditions and Exclusions',
       'insuring-agreement-conditions-and-exclusions', 'The promise, the rules attached to it, and the reasons an insurer says no.', 2,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', c.id, $lesson$# The promise and everything that qualifies it

The declarations tell you whose policy this is. These three parts tell you
what it does.

## The insuring agreement

**The insuring agreement is the insurer's promise.** It is usually a short
paragraph, and it is the broadest statement in the contract — everything
after it narrows.

It answers three questions: what is covered, against what, and on what
trigger.

### Named peril and open peril

This is the most-tested distinction in property insurance.

**A named peril policy covers only the perils it lists.** If the cause of
loss is not on the list, there is no coverage. Fire, lightning, windstorm,
hail, explosion, riot, aircraft, vehicles, smoke, vandalism, theft.

**An open peril policy covers every cause of loss except those excluded.**
Also called "all risk" or "special form" — though "all risk" is a misleading
name, because no policy covers everything. The exclusions define it.

**Where the burden of proof sits is the reason this matters.**

- Under a **named peril** form, **the insured** must show the loss was caused
  by a listed peril.
- Under an **open peril** form, **the insurer** must show the loss falls
  within an exclusion.

That shift is worth more to an insured than the list of perils is, and it is
the answer to "why does an open peril form cost more?"

### Occurrence and claims-made

In liability insurance the insuring agreement also states a **trigger**.

- An **occurrence** policy responds to injury or damage that **happens during
  the policy period**, no matter when the claim is made. A 2026 policy still
  answers a claim brought in 2034 for a 2026 injury.
- A **claims-made** policy responds to claims **first made during the policy
  period**, subject to a **retroactive date**. Injury before the retroactive
  date is not covered no matter when the claim arrives.

Claims-made forms need **tail coverage** — an extended reporting period — when
the policy ends, or claims arriving after expiry have nothing to attach to.

## Conditions

**Conditions are the rules of the contract** — what each side must do, and
what happens if they do not. They appear as a numbered list, and a great many
exam questions live here.

The recurring ones:

- **Duties after a loss** — notice, proof of loss, protecting property,
  cooperating. Covered in its own lesson.
- **Cancellation and non-renewal** — who may end the policy, how, and with
  how much notice.
- **Other insurance** — how this policy shares with another covering the same
  loss.
- **Subrogation** — the insurer's right to step into the insured's shoes and
  pursue whoever caused the loss.
- **Appraisal** — how a dispute over the *amount* of a loss is resolved.
- **Assignment** — the policy may not be transferred to somebody else without
  the insurer's written consent. Insurance is a **personal contract**: the
  insurer agreed to cover *this* insured, and selling the building does not
  sell the policy with it.
- **Abandonment** — property may not be abandoned to the insurer. The insured
  cannot dump a damaged item on the insurer's doorstep and demand the limit.
- **Liberalization** — if the insurer broadens the form during the policy
  period without extra premium, existing insureds get the broader coverage
  automatically.
- **Inspection and audit** — the insurer may inspect the property and examine
  the books, which matters where premium depends on payroll or sales.
- **Concealment, misrepresentation or fraud** — the policy is void where the
  insured has concealed or misrepresented a material fact.

**Conditions are promises, and breaking one can cost the claim.** That is the
practical difference between a condition and an exclusion: an exclusion says
the loss was never covered; a breached condition says it was, and the insured
forfeited it.

## Exclusions

**Exclusions remove coverage the insuring agreement would otherwise have
given.** They are not arbitrary. Each one exists for a reason, and the exam
asks about the reason as often as the exclusion.

### Why insurers exclude things

- **The loss is not fortuitous.** Wear and tear, deterioration, rust,
  inherent vice, mechanical breakdown. These are certainties on a long enough
  timescale, so they are maintenance, not risk.
- **The loss is catastrophic.** Flood, earthquake, war, nuclear hazard. The
  law of large numbers fails where one event hits every policy at once.
- **Coverage belongs in another policy.** Auto exposures are excluded from
  homeowners; professional liability from the CGL; workers' compensation from
  employers' general liability. Excluding here is not refusing to insure — it
  is directing the risk to the form built for it.
- **The loss is intentional.** No policy covers damage the insured caused on
  purpose. This is public policy, not underwriting.
- **The risk needs separate underwriting or pricing.** Business pursuits in a
  home, high-value jewellery, aircraft. Often the exclusion can be bought back
  by endorsement.

### Standard exclusions worth recognising

- **Ordinance or law** — the extra cost of rebuilding to a current building
  code. The code changed; the policy insured the building as it was.
- **Earth movement** and **water damage** (surface water, flood, sewer
  backup) — both usually available by endorsement or separate policy.
- **Wear and tear, latent defect, inherent vice**.
- **Intentional loss**.
- **War**, **nuclear hazard**, **governmental action** (seizure, destruction
  by order).
- **Neglect** — failing to save property at and after the loss.

### Limitations are not exclusions

A **limitation** caps coverage rather than removing it. A homeowners policy
covering theft of jewellery up to $1,500 has not excluded jewellery; it has
limited it. The fix is different too — a limitation is raised by **scheduling
the property**, an exclusion is removed by **buying it back**.

## How this is examined

**Named peril versus open peril**, and specifically **who must prove what**.

**"Why is this excluded?"** — match the exclusion to its reason:
non-fortuitous, catastrophic, covered elsewhere, intentional, separately
underwritten.

**Occurrence versus claims-made**, usually with a date sequence and a
retroactive date.

**Conditions as forfeiture** — the insured who waits eight months to report,
or refuses to submit to examination under oath, or assigns the policy without
consent.

**Ordinance or law**, which reliably catches people, because the rebuilding
cost feels like part of the fire loss and is not.

## Check yourself

1. A loss is caused by something not listed as a covered peril, under a named
   peril form. Who has failed to prove what?
2. An insured sells an insured building and hands the buyer the policy. Is
   the buyer covered?
3. A restaurant's walk-in freezer fails from age and the food spoils. Covered
   under an open peril form? Why or why not?
4. A claims-made policy has a retroactive date of 1 January 2024. A claim is
   made in March 2026 for an injury in 2023. Covered?
5. A fire destroys 60% of a building. The city requires the remainder be
   demolished and the replacement built to current code, adding $80,000.
   Which exclusion is in play?

## Answers

1. **The insured** has failed to prove the loss was caused by a covered
   peril. Under a named peril form that burden is theirs.
2. **No.** Insurance is a personal contract and the assignment condition
   requires the insurer's written consent.
3. **No.** Mechanical breakdown and wear and tear are excluded — the loss is
   not fortuitous. Equipment breakdown coverage is the form that answers it.
4. **No.** The injury predates the retroactive date.
5. **Ordinance or law.** The policy insured the building that existed, not the
   one the current code requires.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

commit;
