-- Texas Exam Prep — content seed, chunk 5 of 30
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', 'ec98aec4-aec6-5d3e-93ae-dbb68098f16a', c.id, 'Inland Marine',
       'inland-marine', 'Coverage for property that moves, property that is unusually valuable, and property no standard form handles well.', 4,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', c.id, $lesson$**What this lesson covers.** Inland marine insurance: what it is, why a line
named after the sea covers property on land, and the floaters you will meet in
both personal and commercial lines.

**By the end you should be able to** say what kinds of property qualify for
inland marine, explain why somebody buys a floater rather than relying on a
homeowners or commercial form, and name the common personal and commercial
floaters and what each is for.

Start with the name, because it will otherwise bother you all lesson.
**Inland marine has almost nothing to do with water.**

## Why it is called that

Marine insurance is the oldest insurance there is: cover for cargo crossing the
sea. When goods began moving on from the docks by rail and road, the same
underwriters followed them off the ship and carried on insuring them overland.
That extension got called **inland** marine, and the name stuck.

Over time it grew to cover a much wider idea: **property that moves, property
somebody else is looking after, and property a normal fire policy cannot value
sensibly.**

**Ocean marine** is still its own thing — ships, cargo at sea, and the
liabilities that go with them.

## What counts as inland marine

A risk belongs here if one of these is true:

- **The property moves about.** Goods in transit, a builder's tools, a sales
  rep's samples.
- **It is small, portable and valuable.** Jewellery, cameras, musical
  instruments, paintings.
- **It is part of how things move or communicate.** Bridges, tunnels,
  pipelines, radio masts. These do not move at all — they are here for
  historical reasons, because they were classed long ago as
  "instrumentalities of transportation". If that seems arbitrary, it is; learn
  it as a list.
- **Somebody else is holding it.** A repairer with a customer's equipment, a
  dry cleaner with a customer's coat.

## Why anyone buys it

A standard property policy covers property **at a place**. Inland marine
covers property **wherever it happens to be**. That is the main thing, and
there are three more:

- **It is usually open peril** — covered against everything except the
  exclusions — where a standard form is often named peril.
- **The value can be agreed up front.** For a painting or an antique, that
  matters enormously. Without it, the owner and the insurer would argue for
  months about what a one-off object was worth on the morning it was
  destroyed.
- **There is usually no coinsurance** on scheduled items, so no penalty for
  getting the amount slightly wrong.

**These policies are called floaters**, because the cover floats along with
the property instead of staying at an address.

## D. Inland Marine

### 1. Personal Articles Floaters

#### The personal articles floater

**This lists valuable personal items one by one, each with an agreed value.**

The standard categories are: **jewellery · furs · cameras · musical
instruments · silverware · golf equipment · fine art · stamp and coin
collections.**

It is sold either as an endorsement bolted on to a homeowners policy — called
**scheduled personal property** — or as a policy in its own right.

**Why bother?** Because a homeowners policy caps exactly these categories at
small amounts, mostly for theft. Scheduling a $12,000 ring does four things:

1. The cap disappears — it is insured for the $12,000 you agreed.
2. It is covered against **more causes of loss**, usually open peril.
3. The **deductible usually goes away** for that item.
4. The value is settled **now**, not argued about after it is gone.

#### The personal property floater

Instead of listing items one by one, this covers **everything the insured
owns**, anywhere in the world, on an open peril basis. Thorough, uncommon, and
expensive.

### 2. Commercial Property Floaters

#### A rule about what may be written here

Because inland marine forms are flexible and lightly regulated, insurers were
once tempted to write ordinary fire business on them to escape the rules that
govern fire rates.

So regulators publish a **nationwide marine definition** — a list of what is
allowed to be written as inland marine. **Controlled** classes have filed
rates; **uncontrolled** classes can be negotiated case by case.

#### The floaters a business buys

Do not try to memorise these as definitions. Read each as *"who has this
problem?"*

**Contractor's equipment floater** — a builder's diggers, mixers and power
tools, covered on site, between sites and in the van.

**Installation floater** — materials from the moment they leave the supplier
until they are installed and signed off. The contractor's version of builders
risk.

**Motor truck cargo** — a haulier's responsibility for the goods on its lorry.

**Transportation or trip transit** — goods on the move generally, or one
particular shipment.

**Bailee's customers** — for anybody holding customers' property: a dry
cleaner, a repair shop, a storage warehouse.

> This one has a feature worth noticing. **It usually pays whether or not the
> business was at fault.**
>
> Strictly, a dry cleaner is only liable for a customer's burnt suit if it was
> careless. But telling a customer "we burnt your suit and it was not our
> fault, so no" is a good way to lose every customer they ever speak to. The
> coverage is written to let the business simply pay.

**Accounts receivable** — money owed to the business that it cannot collect
because the records burned, plus what it costs to rebuild the records and
chase the money.

**Valuable papers and records** — the cost of **recreating** damaged documents
and records. It pays for the work of reconstruction, not for what the
information was worth in the abstract.

**Electronic data processing** — computers, software and data, open peril,
and usually including **mechanical breakdown and electrical disturbance**,
which ordinary property forms leave out.

Also named classes: **signs**, **jewellers block**, **furriers block**,
**physicians and surgeons equipment**, **theatrical property**.

**Instrumentalities of transportation and communication** — the bridges,
tunnels, pipelines, power lines and masts from earlier.

#### Bailee terminology

- A **bailee** holds another's property. A **bailor** owns it.
- A **bailee's customers form** covers the customers' goods regardless of
  fault.
- **Legal liability** forms cover only what the bailee is legally responsible
  for — cheaper, and much less useful when the customer is angry.

## How this is examined

**"Which of these is an inland marine risk?"** — look for movement,
portability with high value, bailment, or an instrumentality of
transportation.

**Why schedule jewellery?** — to remove the homeowners special limit, broaden
to open peril, agree the value and drop the deductible.

**Bailee's customers pays regardless of negligence.**

**Accounts receivable and valuable papers pay for reconstruction**, not for
the debt or the information as an asset.

**A bridge is inland marine**, which feels wrong until you know the history.

## Check yourself

1. A photographer owns $30,000 of camera equipment used at client sites. What
   form, and why not the homeowners policy?
2. A dry cleaner's premises burn, destroying customers' garments. The cleaner
   was not negligent. Which form pays the customers?
3. Why does a floater usually have no coinsurance clause?
4. A contractor's excavator is damaged while being towed between sites. Which
   floater?
5. A fire destroys a firm's ledgers and it cannot collect $200,000 of debts.
   Which coverage, and what does it pay?

## Answers

1. A **personal articles floater** or a commercial camera floater. The
   homeowners policy limits cameras, covers them on a named peril basis away
   from home, and would settle on actual cash value.
2. A **bailee's customers form**, which pays regardless of the bailee's
   negligence.
3. Because scheduled items carry **agreed or stated values** — the insurer has
   already accepted the value, so there is nothing for a coinsurance clause to
   police.
4. A **contractor's equipment floater**.
5. **Accounts receivable** coverage — the uncollectible sums, the cost of
   reconstructing the records, and the extra collection expense.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', 'ec98aec4-aec6-5d3e-93ae-dbb68098f16a', c.id, 'The National Flood Insurance Program',
       'the-national-flood-insurance-program', 'Why flood is excluded from every standard policy, how the federal programme covers it, and the limits and waiting period that apply.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', c.id, $lesson$**What this lesson covers.** Flood: why every standard property policy
excludes it, how the National Flood Insurance Program covers it instead, and
the rules a flood policy runs on.

**By the end you should be able to** explain why the private market will not
write flood, say how a community and its property owners come to be covered,
state the waiting period and the limits, and say what the programme counts as
a flood — and what it does not cover.

Here is a fact worth getting used to early: **no ordinary property policy
covers flood.** Not homeowners, not dwelling, not commercial property. If a
river comes through the front door, none of the policies in this module pay.

That is not an oversight, and once you see why, everything else about flood
insurance follows.

## E. National Flood Insurance Program

### Why insurers will not cover flood

In Module 2 you will meet the conditions a risk has to satisfy before anyone
can sensibly insure it. Flood fails several of them at once.

**The losses all arrive together.** Insurance works by pooling — thousands of
customers pay, a few of them claim, and the premiums of the many cover the
losses of the few. That only works if the losses are **unrelated**. A flood is
the opposite: it does not damage one house on the flood plain, it damages
every house on the flood plain, on the same afternoon. The insurer collects a
thousand small premiums and then pays a thousand large claims at once.

**Only the people who need it would buy it.** Nobody living on a hill buys
flood insurance. Everybody living beside a river does. So the pool would be
made up almost entirely of properties expected to flood — which is called
**adverse selection**, and it is fatal to pricing.

**For the worst properties it is not really a risk at all.** A house that
floods every few years is not an uncertainty to be insured; it is a
maintenance schedule with a bill attached.

So in **1968 Congress created the National Flood Insurance Program**, run by
**FEMA**. The federal government took on the risk the private market would
not.

### How a town gets into the programme

This is the part people find surprising: **the deal is with the community, not
with you.**

A town or county has to **adopt and enforce flood plain building rules** —
how high new buildings must sit, how they must be built, where building is
not allowed at all. In return, **federally backed flood insurance becomes
available to property owners in that community.**

**If the community is not in the programme, you cannot buy the policy.** An
owner in a non-participating area has to find a private insurer or go without.

There are two stages:

- **The emergency programme** — a starting stage with **limited amounts** of
  cover, while the flood maps are being drawn.
- **The regular programme** — full limits, once the community has its flood
  map and its building rules in place.

### The 30-day wait

**A flood policy does not start the day you buy it. Normally you wait 30
days.**

The reason is obvious once stated: without it, people would buy flood
insurance when the forecast turned bad, and the programme would only ever be
paying claims.

Three exceptions are worth knowing:

- **No wait when a lender requires the insurance** as part of making,
  increasing, extending or renewing a loan.
- **One day** when the cover is bought because the flood map changed.
- **A shortened wait** for property affected by wildfire on federal land.

### What a flood is

The programme's definition is specific, and questions are built on it. A
flood is a **general and temporary condition of partial or complete
inundation of two or more acres of normally dry land, or of two or more
properties**, from:

- overflow of inland or tidal waters,
- unusual and rapid accumulation or runoff of surface water,
- mudflow, or
- collapse of land along a body of water from erosion or an unusually severe
  storm.

Two consequences:

- **Water entering one building alone is generally not a flood** — a burst
  pipe, a backed-up sewer, a leaking roof. Two acres or two properties is the
  threshold.
- **Mudflow counts; landslide generally does not.** Mudflow is liquid mud
  flowing; a landslide is earth movement, excluded.

### What is covered

Two separate coverages, bought separately:

**Building property** — the structure and its foundation, electrical and
plumbing, furnaces and water heaters, built-in appliances, permanently
installed carpet, and detached garages (within a portion of the limit).

**Personal property (contents)** — furniture, clothing, portable appliances,
washers and dryers, and a limited amount for valuables.

**Contents are not automatically included.** An owner who buys building
coverage only has no coverage for anything inside. That is a favourite
question.

### Limits

Under the **regular programme**, the maximum amounts available are:

| | Building | Contents |
| --- | --- | --- |
| **Residential** | **$250,000** | **$100,000** |
| **Non-residential / commercial** | **$500,000** | **$500,000** |

These are **programme maximums**, not appraised values. Anybody needing more
buys **excess flood** from the private market.

### Loss settlement

- **Replacement cost** is available on a **single-family dwelling that is the
  insured's principal residence**, insured to at least 80% of replacement
  cost.
- **Everything else is actual cash value** — contents always, and buildings
  that are secondary homes, rentals or commercial.

### What is not covered

- **Contents in a basement**, beyond a very short list of building items.
  Finished basements are largely uninsurable under the programme.
- **Additional living expense and loss of use** — the NFIP pays for the
  property, not for the disruption.
- **Currency, precious metals and valuable papers.**
- **Property outside the building** — landscaping, decks, patios, fences,
  septic systems, swimming pools.
- **Vehicles**, which belong on an auto policy's other-than-collision
  coverage.
- **Business interruption.**

### Zones, maps and requirements

FEMA publishes a **Flood Insurance Rate Map** for each participating
community, dividing it into **flood zones**.

- **Zones A and V** are **Special Flood Hazard Areas** — the 100-year flood
  plain, meaning a 1% annual chance of flooding. **V zones are coastal**, with
  additional wave action.
- **Zones B, C and X** are moderate or minimal risk, where coverage is
  cheaper and often bought voluntarily.

**Mandatory purchase:** a building in a Special Flood Hazard Area with a
**federally backed or federally regulated mortgage** must carry flood
insurance. This is the single largest driver of NFIP sales.

**Write Your Own.** Private insurers issue and service NFIP policies under
their own names, with the **federal government carrying the risk**. The
producer sells what looks like a private policy; the terms, limits and rates
are the programme's.

## How this is examined

**The 30-day waiting period** and its exceptions.

**The two-acre / two-property definition** of a flood.

**Contents must be bought separately.**

**The $250,000 / $100,000 residential limits.**

**Replacement cost applies only to a principal residence**; everything else is
ACV.

**Community participation is a precondition.**

**Basements, landscaping and living expense are not covered.**

## Check yourself

1. A homeowner buys an NFIP policy on 1 May. The river floods on 20 May. Is
   there coverage?
2. A burst water main floods only the insured's basement. Is this a "flood"
   under the programme?
3. An owner buys $250,000 of building coverage. A flood destroys $60,000 of
   furniture. What is paid?
4. A rental house owned as an investment suffers flood damage to a 15-year-old
   roof. Replacement cost or actual cash value?
5. A community declines to adopt flood plain management ordinances. Can its
   residents buy NFIP coverage?
6. What is the maximum building coverage on a commercial property?

## Answers

1. **No** — the 30-day waiting period has not run, and no exception applies.
2. **No.** A flood requires inundation of **two or more acres or two or more
   properties**; water in one building from a burst main is not one.
3. **Nothing.** Contents coverage must be purchased separately.
4. **Actual cash value.** Replacement cost is limited to a single-family
   dwelling that is the insured's **principal residence**.
5. **No.** Community participation is a precondition.
6. **$500,000**, with a further $500,000 available for contents.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
