-- Texas Exam Prep — content seed, chunk 6 of 25
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '52333f53-7203-52c7-90e1-39181aad19a7', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Other Insurance, Subrogation and Supplementary Payments',
       'other-insurance-subrogation-and-supplementary-payments', 'How two policies covering one loss divide it, how the insurer recovers from whoever caused it, and what a liability policy pays on top of the limit.', 6,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '52333f53-7203-52c7-90e1-39181aad19a7', c.id, $lesson$# Three conditions that all protect the same principle

Indemnity says an insured is restored, not enriched. Two of these conditions
enforce it. The third is the exception that proves the rule.

## Other insurance

**When more than one policy covers the same loss, the insured still collects
only once.** The other insurance condition decides how the insurers divide
it.

### Pro rata

**Each insurer pays the share its limit bears to the total of all limits.**
The standard method for property insurance.

> Insurer's share = (its limit ÷ total of all limits) × the loss

Two policies, $300,000 and $100,000, covering a $40,000 loss:

- Total limits = $400,000
- The $300,000 policy pays 300/400 × $40,000 = **$30,000**
- The $100,000 policy pays 100/400 × $40,000 = **$10,000**

The insured collects **$40,000** — the loss, not $80,000.

### Contribution by equal shares

**Each insurer pays equal amounts until the loss is paid or its limit is
exhausted**, after which the rest continue. Common in liability insurance.

A $90,000 loss against limits of $100,000 and $50,000: each pays $45,000.
Had the loss been $120,000, the smaller policy would stop at $50,000 and the
larger would pay $70,000.

### Primary and excess

**One policy pays first and the other only after the first is exhausted.**
Not sharing — a queue.

The exam's standard illustrations:

- **Auto liability follows the car.** The owner's policy is **primary**; the
  driver's own policy is **excess**.
- A **homeowners** policy is primary for premises liability; a **personal
  umbrella** sits excess above it.
- **Non-owned** auto coverage in a business auto policy is typically excess
  over the vehicle owner's insurance.

### Excess and escape clauses

An **excess clause** says this policy pays only above other collectible
insurance. An **escape clause** says it pays nothing at all where other
insurance exists. Where two policies both claim to be excess, courts usually
make them share; where an escape clause would leave the insured with nothing,
it is often disregarded.

## Subrogation

**Subrogation is the insurer's right, after paying a claim, to step into the
insured's position and pursue whoever caused the loss.**

Three reasons it exists, all worth knowing:

1. **It preserves indemnity.** Without it, an insured could collect from the
   insurer and then sue the wrongdoer and end up ahead.
2. **It puts the cost on the party at fault**, not on the insurer's pool of
   policyholders.
3. **It holds premiums down**, since recoveries return to the pool.

### The rules

- **The insurer's rights are no better than the insured's.** If the insured
  had no claim against the third party, neither has the insurer.
- **The insured must not prejudice the right.** Signing a waiver of recovery
  *after* a loss can void coverage. Signing one *before* a loss — a hold
  harmless in a lease or construction contract — is usually permitted, and
  the exam likes this before-and-after distinction.
- **The insured must cooperate** in the recovery action.
- **Recovery order.** The insured is generally made whole first: money
  recovered goes to the insured's uninsured loss (including the deductible)
  before the insurer recoups.
- **No subrogation against your own insured.** An insurer cannot subrogate
  against a party insured under the same policy.

Subrogation applies to **property and liability** insurance, which are
contracts of indemnity. It does **not** apply to life insurance or to most
personal accident coverage, which are valued contracts — there is no
"wrongdoer to recover from" in the indemnity sense, and no over-recovery to
prevent.

## Supplementary payments

**Supplementary payments are amounts a liability policy pays in addition to
its limit of liability.** This is the exception to indemnity's tidiness: the
insurer pays these because defending the claim is in its own interest.

The list is stable across liability forms:

- **Defence costs** — attorney's fees and the expense of investigating and
  defending, including claims the insurer believes to be groundless.
- **The cost of bonds to release attachments**, up to the policy limit.
- **The premium on appeal bonds** — the insurer pays the premium, not the
  face amount of the bond.
- **The premium on bail bonds** arising from a covered accident, subject to a
  stated maximum (commonly $250 in auto forms).
- **Reasonable expenses incurred by the insured at the insurer's request**,
  including lost earnings up to a stated daily amount (commonly $250).
- **Post-judgment interest** on the entire judgment, and **pre-judgment
  interest** where awarded.
- **Court costs** taxed against the insured.

Two things to keep straight:

- **The insurer pays the premium for a bond, not the bond itself.** A
  question offering "the insurer posts a $100,000 appeal bond" is testing
  exactly this.
- **Supplementary payments stop when the limit is exhausted.** Once the
  insurer has paid its limit in judgments or settlements, the duty to defend
  ends and so do these.

## How this is examined

**Pro rata calculations** with two limits and one loss — the arithmetic is
easy; the trap is answering with the total of both payments as though the
insured collected twice.

**Primary versus excess in auto**, through the borrowed-car fact pattern.

**Waiver of subrogation before versus after a loss.**

**Defence costs outside the limit**, and the moment they stop.

**Bond premium versus bond amount** in supplementary payments.

## Check yourself

1. A $60,000 loss is covered by policies with limits of $200,000 and
   $100,000, both pro rata. What does each pay, and what does the insured
   receive?
2. After a fire caused by a contractor's negligence, the insured signs a
   release of the contractor and then claims on the policy. What is the
   likely result?
3. A friend borrows the insured's car and causes an accident. Which policy is
   primary?
4. A liability policy has a $300,000 limit. The insurer spends $75,000
   defending a suit that settles for $300,000. What is the total outlay, and
   what happens to a second suit arriving the next week?
5. An insurer pays a $10,000 claim on which the insured bore a $1,000
   deductible, then recovers $6,000 from the party at fault. Who gets what?

## Answers

1. The $200,000 policy pays 200/300 × $60,000 = **$40,000**; the $100,000
   policy pays **$20,000**. The insured receives **$60,000** — the loss.
2. Coverage is likely **void** for that loss. The insured destroyed the
   insurer's subrogation right after the loss occurred.
3. **The car owner's policy** is primary; the driver's own policy is excess.
4. **$375,000** — defence costs are in addition to the limit. The limit is
   now exhausted, so the insurer has **no duty to defend** the second suit.
5. The insured is generally made whole first, so the **$1,000 deductible**
   comes back to the insured and the insurer keeps **$5,000**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '52333f53-7203-52c7-90e1-39181aad19a7', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Elements of a Contract',
       'elements-of-a-contract', 'The four things every contract needs, and the six ways an insurance contract is unlike most others.', 7,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', c.id, $lesson$# Why a policy is a contract, and what kind

An insurance policy is a legally enforceable agreement. The exam asks two
separate questions about that: what makes it enforceable at all, and what
makes it a peculiar sort of contract.

## The four elements

Every contract, insurance or otherwise, requires all four. Miss one and there
is no contract.

### 1. Offer and acceptance — "agreement"

One party proposes terms; the other accepts them.

**In insurance, the applicant makes the offer.** This catches people out,
because it feels as though the insurer, with its brochures and rate tables,
is the one offering. It is not. The applicant offers by submitting a
completed application **with the initial premium**; the insurer accepts by
**issuing the policy** — or by **binding coverage**, where the agent has
binding authority.

A **counter-offer** is a rejection of the original offer plus a new one. If
the insurer issues a policy on terms different from those applied for — a
higher premium, an added exclusion — it has made a counter-offer, and the
applicant is free to decline.

### 2. Consideration

**Each side must give up something of value.**

- **The insured's consideration** is the premium *and* the statements made in
  the application.
- **The insurer's consideration** is the promise to pay covered losses.

Note that the insurer's consideration is a *promise*, not money. It is the
promise that makes the contract binding, which is why an insurer that never
has a claim has still given full consideration.

### 3. Competent parties

**Both parties must be legally capable of contracting.** Generally this
excludes minors, persons legally declared incompetent, and those under the
influence of drugs or alcohol at the time of contracting. The insurer must
also be competent — that is, **licensed and authorised** to transact
insurance in the state.

### 4. Legal purpose

**The contract must not be for an illegal purpose or contrary to public
policy.** Insuring a smuggling operation, or insuring property in which you
have no insurable interest so that you profit from its destruction, fails
here. **Insurable interest is the legal purpose requirement doing its work**
in insurance — without it, the contract is a wager.

Some texts add a fifth, **legal form**, meaning the policy must meet the
form requirements the state imposes. Where a question offers four elements,
they are the four above.

## The distinguishing characteristics

An insurance contract has six features that mark it out. These are reliably
examined, usually by giving a definition and asking for the word.

**Adhesion.** One party writes it; the other takes it or leaves it. The
insured does not negotiate clause by clause.

> **The consequence is the rule you must know: ambiguity is construed against
> the drafter.** Where a policy term can reasonably be read two ways, the
> reading favourable to the insured wins — because the insurer chose the
> words. This principle, *contra proferentem*, is the single most useful
> thing to take from this lesson.

**Aleatory.** The exchange of value is **unequal and depends on chance**. An
insured pays $1,200 and may collect nothing, or may collect $400,000. A
non-aleatory contract — buying a car — exchanges roughly equal value both
ways.

**Unilateral.** **Only one party makes a legally enforceable promise.** Once
the premium is paid, the insured has promised nothing further; the insurer
alone is bound to perform. The insured who stops paying is not sued for
breach — the policy simply lapses.

**Conditional.** **Performance depends on conditions being met.** The insurer
pays only if a covered loss occurs and the insured has met their duties —
notice, proof of loss, cooperation.

**Personal.** **The contract is with a person, not a thing.** It follows the
insured, not the property, which is why it may not be assigned without the
insurer's consent. Selling the building does not sell the policy.

**Utmost good faith** (*uberrimae fidei*). **Both parties rely on the other's
honesty to a degree ordinary commerce does not require.** The insurer cannot
inspect every fact about the risk, so it relies on the applicant's disclosure;
the insured relies on the insurer's promise to pay a claim years away. This is
the principle beneath representations, warranties and concealment.

A useful check: **A**dhesion, **A**leatory, **U**nilateral, **C**onditional,
**P**ersonal, **U**tmost good faith.

## The application, and signing it

The application is where the contract starts, and the blueprint names it in its
own right. Three things about it are examined.

**The signature is what adopts the statements.** Everything written on the
application becomes the applicant's **representation** the moment they sign —
which is what makes Module 2's misrepresentation and concealment rules bite.
An applicant who lets somebody else fill the form in and signs without reading
it has still made every statement on it.

**The agent signs as the producer, never as the applicant.** An agent who signs
an applicant's name — however convenient, however clearly the applicant agreed
on the phone — has **signed another's name without authority**, which is the
definition of **forgery** from the crime lesson. It is also a **fraudulent or
dishonest act or practice** under **§4005.101(b)(5)**, an independent ground to
deny, suspend or revoke a licence. There is no version of this that is
harmless, and "the client asked me to" is not a defence.

**The signed application is usually attached to and made part of the policy.**
That is why the declarations restate it, and why a discrepancy between what was
applied for and what was issued matters: the insured can see both.

Texas puts the signature to work in several places already met:

- **§4005.004(a)(5)** defines a **"customer"**, for compensation disclosure, as
  **the person signing the application** for insurance, or the authorised
  representative of the insured actually negotiating the placement.
- **§2151.102(b)** requires **the applicant and the servicing agent** to
  certify, **as part of the application**, that the applicant was rejected by at
  least two insurers, before TAIPA will assign the risk.
- **§1952.101(c)** and **§1952.152** let a named insured remove uninsured
  motorist or personal injury protection coverage **only by rejecting it in
  writing** — a signature is what makes the rejection exist at all.

The pattern: **where Texas wants certainty about what somebody agreed to, it
asks for a signature.**

## Agency: why the agent's knowledge is the insurer's

An agent represents the **insurer**. A broker represents the **insured**.
That difference decides who is bound by what.

An agent's authority comes in three forms:

- **Express** — what the agency agreement actually says: solicit, bind, issue
  certain policies, collect premiums.
- **Implied** — what is reasonably necessary to carry out the express
  authority, though unstated. Renting an office, advertising.
- **Apparent** (ostensible) — what a reasonable member of the public would
  believe the agent has, from the insurer's own conduct. An agent still
  holding the insurer's signs, forms and rate manuals after termination can
  bind the insurer to a third party who reasonably relies on them.

Two doctrines follow, and they are examined often:

**Waiver** — the **voluntary surrender of a known right**. An insurer that
accepts a late premium without objection has waived the timeliness of
payment for that occasion.

**Estoppel** — a party is **barred from asserting a right** because their own
earlier conduct led the other to rely on the opposite, to their detriment. An
adjuster who tells the insured not to bother with a formal proof of loss
estops the insurer from later denying the claim for want of one.

**Knowledge of the agent is knowledge of the insurer.** Where an applicant
tells the agent something material and the agent omits it from the
application, the insurer is generally held to have known it.

## How this is examined

**"Who makes the offer?"** The applicant.

**"What is the insured's consideration?"** The premium *and* the statements in
the application.

**Matching definitions to the six characteristics**, most often aleatory,
unilateral and adhesion.

**"Ambiguity is resolved in favour of whom, and why?"** The insured, because
the policy is a contract of adhesion.

**Apparent authority** through a terminated-agent fact pattern.

**Waiver versus estoppel** — voluntarily giving up a right versus being
barred from asserting one.

**The applicant signs the application; the agent never signs for them.** Doing
so is forgery, and a ground for discipline under §4005.101(b)(5).

## Check yourself

1. An applicant submits a completed application with the first premium. Who
   has made the offer, and how does the other party accept?
2. A policy term is capable of two reasonable readings. Which is applied?
3. Which characteristic explains why a policy cannot be assigned to the buyer
   of the insured building?
4. An insured stops paying premium. Can the insurer sue for breach of
   contract? Why or why not?
5. An adjuster tells an insured "don't worry about the proof of loss, we have
   what we need". The insurer later denies the claim for lack of a proof of
   loss. What doctrine applies?
6. An applicant tells the agent about a prior fire loss; the agent leaves it
   off the application. Is the insurer deemed to know?

## Answers

1. **The applicant** made the offer. The insurer accepts by **issuing the
   policy**, or by **binding** coverage through an agent with binding
   authority.
2. The reading **favourable to the insured** — the contract is one of
   adhesion and ambiguity is construed against the drafter.
3. **Personal.** The contract is with the insured, not the property.
4. **No.** The contract is **unilateral**: only the insurer made an
   enforceable promise. The policy lapses instead.
5. **Estoppel.** The insurer's own conduct induced the insured's reliance.
6. **Yes.** Knowledge of the agent is imputed to the insurer.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

commit;
