-- Texas Exam Prep — content seed, chunk 11 of 28
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '65f6bec4-114d-558c-9035-89adbd274ada', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Territory and the Terrorism Risk Insurance Act',
       'territory-and-the-terrorism-risk-insurance-act', 'Where a policy works geographically, and the federal backstop that made terrorism insurable again.', 10,
       'draft', 11
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '65f6bec4-114d-558c-9035-89adbd274ada', c.id, $lesson$# Two provisions about where and what

Both are small, both appear in the blueprint twice — once under policy
provisions and contract law, once under casualty policy provisions — and both
are easy marks if you have read them once.

## Territory

**The territory (or policy territory) provision states where coverage
applies.** A policy is not worldwide unless it says so.

The usual definition in general liability and auto forms covers:

- **The United States**, including its territories and possessions;
- **Puerto Rico**; and
- **Canada**.

That is the core. Forms then extend it in two ways:

- **International waters or airspace**, but only in transit between places in
  the territory above.
- **Anywhere in the world** for a narrow set of exposures — typically
  **products** manufactured or sold in the territory that cause injury
  elsewhere, and the **independent activities of a person temporarily
  outside** the territory on the insured's business — **provided the suit is
  brought within the territory**.

That proviso is the examined point. **A worldwide extension usually still
requires that the lawsuit be brought in the United States (or Canada).** A
product made in Texas that injures somebody in Germany is covered if the suit
is filed in a US court; a German judgment obtained in a German court
generally is not.

Property forms take a different approach: **coverage attaches to described
premises**, and property away from the premises is covered only by specific
extensions or by an inland marine form, which is where property genuinely in
transit belongs.

In **personal auto**, the territory is the United States, its territories and
possessions, Puerto Rico and Canada. **Mexico is not included** — a driver
going to Mexico needs a Mexican policy from a Mexican insurer, because Mexico
does not recognise foreign auto insurance. This is a favourite question.

## The Terrorism Risk Insurance Act

### Why it exists

Before September 2001, terrorism was not excluded from most commercial
property and liability policies — it was simply not thought about, and was
covered by silence. The losses that followed made insurers move to exclude
it, and reinsurers to withdraw. Commercial property development stalled where
lenders required terrorism coverage that no longer existed.

**TRIA, enacted in 2002 and extended several times since, is a federal
backstop: the government shares in insured losses from certified acts of
terrorism, so that private insurers can afford to offer the coverage.**

It is a **reinsurance programme**, not an insurance policy. Nobody buys a
policy from TRIA.

### How it works

**Certification.** Losses are covered by the programme only for an act of
terrorism **certified by the Secretary of the Treasury**, in consultation with
other federal officials. Certification requires that the act be violent or
dangerous to human life, property or infrastructure, committed as part of an
effort to coerce the United States civilian population or influence policy,
and that aggregate insured losses **exceed a statutory trigger**.

**Mandatory offer.** **An insurer writing commercial property and casualty
insurance must offer terrorism coverage** on terms not differing materially
from the rest of the policy. This is the obligation that matters to a
producer.

**The insured may decline.** Coverage is not compulsory for the buyer.
Where the insured rejects it, the insurer may attach a terrorism exclusion.
**The rejection should be in writing**, and the premium for the coverage must
be **separately stated** so the insured knows what they are accepting or
declining.

**Loss sharing.** Each insurer retains a deductible calculated as a
percentage of its own earned premium. Above that, the federal government pays
a share of losses and the insurer the remainder, subject to an annual
aggregate cap on the whole programme.

### What it does and does not cover

- It applies to **commercial** lines. Personal lines are outside the
  programme, although personal policies are generally silent on terrorism and
  so tend to cover it.
- **Nuclear, biological, chemical and radiological** losses are generally
  excluded from the coverage offered, unless the underlying policy covers
  them.
- **Domestic as well as foreign** acts have been certifiable since the 2007
  reauthorisation removed the requirement that the act be committed on behalf
  of a foreign interest.
- **Workers' compensation is different.** A workers' compensation insurer
  **may not exclude terrorism at all**, because state law requires the policy
  to cover statutory benefits whatever the cause. The insured has no right to
  decline it there.

That last point is the trap. **Everywhere else the insured may reject
terrorism coverage; in workers' compensation they may not.**

## How this is examined

**Mexico** in personal auto territory.

**The worldwide products extension**, and the requirement that suit be
brought within the policy territory.

**The mandatory offer** — the insurer must offer, the insured may decline,
the premium must be separately stated, the rejection should be written.

**Certification by the Secretary of the Treasury**, not by the insurer or the
state regulator.

**Workers' compensation cannot exclude terrorism.**

## Check yourself

1. An insured drives from Houston to Monterrey. Does the personal auto policy
   respond to an accident there?
2. A product manufactured in the United States injures a consumer in France,
   who sues in a French court. Is the CGL's worldwide extension likely to
   respond?
3. Who certifies an act of terrorism for TRIA purposes?
4. A commercial insured does not want terrorism coverage. May the insurer
   simply leave it out of the quote?
5. May a workers' compensation policy exclude terrorism?

## Answers

1. **No.** Mexico is outside the policy territory; a Mexican policy from a
   Mexican insurer is required.
2. **No.** The extension generally requires the **suit to be brought within
   the policy territory**.
3. **The Secretary of the Treasury**, in consultation with other federal
   officials.
4. **No.** The insurer must **offer** the coverage with the premium
   separately stated; the insured then declines, preferably in writing.
5. **No.** Statutory benefits must be paid whatever the cause, so terrorism
   cannot be excluded from workers' compensation.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '65f6bec4-114d-558c-9035-89adbd274ada', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2aa5db82-0689-5f02-8850-03dec995ef82', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Homeowners Forms',
       'homeowners-forms', 'Six forms, six coverages and two sections — and the handful of differences the exam actually tests.', 1,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2aa5db82-0689-5f02-8850-03dec995ef82', c.id, $lesson$# One package, six variations

A homeowners policy is a **package**: property and liability in one contract.
That is its defining feature, and it is why it replaced the older practice of
buying a fire policy and a separate liability policy.

Learn the structure once; the six forms are then just differences in who is
covered and on what peril basis.

## The structure

**Section I — Property**

| | Covers |
| --- | --- |
| **Coverage A — Dwelling** | The house, and structures attached to it |
| **Coverage B — Other Structures** | Detached: garage, shed, fence |
| **Coverage C — Personal Property** | Contents, anywhere in the world |
| **Coverage D — Loss of Use** | Additional living expense and fair rental value |

**Section II — Liability**

| | Covers |
| --- | --- |
| **Coverage E — Personal Liability** | Bodily injury and property damage the insured is legally liable for |
| **Coverage F — Medical Payments to Others** | Medical costs for others injured on the premises, **regardless of fault** |

### The relationships between the limits

These are reliably examined, because they are derived rather than chosen:

- **Coverage B is typically 10% of Coverage A.**
- **Coverage C is typically 50% of Coverage A** (often 40% in some forms).
- **Coverage D is typically 20–30% of Coverage A**, depending on the form.

Set Coverage A and the rest follow, though each can be increased for extra
premium.

**Coverage F is a no-fault coverage.** It pays medical expenses of an injured
guest without any finding of negligence, with a short reporting window —
typically three years from the accident. It does **not** cover the insured or
regular residents of the household, which is the point candidates miss: your
own family's injuries are a health insurance matter.

## A. Homeowners

The outline lists six forms under **I.A**, and the exam tests the differences
between them rather than any one in isolation. Read the table first, then each
form in the outline's own order.

| Form | Who | Dwelling (A) | Contents (C) |
| --- | --- | --- | --- |
| **HO-2** Broad | Owner-occupant | **Named peril** (broad) | **Named peril** |
| **HO-3** Special | Owner-occupant | **Open peril** | **Named peril** |
| **HO-4** Contents / tenants | **Renter** | none | **Named peril** |
| **HO-5** Comprehensive | Owner-occupant | **Open peril** | **Open peril** |
| **HO-6** Unit-owners | **Condominium owner** | limited (see below) | **Named peril** |
| **HO-8** Modified | Owner of an older home | **Named peril** | **Named peril** |

### 1. HO-2 — Broad Form

**Named peril on both sides.** The dwelling and the contents are each covered
against the perils on the broad list and nothing else. It is the plainest of
the owner-occupant forms, and it is the baseline the others are measured
against: every form below it either widens the peril basis or changes who the
policy is for.

### 2. HO-3 — Special Form

**HO-3 is the one most people own**, and its asymmetry is the most-tested fact
in this lesson: **the dwelling is open peril, the contents are named peril.**

### 3. HO-4 — Contents Form (tenants)

**HO-4 is the renter's policy** — no Coverage A at all, because the tenant
does not own the building. It does carry Coverage C, D, E and F.

### 4. HO-5 — Comprehensive Form

**HO-5 upgrades the contents to open peril** as well. That is the whole
difference between HO-3 and HO-5.

### 5. HO-6 — Unit-Owners Form

**HO-6 is the condominium owner's policy.** Coverage A is limited — commonly
a small default such as $5,000, increasable — because the association's
master policy covers the building. The unit owner's Coverage A answers for
what is inside the walls: fixtures, cabinetry, improvements and betterments,
and whatever the master policy leaves to the unit owner. Read the master
policy to know which.

### 6. HO-8 — Modified Coverage Form

**HO-8 exists for older homes whose replacement cost far exceeds their market
value** — a large Victorian in a low-value neighbourhood, where rebuilding
would cost several times what the house could be sold for. Insuring it for
full replacement cost would be unaffordable and would create a moral hazard.
So **HO-8 settles losses on a modified basis** — repair cost using common
construction materials and methods, rather than full replacement — and pairs
that with a narrower named peril list.

## Eligibility

- The insured must be an **owner-occupant** (HO-2, 3, 5, 8), a **tenant**
  (HO-4), or a **unit owner** (HO-6).
- Dwellings of up to **four families** are eligible, with the insured
  occupying one unit; no more than a stated number of roomers or boarders per
  unit.
- **Farms are not eligible** — a farmowners policy covers those.
- **Incidental business occupancies** may be permitted by endorsement; a full
  business needs a commercial policy.

## Named perils worth knowing

The **basic** group: fire or lightning, windstorm or hail, explosion, riot or
civil commotion, aircraft, vehicles, smoke, vandalism or malicious mischief,
theft, volcanic eruption.

The **broad** group adds: falling objects; weight of ice, snow or sleet;
accidental discharge or overflow of water or steam; sudden and accidental
tearing apart, cracking, burning or bulging of a heating or
air-conditioning system; freezing; sudden and accidental damage from
artificially generated electrical current.

**Open peril forms cover everything not excluded**, which shifts the burden of
proof onto the insurer.

## Additional coverages

Included without extra premium, usually in modest amounts:

- **Debris removal**, **reasonable repairs**, and **property removed** from
  danger.
- **Trees, shrubs and other plants** — a percentage of Coverage A, with a
  per-item cap and a limited peril list. **Not** windstorm damage to a tree,
  which is the standard trap.
- **Fire department service charge.**
- **Credit card, forgery and counterfeit money**, commonly $500.
- **Loss assessment** — the unit owner's share of a condominium association
  assessment.
- **Collapse**, and **glass breakage**.
- **Ordinance or law**, at a small percentage of Coverage A.

## Special limits on Coverage C

Certain categories of personal property carry **sub-limits** — not exclusions,
limits. Typical categories: money and bullion; securities and manuscripts;
watercraft and trailers; jewellery, watches and furs **for theft**; firearms
**for theft**; silverware **for theft**.

The fix is to **schedule the property** — list each item with a stated value —
by endorsement, usually a **scheduled personal property** floater. Scheduling
also broadens the covered perils and commonly removes the deductible.

**Loss settlement on Coverage C is actual cash value** in most forms.
**Replacement cost on contents is an endorsement**, and a commonly sold one.

## Coverage D: loss of use

Two distinct parts:

- **Additional living expense** — the *increase* in ordinary living costs
  while the home is uninhabitable. Not the whole hotel bill: the increase over
  what the household would have spent anyway.
- **Fair rental value** — lost rent where part of the home was rented out.

Also payable where a **civil authority prohibits use** of the home because of
damage to *neighbouring* property by a covered peril, typically for up to two
weeks.

## Exclusions

Section I excludes, among others: **ordinance or law** (beyond the small
additional coverage), **earth movement**, **water damage** (flood, surface
water, sewer backup), **power failure** away from the premises, **neglect**,
**war**, **nuclear hazard**, **intentional loss**, and **governmental
action**. Wear and tear, mechanical breakdown, rot, mould, insects and vermin
are excluded as maintenance rather than risk.

Section II excludes **business pursuits**, **professional services**,
**motor vehicles** (with narrow exceptions for vehicles not subject to
registration, such as a ride-on mower on the premises), **aircraft**, larger
**watercraft**, **intentional injury**, and **workers' compensation**
obligations.

## How this is examined

**HO-3's asymmetry** — dwelling open peril, contents named peril.

**Which form for which insured** — renter, condominium owner, older home.

**The percentage relationships** between Coverages A, B, C and D.

**Coverage F pays without fault, and not to residents of the household.**

**Special limits** on jewellery, firearms and silverware, and that they are
limits rather than exclusions.

**Additional living expense is the increase**, not the total.

## Check yourself

1. Under an HO-3, lightning damages the house and a mysterious cause damages
   the contents. Which loss is easier to establish, and why?
2. A tenant wants coverage for belongings and liability but not the building.
   Which form?
3. Coverage A is $400,000. What are the usual limits for B and C?
4. A guest slips on the insured's steps and is injured. The insured is not
   negligent. Is anything payable?
5. A homeowner's $12,000 diamond ring is stolen. The policy has a $1,500
   special limit on theft of jewellery. What is the fix, and was the ring
   excluded?
6. Why does HO-8 exist?

## Answers

1. **The dwelling loss.** Coverage A is open peril, so the insured need only
   show a loss occurred; the insurer must prove an exclusion. Coverage C is
   named peril, so the insured must prove a listed peril caused the contents
   loss — and "mysterious cause" will not do it.
2. **HO-4.**
3. **B = $40,000** (10%), **C = $200,000** (50%).
4. **Yes** — Coverage F, medical payments to others, pays regardless of
   fault.
5. It was **limited**, not excluded — $1,500 is payable. The fix is to
   **schedule** the ring by endorsement.
6. Because for older homes replacement cost can far exceed market value,
   making full replacement cost coverage unaffordable and creating a moral
   hazard. HO-8 settles on a modified repair-cost basis instead.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2aa5db82-0689-5f02-8850-03dec995ef82', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
