-- Texas Exam Prep — content seed, chunk 12 of 28
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Dwelling Policies',
       'dwelling-policies', 'The property-only forms for houses that do not qualify for a homeowners policy.', 2,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', c.id, $lesson$# When a homeowners policy will not do

The dwelling policy is the older, narrower form. Where a homeowners policy is
a package, **a dwelling policy is property insurance alone** — liability is
optional and added by endorsement.

## When it is used

- **The dwelling is not owner-occupied** — a rental house, where the owner
  needs the building covered but not the tenant's belongings.
- **The dwelling is seasonal or vacant.**
- **The insured does not qualify** for a homeowners policy — value too low,
  condition too poor, occupancy of the wrong kind.
- **The owner wants building coverage only.**

Eligible dwellings are generally one- to four-family, with limits on
permitted incidental business.

## The coverages

| | Covers |
| --- | --- |
| **Coverage A — Dwelling** | The building |
| **Coverage B — Other Structures** | Detached structures, commonly **10% of A** |
| **Coverage C — Personal Property** | Contents |
| **Coverage D — Fair Rental Value** | Lost rent while the dwelling is unfit |
| **Coverage E — Additional Living Expense** | The increase in living costs |

Two differences from homeowners worth holding:

- **Loss of use is split into two lettered coverages here** (D and E), where
  homeowners combines them into Coverage D.
- **Coverage B and C may be used interchangeably in some forms** — a portion
  of the Coverage C limit can be applied to other structures, and vice versa.

**DP-1 does not include Coverage E at all.** Additional living expense is a
DP-2 and DP-3 feature.

## The three forms

### DP-1 — Basic

**Named peril**, and the narrowest of the three.

The standard perils are **fire, lightning and internal explosion**, with
**extended coverage** available — windstorm, hail, explosion, riot, aircraft,
vehicles, smoke, volcanic eruption — and **vandalism and malicious mischief**
available on top of that.

Two distinguishing features:

- **Loss settlement is actual cash value.** DP-1 does not offer replacement
  cost on the dwelling.
- **Theft is not covered** and generally is not available.

### DP-2 — Broad

**Named peril**, with the broad list — everything in DP-1's extended coverage
plus falling objects; weight of ice, snow or sleet; accidental discharge of
water or steam; tearing apart of a heating system; freezing; accidental damage
from artificially generated electrical current; and **damage by burglars**.

> **"Damage by burglars" is not theft cover**, and the difference is examined.
> It pays for what burglars *break* — a forced door, a smashed frame, a
> ransacked room — and not for what they **take**. A DP-2 insured whose house
> is burgled is paid for the door and not for the television.
>
> Theft of the contents needs theft coverage, which a dwelling form adds by
> endorsement. This is the same boundary as commercial property, where Basic
> and Broad reach vandalism but **only Special adds theft**.

**Loss settlement is replacement cost** on the dwelling, subject to the
usual insurance-to-value requirement.

Additional living expense and fair rental value are both included.

### DP-3 — Special

**Open peril on the dwelling and other structures; named peril on personal
property.**

This is the same asymmetry as the HO-3, and for the same reason — and it is
tested the same way. **Loss settlement is replacement cost** on the building.

| | Dwelling | Contents | Settlement | Theft |
| --- | --- | --- | --- | --- |
| **DP-1** | Named (basic) | Named (basic) | **ACV** | No |
| **DP-2** | Named (broad) | Named (broad) | **Replacement cost** | By endorsement |
| **DP-3** | **Open peril** | Named (broad) | **Replacement cost** | By endorsement |

## What a dwelling policy does not include

**No liability.** Personal liability and medical payments are added by
endorsement — which is precisely what a landlord needs, since a tenant
injured on the property will look to the owner.

**No theft coverage as standard.** Available by endorsement on DP-2 and DP-3;
not on DP-1.

**No automatic additional coverages of the homeowners kind.** The lists of
debris removal, trees and shrubs, credit card coverage and so on are thinner
or absent.

## Endorsements a landlord will want

- **Personal liability** and **medical payments**.
- **Theft**, where the dwelling is furnished.
- **Vandalism and malicious mischief** — often excluded once a dwelling has
  been **vacant beyond 60 days**, which is the vacancy trap below.
- **Broad theft** or **building items** coverage.
- **Rental income**, beyond the included fair rental value.
- **Automatic increase in insurance**, to keep pace with construction costs.

## Vacancy and unoccupancy

The two words are not synonyms, and the exam separates them.

- **Unoccupied** — nobody is living there, but the contents remain. A family
  on a three-month trip.
- **Vacant** — **both the people and the contents are gone.** An empty house
  between tenants.

**Vacancy is the one that restricts coverage.** After a dwelling has been
vacant beyond a stated period — commonly **60 consecutive days** — several
perils are typically suspended, including **vandalism and malicious mischief,
glass breakage, theft, sprinkler leakage** and **water damage**, and some
forms reduce payment on any remaining covered loss.

The underwriting logic is straightforward: an empty building is a magnet for
vandalism and a slow burn nobody notices. The insured's fix is to tell the
insurer and buy a **vacancy permit**.

## How this is examined

**Which form for a rental house**, and that liability must be added.

**DP-1's actual cash value settlement**, contrasted with DP-2 and DP-3's
replacement cost.

**DP-3's open peril dwelling / named peril contents split.**

**Theft is not standard** on any dwelling form.

**Vacancy versus unoccupancy**, and the 60-day suspension of vandalism and
related perils.

**Coverage D and E as separate coverages** here, combined in homeowners.

## Check yourself

1. A landlord owns a rented house and wants building coverage plus protection
   against a tenant's injury claim. What policy and what addition?
2. Under a DP-1, a covered fire destroys a 30-year-old roof. How is the loss
   settled?
3. Which dwelling form matches the HO-3's peril structure?
4. A house stands empty with all furniture removed for 75 days. Vandals break
   in and damage it. Likely outcome?
5. Is theft included in a standard DP-2?

## Answers

1. A **dwelling policy** with a **personal liability** (and medical payments)
   endorsement.
2. **Actual cash value** — replacement cost less depreciation. DP-1 offers no
   replacement cost option.
3. **DP-3** — open peril on the dwelling, named peril on contents.
4. **No coverage.** The dwelling is **vacant** (people and contents gone)
   beyond 60 days, and vandalism is among the perils suspended.
5. **No.** Theft is added by endorsement on DP-2 and DP-3, and is not
   available on DP-1.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'dda2d47b-e8ee-5b9b-bffb-df02bb0b8812', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Commercial Property and the Package Policy',
       'commercial-property-and-the-package-policy', 'How a commercial package is assembled, the three causes of loss forms, and the income coverages that pay when the building is standing but the business is not.', 3,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', c.id, $lesson$# Building a commercial policy out of parts

Personal lines sells finished packages. Commercial lines sells components,
and the producer assembles them.

## The Commercial Package Policy

**A CPP is two or more commercial coverage parts issued under one policy.**
Its architecture:

1. **Common policy declarations** — insured, term, premium, coverage parts.
2. **Common policy conditions** — cancellation, changes, inspections,
   examination of books, transfer of rights. These apply to every part.
3. **Two or more coverage parts**, each with its own declarations, forms and
   conditions.

The available parts include **commercial property, general liability,
commercial auto, crime, inland marine, boiler and machinery (equipment
breakdown)** and **farm**.

**A single coverage part is a monoline policy; two or more make a package.**
The package earns a discount and removes the gaps and overlaps that separate
policies produce.

**Workers' compensation is written separately**, not as a CPP part.

## The commercial property coverage part

Three things must be assembled:

1. **A coverage form** — what property is covered.
2. **A causes of loss form** — what perils.
3. **Conditions and any endorsements.**

### The building and personal property coverage form

The workhorse. It insures three categories, each separately scheduled on the
declarations:

**Building** — the structure, completed additions, fixtures (including
outdoor fixtures), permanently installed machinery and equipment, and
materials and supplies used to maintain it.

**Your business personal property** — the insured's own contents at the
described premises: furniture, stock, machinery, leased property the insured
is responsible for, and **the insured's use interest in improvements and
betterments** made to a leased building.

**Personal property of others** — property in the insured's care, custody or
control. **Payment goes to the owner**, not to the insured.

The **coinsurance** clause applies, usually at 80%, 90% or 100%, and the
calculation is the one from Module 1.

### Extensions and additional coverages

Typically included: **debris removal** (a percentage of the loss plus the
deductible, with an additional amount available); **preservation of
property**; **fire department service charge**; **pollutant clean-up and
removal**, capped annually; **newly acquired or constructed property** for a
limited period and amount; **personal effects**; **property off premises**;
**outdoor property**; and **valuable papers and records** at a limited
amount.

### Reporting forms and blanket insurance

**Specific insurance** names an amount for one item at one location.

**Blanket insurance** covers **two or more items, or two or more locations,
under a single limit**. The advantage is flexibility: a shifting inventory
across three warehouses is fully covered wherever it sits, rather than being
underinsured at one and over at another. Blanket cover normally requires a
**statement of values** and a high coinsurance percentage.

**Reporting forms** suit a fluctuating inventory: the insured reports values
periodically and the premium is adjusted. Under-reporting is penalised at
claim time in proportion to the shortfall.

**Agreed value** suspends coinsurance where the insurer has accepted a
statement of values.

## How the building is classified

Before any of the coverage choices, an underwriter classifies the building
itself, because construction drives the rate more than almost anything else.

**The class is decided by the materials of the structure itself — the frame,
walls, floors and roof.** Not by the building's location, not by its value,
and not by the roof alone. The question underneath every class is the same:
**how much of this building will burn, and how long will it stand while it
does?**

**Six classes, from most combustible to least:**

1. **Frame** — combustible walls and floors. Wood.
2. **Joisted masonry** — masonry walls, combustible floor and roof.
3. **Non-combustible** — metal walls and roof on a metal or concrete frame.
4. **Masonry non-combustible** — masonry walls with a non-combustible floor
   and roof.
5. **Modified fire resistive** — rated materials, roughly one hour.
6. **Fire resistive** — concrete or protected steel, roughly two hours.

**The order is the point.** Each step buys a lower fire rate, and the first two
are where most small commercial risks sit.

> **Not named on either Texas outline.** Included because a producer quoting
> commercial property is asked the construction class on every submission, and
> because it explains why two identical-looking buildings on the same street
> price differently.

## The three causes of loss forms

This is the most-tested part of commercial property.

**Basic** — a named peril list: fire, lightning, explosion, windstorm or
hail, smoke, aircraft or vehicles, riot or civil commotion, vandalism,
sprinkler leakage, sinkhole collapse, volcanic action.

**Broad** — everything in Basic **plus** falling objects; weight of snow, ice
or sleet; and water damage from the accidental discharge of a system. It also
adds **collapse** as an additional coverage.

**Special** — **open peril**: every cause of loss except those excluded. The
burden shifts to the insurer. Special also adds coverage for **theft**, which
Basic and Broad do not include.

> **"Special form" means open peril, not "extra".** A question describing a
> loss from an unusual, unexcluded cause is testing whether you know Special
> is the only one of the three that answers it.

An **earthquake** form and a **flood** form exist separately, because neither
is included in any of the three.

## Business income and extra expense

These are **indirect** or **consequential** loss coverages. Direct damage
coverage rebuilds the building; these pay for the trading that could not
happen while it was being rebuilt.

**Business income** (formerly business interruption) pays:

- **the net income the business would have earned**, plus
- **continuing normal operating expenses**, including payroll where covered.

Three conditions frame it: there must be **direct physical loss** to covered
property, **by a covered cause of loss**, at the **described premises**,
causing a **necessary suspension** of operations.

The **period of restoration** begins **72 hours after the physical loss**
(where a waiting period applies) and ends when the property **should** have
been repaired with reasonable speed — not when it actually was. An insured
who takes eight months over a four-month rebuild is paid for four.

**Extra expense** pays the additional costs of **continuing** operations —
renting temporary premises, hiring equipment, expedited shipping. A business
that cannot afford to stop, such as a dairy or a newspaper, buys extra
expense rather than business income; many buy both on a combined form.

Related: **contingent business income** covers loss caused by damage to
**somebody else's** property — a sole supplier or a dominant customer.
**Civil authority** coverage pays where access to the premises is prohibited
by an authority because of damage to nearby property.

## Equipment breakdown

Formerly boiler and machinery. **It covers the sudden and accidental
breakdown of pressure, mechanical and electrical equipment** — and the
resulting damage.

It matters because **mechanical breakdown and electrical arcing are excluded
from every standard property form**, so without this coverage a burst boiler
or a failed transformer is uninsured. It typically covers the damaged
equipment, other property damaged by the breakdown, spoilage, expediting
expenses and business income.

**Inspection is part of the product.** The insurer's engineers inspect
boilers and pressure vessels, often satisfying the jurisdiction's statutory
inspection requirement, and the loss-prevention value is a substantial part of
what the premium buys.

## Builders risk

**Covers a structure under construction**, against loss during the build.

- The limit should equal the **completed value** of the structure.
- **Materials, supplies and equipment** intended to become part of the
  building are covered on site, and often in transit and at temporary
  storage.
- Insurable interest may belong to the **owner, the contractor, or both**,
  and the policy is usually written to name all interested parties.
- **Coverage ends** when the building is accepted, occupied for its intended
  purpose, or the policy expires — whichever comes first. At that point a
  standard property policy takes over.

## Cyber first-party coverage

**First-party cyber coverage pays the insured's own losses from a cyber
event**, as distinct from cyber *liability*, which pays what the insured owes
others.

What it typically covers: **data restoration** and system repair; **business
interruption** from a network outage; **cyber extortion** and ransomware
payments; **breach response costs** — forensics, notification of affected
individuals, credit monitoring, public relations; and **funds transfer
fraud**, where an employee is deceived into sending money.

It exists because standard property forms were written around physical damage
to tangible property, and **electronic data is generally not "tangible
property"** under them. Many forms now exclude cyber events explicitly, so the
coverage is bought deliberately or not at all.

## How this is examined

**Basic versus Broad versus Special**, and specifically that **only Special is
open peril** and **only Special includes theft**.

**Blanket versus specific insurance.**

**Business income versus extra expense** — replacing lost earnings versus
funding continued operation.

**The period of restoration ends when repairs *should* have been completed.**

**Equipment breakdown fills the mechanical breakdown exclusion.**

**Builders risk is written at completed value** and ends at occupancy.

## Check yourself

1. A commercial policy carries the Broad causes of loss form. Stock is stolen
   overnight. Covered?
2. An insured stores inventory across four warehouses, with amounts shifting
   weekly. Blanket or specific?
3. A fire closes a restaurant for five months, though competent repairs would
   have taken three. Business income is $40,000 a month. What is paid,
   broadly?
4. A transformer fails and burns out, damaging nearby equipment. Which
   coverage responds, and why not the property form?
5. A builders risk policy is written for $2m on a building whose completed
   value is $2m. Construction finishes and the owner moves in. What happens to
   the coverage?
6. A ransomware attack encrypts a firm's records and halts trading for a
   week. Which coverage responds?

## Answers

1. **No.** Theft is covered only under the **Special** form.
2. **Blanket**, so the single limit follows the inventory wherever it sits.
3. Roughly **three months** — about **$120,000**. The period of restoration
   ends when repairs **should** have been completed with reasonable speed.
4. **Equipment breakdown.** The standard property forms exclude mechanical
   breakdown and electrical arcing.
5. **It ends** on occupancy for the intended purpose; a standard commercial
   property policy must take over.
6. **First-party cyber coverage** — data restoration, cyber extortion and
   network business interruption. Electronic data is generally not tangible
   property under a standard form.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
