-- Texas Exam Prep — content seed, chunk 12 of 27
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Inland Marine',
       'inland-marine', 'Coverage for property that moves, property that is unusually valuable, and property no standard form handles well.', 4,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', c.id, $lesson$# Insurance for things that will not stay still

The name is historical and misleading. **Inland marine has almost nothing to
do with water.**

## Where the name comes from

Marine insurance is the oldest form of insurance, covering cargo at sea. As
goods moved inland by rail and road, marine underwriters followed the cargo
off the ship — insuring it over land as well. That extension became **inland**
marine, and over time it absorbed a much wider category: **property that
moves, property that is held by somebody other than its owner, and property
that a standard fire policy cannot value properly.**

**Ocean marine** remains separate, covering hull, cargo, freight and
protection and indemnity on the water.

## What qualifies

The distinguishing feature of an inland marine risk is one of:

- **The property moves** — goods in transit, a contractor's tools, a
  salesman's samples.
- **The property is portable and high value** — jewellery, cameras, musical
  instruments, fine art.
- **The property is instrumental to transport or communication** — bridges,
  tunnels, pipelines, radio towers. These do not move at all, and are insured
  here because they were historically classed as "instrumentalities of
  transportation."
- **The property is in somebody else's care** — a bailee holding customers'
  goods.

## Why anybody buys it

Four advantages over a standard property form:

- **Coverage is usually open peril** rather than named peril.
- **Coverage follows the property anywhere**, rather than attaching to
  described premises.
- **Valuation can be agreed in advance**, which matters enormously for a
  painting or an antique whose actual cash value would be argued about for
  months.
- **There is normally no coinsurance clause** on scheduled items.

**"Floater"** is the common name, because the coverage floats with the
property.

## Personal inland marine

### The personal articles floater

**Schedules high-value personal items individually**, each with a stated
value. The standard categories:

- jewellery
- furs
- cameras and photographic equipment
- musical instruments
- silverware
- golfer's equipment
- fine arts
- stamp and coin collections

Written as a **scheduled personal property** endorsement to a homeowners
policy, or as a stand-alone floater.

Why it is bought: the homeowners policy has **special limits** on exactly
these categories, most of them applying **to theft**. Scheduling removes the
sub-limit, broadens the perils to open peril, usually **removes the
deductible**, and pins the value in advance.

Two details that get tested:

- **Fine arts are normally written on a valued basis**, and typically carry a
  **breakage exclusion** unless it is bought back.
- **Newly acquired property** of a scheduled class is usually covered
  automatically for a limited period — commonly 30 days — provided the
  insurer is notified and premium paid.

### The personal property floater

Covers **all** the insured's personal property on an open peril, worldwide
basis, rather than a schedule of named items. Less common, and expensive.

## Commercial inland marine

### Nationwide marine definition

Regulators publish a **nationwide marine definition** setting out what may be
written as inland marine. It exists to stop insurers writing ordinary fire
business on inland marine forms to escape rate regulation. **Controlled**
lines are filed classes; **uncontrolled** lines may be written on
individually negotiated terms.

### The common commercial floaters

**Contractor's equipment floater** — mobile tools, machinery and equipment,
on site and in transit.

**Installation floater** — materials and equipment from the time they leave
the supplier until installed and accepted. The contractor's counterpart to
builders risk.

**Motor truck cargo** — the carrier's liability for goods it is hauling.

**Transportation / trip transit** — goods in transit generally, or one
specific shipment.

**Bailee's customers** — a dry cleaner, a repair shop, a warehouse. **Covers
the customers' property in the insured's care, and typically pays whether or
not the bailee was negligent**, because arguing about fault with a customer
whose suit you burned is bad business.

**Accounts receivable** — the sums the insured cannot collect because the
records were destroyed, plus the cost of reconstructing them and the extra
collection expense.

**Valuable papers and records** — the cost of reconstructing documents,
manuscripts and records. It pays for **reconstruction**, not for the
information's abstract worth.

**Electronic data processing** — computer hardware, software and data, on an
open peril basis, typically including **mechanical breakdown and electrical
disturbance**, which standard property forms exclude.

**Signs, jewellers block, furriers block, physicians and surgeons
equipment**, and **theatrical property** are further named classes.

**Instrumentalities of transportation and communication** — bridges, tunnels,
pipelines, power transmission lines, radio and television towers.

### Bailee terminology

- A **bailee** holds another's property. A **bailor** owns it.
- A **bailee's customers form** covers the customers' goods regardless of
  fault.
- **Legal liability** forms cover only what the bailee is legally responsible
  for — cheaper, and much less useful when the customer is angry.

## How this is examined

**"Which of these is an inland marine risk?"** — look for movement,
portability with high value, bailment, or an instrumentality of
transportation.

**Why schedule jewellery?** — to remove the homeowners special limit, broaden
to open peril, agree the value and drop the deductible.

**Bailee's customers pays regardless of negligence.**

**Accounts receivable and valuable papers pay for reconstruction**, not for
the debt or the information as an asset.

**A bridge is inland marine**, which feels wrong until you know the history.

## Check yourself

1. A photographer owns $30,000 of camera equipment used at client sites. What
   form, and why not the homeowners policy?
2. A dry cleaner's premises burn, destroying customers' garments. The cleaner
   was not negligent. Which form pays the customers?
3. Why does a floater usually have no coinsurance clause?
4. A contractor's excavator is damaged while being towed between sites. Which
   floater?
5. A fire destroys a firm's ledgers and it cannot collect $200,000 of debts.
   Which coverage, and what does it pay?

## Answers

1. A **personal articles floater** or a commercial camera floater. The
   homeowners policy limits cameras, covers them on a named peril basis away
   from home, and would settle on actual cash value.
2. A **bailee's customers form**, which pays regardless of the bailee's
   negligence.
3. Because scheduled items carry **agreed or stated values** — the insurer has
   already accepted the value, so there is nothing for a coinsurance clause to
   police.
4. A **contractor's equipment floater**.
5. **Accounts receivable** coverage — the uncollectible sums, the cost of
   reconstructing the records, and the extra collection expense.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'The National Flood Insurance Program',
       'the-national-flood-insurance-program', 'Why flood is excluded everywhere else, and how the federal programme fills the gap.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', c.id, $lesson$# The peril the private market would not write

Flood is excluded from homeowners, dwelling and commercial property forms
alike. The exclusion is not arbitrary, and understanding why explains
everything else about the programme.

## Why flood is uninsurable privately

Flood fails the tests of an insurable risk from Module 1:

- **The losses are not independent.** A flood does not damage one house; it
  damages every house on the flood plain at once. The law of large numbers
  needs many unrelated exposures, and a flood plain is one exposure with many
  addresses.
- **Adverse selection is extreme.** Only people who expect to flood buy flood
  insurance, so the pool consists almost entirely of bad risks.
- **The loss is close to predictable** for the highest-risk properties — not
  a risk so much as a schedule.

So in **1968 Congress created the National Flood Insurance Program**,
administered by **FEMA**. The federal government takes the risk the private
market would not.

## How a community participates

**The NFIP is a bargain between the federal government and the community, not
just with the individual.**

A community must **adopt and enforce flood plain management ordinances** —
building elevation requirements, construction standards, development
restrictions — to reduce future flood losses. In exchange, **federally backed
flood insurance becomes available to property owners in that community**.

**No participating community, no NFIP policy.** An owner in a non-participating
community must find private coverage or go without.

Two phases:

- **The emergency programme** — an interim phase with **limited amounts** of
  coverage available while flood mapping is completed.
- **The regular programme** — full limits, once the community has a flood
  insurance rate map and has adopted the required ordinances.

## The waiting period

**There is normally a 30-day waiting period** between application and the
policy taking effect. It is the programme's defence against somebody buying
cover as the river rises.

The exceptions are worth knowing:

- **No waiting period where flood insurance is required by a lender** in
  connection with making, increasing, extending or renewing a loan.
- **A one-day wait** where coverage is bought following a change in the flood
  map.
- A shortened wait for property **affected by wildfire on federal land**.

## What a flood is

The programme's definition is specific, and questions are built on it. A
flood is a **general and temporary condition of partial or complete
inundation of two or more acres of normally dry land, or of two or more
properties**, from:

- overflow of inland or tidal waters,
- unusual and rapid accumulation or runoff of surface water,
- mudflow, or
- collapse of land along a body of water from erosion or an unusually severe
  storm.

Two consequences:

- **Water entering one building alone is generally not a flood** — a burst
  pipe, a backed-up sewer, a leaking roof. Two acres or two properties is the
  threshold.
- **Mudflow counts; landslide generally does not.** Mudflow is liquid mud
  flowing; a landslide is earth movement, excluded.

## What is covered

Two separate coverages, bought separately:

**Building property** — the structure and its foundation, electrical and
plumbing, furnaces and water heaters, built-in appliances, permanently
installed carpet, and detached garages (within a portion of the limit).

**Personal property (contents)** — furniture, clothing, portable appliances,
washers and dryers, and a limited amount for valuables.

**Contents are not automatically included.** An owner who buys building
coverage only has no coverage for anything inside. That is a favourite
question.

### Limits

Under the **regular programme**, the maximum amounts available are:

| | Building | Contents |
| --- | --- | --- |
| **Residential** | **$250,000** | **$100,000** |
| **Non-residential / commercial** | **$500,000** | **$500,000** |

These are **programme maximums**, not appraised values. Anybody needing more
buys **excess flood** from the private market.

### Loss settlement

- **Replacement cost** is available on a **single-family dwelling that is the
  insured's principal residence**, insured to at least 80% of replacement
  cost.
- **Everything else is actual cash value** — contents always, and buildings
  that are secondary homes, rentals or commercial.

## What is not covered

- **Contents in a basement**, beyond a very short list of building items.
  Finished basements are largely uninsurable under the programme.
- **Additional living expense and loss of use** — the NFIP pays for the
  property, not for the disruption.
- **Currency, precious metals and valuable papers.**
- **Property outside the building** — landscaping, decks, patios, fences,
  septic systems, swimming pools.
- **Vehicles**, which belong on an auto policy's other-than-collision
  coverage.
- **Business interruption.**

## Zones, maps and requirements

FEMA publishes a **Flood Insurance Rate Map** for each participating
community, dividing it into **flood zones**.

- **Zones A and V** are **Special Flood Hazard Areas** — the 100-year flood
  plain, meaning a 1% annual chance of flooding. **V zones are coastal**, with
  additional wave action.
- **Zones B, C and X** are moderate or minimal risk, where coverage is
  cheaper and often bought voluntarily.

**Mandatory purchase:** a building in a Special Flood Hazard Area with a
**federally backed or federally regulated mortgage** must carry flood
insurance. This is the single largest driver of NFIP sales.

**Write Your Own.** Private insurers issue and service NFIP policies under
their own names, with the **federal government carrying the risk**. The
producer sells what looks like a private policy; the terms, limits and rates
are the programme's.

## How this is examined

**The 30-day waiting period** and its exceptions.

**The two-acre / two-property definition** of a flood.

**Contents must be bought separately.**

**The $250,000 / $100,000 residential limits.**

**Replacement cost applies only to a principal residence**; everything else is
ACV.

**Community participation is a precondition.**

**Basements, landscaping and living expense are not covered.**

## Check yourself

1. A homeowner buys an NFIP policy on 1 May. The river floods on 20 May. Is
   there coverage?
2. A burst water main floods only the insured's basement. Is this a "flood"
   under the programme?
3. An owner buys $250,000 of building coverage. A flood destroys $60,000 of
   furniture. What is paid?
4. A rental house owned as an investment suffers flood damage to a 15-year-old
   roof. Replacement cost or actual cash value?
5. A community declines to adopt flood plain management ordinances. Can its
   residents buy NFIP coverage?
6. What is the maximum building coverage on a commercial property?

## Answers

1. **No** — the 30-day waiting period has not run, and no exception applies.
2. **No.** A flood requires inundation of **two or more acres or two or more
   properties**; water in one building from a burst main is not one.
3. **Nothing.** Contents coverage must be purchased separately.
4. **Actual cash value.** Replacement cost is limited to a single-family
   dwelling that is the insured's **principal residence**.
5. **No.** Community participation is a precondition.
6. **$500,000**, with a further $500,000 available for contents.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
