-- Texas Exam Prep — content seed, chunk 13 of 27
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Other Property Policies',
       'other-property-policies', 'Earthquake, mobile homes, watercraft, farmowners and windstorm — five smaller forms the blueprint names explicitly.', 6,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', c.id, $lesson$# Five risks the standard forms send elsewhere

The blueprint lists these by name, so they are examined by name. Each exists
because a standard homeowners or commercial form either excludes the peril or
cannot handle the property.

## Earthquake

**Earth movement is excluded from every standard property form**, for the same
reason as flood: the losses are correlated. One earthquake damages every
building in a region simultaneously.

Coverage is bought back by **endorsement** to a homeowners or commercial
policy, or written as a **separate policy**.

What to know:

- **The exclusion is broader than "earthquake".** Earth movement includes
  **landslide, mudslide, subsidence, sinkhole collapse and earth sinking,
  rising or shifting**. Buying earthquake coverage does not necessarily buy
  all of these back.
- **Fire following an earthquake is covered by the standard policy.** The
  earth movement exclusion is generally written so that **ensuing fire** is
  not excluded. This is a long-standing rule and a reliable exam point.
- **The deductible is a percentage**, not a flat sum — commonly **2% to 20%
  of the coverage limit**, and it is applied to the limit rather than to the
  loss. On a $400,000 dwelling, a 10% deductible is $40,000 before anything is
  paid.
- **Multiple shocks within a stated period** — commonly 72 hours — count as
  **one occurrence**, so one deductible applies rather than several.

## Mobile homes

A mobile or manufactured home cannot be written on a standard homeowners
policy: it is built to different standards, depreciates like a vehicle rather
than appreciating like a house, and can be moved.

**A mobile homeowners policy is a package**, structured like a homeowners
policy with property and liability sections, but with changes:

- **Loss settlement is normally actual cash value**, reflecting that the unit
  depreciates. Replacement cost may be available by endorsement on newer
  units.
- **Transportation and permission to move** must be arranged. Coverage while
  the home is being moved is typically added by endorsement, often with a
  limited amount and a requirement that the insurer be notified beforehand.
- **Eligibility** usually requires the unit to be of a minimum size, designed
  for year-round living, and at a fixed location.
- **Skirting, awnings, carports and attached structures** may need to be
  listed to be covered.

## Watercraft

Homeowners policies cover **small, low-powered boats** and very little else.
The typical arrangement covers a boat only up to a modest length and
horsepower, on a narrow peril basis, with liability excluded for larger or
faster craft.

Anything beyond that needs a **boatowners or yacht policy**:

- **A boatowners policy** is a package for smaller pleasure craft, covering
  the hull, motor, trailer and equipment, plus liability and medical payments.
- **A yacht policy** covers larger vessels and is structured on ocean marine
  principles: **hull** coverage on the vessel, **protection and indemnity**
  for liability, plus medical payments and coverage for the boat's trailer
  and equipment.

Points that are examined:

- **Navigational limits.** The policy specifies the waters in which the
  vessel is covered, and often a **lay-up period** during which it must be out
  of the water — coverage is reduced or restricted outside those terms.
- **Protection and indemnity is the marine world's liability coverage**, and
  is broader than a general liability form in respect of crew and other
  maritime exposures.
- **Ocean marine perils** — the traditional list includes perils of the sea,
  fire, jettison, piracy and barratry (wrongful acts by the master or crew).

## Farmowners

**A farmowners policy is a package covering both the farm residence and the
farming operation** — the agricultural equivalent of a homeowners policy, and
the reason farms are ineligible for a homeowners policy.

It combines, in one contract:

- **The dwelling and its contents**, on much the same basis as a homeowners
  policy.
- **Farm structures** — barns, silos, outbuildings, fences, corrals.
- **Farm personal property** — machinery, equipment, tools, harvested crops,
  feed, seed, fertiliser, and **livestock**.
- **Farm liability**, which is broader than personal liability because the
  farm is a business. It covers the farming operation, and typically **farm
  employees**, whose injuries would otherwise fall outside a personal policy.

Specific features:

- **Livestock coverage** is usually written on a **named peril** basis and
  frequently includes perils peculiar to the exposure — **electrocution,
  attack by dogs or wild animals, accidental shooting, drowning** and **loading
  and unloading**.
- **Scheduled versus blanket** treatment of farm personal property works as it
  does in commercial property: blanket for a shifting inventory of feed and
  grain, scheduled for named machines.
- **Crop insurance is separate**, largely federal, and is not part of a
  farmowners policy.
- **Mobile agricultural equipment in transit** may need inland marine.

## Windstorm

Wind is a **covered peril** on standard property forms in most of the country.
In coastal areas it is frequently **excluded or heavily deductible**, because
the exposure is concentrated: one hurricane damages an entire coastline.

Where the private market withdraws, coverage comes from a **residual market**
— a state-created insurer of last resort. Two mechanisms appear:

- **A windstorm pool or association**, writing wind and hail coverage in a
  designated coastal area.
- **A FAIR Plan** — Fair Access to Insurance Requirements — writing basic
  property coverage for those unable to obtain it in the voluntary market,
  usually because of location or property condition rather than the owner's
  conduct.

Both are funded by **compulsory membership of the insurers writing in the
state**, which is why they are described as the market insuring itself.

Recurring features:

- **A separate, percentage windstorm or hurricane deductible**, applied to the
  coverage limit.
- **A named-storm trigger**, where the percentage deductible applies only to
  storms the weather service has named.
- **Insurance-to-value and building-code requirements** as conditions of
  eligibility.
- **A waiting period** and a suspension of new business once a storm is
  approaching.

> **Texas is one of the states where this matters most.** The Texas Windstorm
> Insurance Association and the Texas FAIR Plan Association are creatures of
> the Texas Insurance Code, with their own eligibility rules, limits,
> deductibles and claim deadlines. Those specifics belong to the Texas
> statutes module and are examined there. What belongs here is the general
> shape: wind excluded on the coast, a residual market filling the gap, funded
> by compulsory membership.

## How this is examined

**Fire following an earthquake is covered** by the standard policy.

**Earthquake deductibles are a percentage of the limit**, and multiple shocks
in 72 hours are one occurrence.

**Mobile homes settle at actual cash value.**

**A farm is ineligible for a homeowners policy**, and why.

**Livestock perils** — electrocution, attack by animals, accidental shooting,
drowning.

**Residual markets** exist because of correlated catastrophe exposure, and are
funded by the insurers writing in the state.

## Check yourself

1. An earthquake cracks a gas line and the resulting fire destroys the house.
   What is covered under a standard homeowners policy without an earthquake
   endorsement?
2. A $500,000 dwelling carries earthquake coverage with a 10% deductible. A
   quake causes $70,000 of damage. What is paid?
3. Why is a mobile home not written on a homeowners policy?
4. A farmer keeps a herd of cattle, farms 400 acres and lives in a house on
   the property. What policy?
5. Cattle are killed by lightning. Covered under a farmowners policy?
6. Why is windstorm excluded on the coast when it is covered inland?

## Answers

1. **The fire damage.** Ensuing fire is not excluded by the earth movement
   exclusion. The shake damage itself is not covered.
2. **$20,000.** The deductible is 10% of the **limit** — $50,000 — not of the
   loss.
3. It is built to different standards, depreciates rather than appreciates,
   and can be moved. A mobile homeowners policy settles on **actual cash
   value** and addresses transportation.
4. A **farmowners** policy — a package covering the residence and the farming
   operation. A farm is ineligible for homeowners.
5. **Yes.** Lightning is a standard peril and electrocution is among the
   perils livestock coverage typically names.
6. Because the exposure is **correlated** — a single hurricane damages an
   entire coastline at once, which defeats the law of large numbers. A
   residual market fills the gap.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Commercial General Liability',
       'commercial-general-liability', 'Three coverages, four exposures, six limits — the form most commercial liability questions are built on.', 1,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', c.id, $lesson$# The business's liability policy

The CGL covers a business's liability to **third parties** — customers,
visitors, passers-by, the users of its products. Not its employees (workers'
compensation), not its vehicles (commercial auto), not its professional
advice (professional liability).

## The four exposures

Traditionally grouped as **premises and operations**, **products and completed
operations**, **contractual**, and **personal and advertising injury**. The
blueprint names the first two explicitly.

**Premises** — somebody is injured on the insured's property. A customer
slips in a supermarket aisle.

**Operations** — somebody is injured by the insured's work **while it is in
progress**, whether at the insured's premises or elsewhere. A plumber floods
a client's kitchen mid-job.

**Products** — injury or damage caused by a product the insured made or sold,
**after it has left the insured's possession**.

**Completed operations** — injury or damage arising from the insured's work
**after it is finished** and handed over. A deck collapses two years after the
builder left.

**Products and completed operations are grouped together** because they share
a characteristic: the loss happens when the insured is no longer there, often
long afterwards. They also share **their own separate aggregate limit**.

The dividing line is tested directly: **work in progress is operations;
work handed over is completed operations.**

## The three coverages

### Coverage A — Bodily Injury and Property Damage Liability

The core. Pays sums the insured becomes **legally obligated to pay as
damages** because of bodily injury or property damage caused by an
**occurrence** in the coverage territory.

**An occurrence is an accident, including continuous or repeated exposure to
substantially the same general harmful conditions.** The word does the work
of excluding the deliberate: intentional injury is not an occurrence.

**Bodily injury** means bodily injury, sickness or disease, including death.
**Property damage** means physical injury to tangible property, including loss
of use, **and** loss of use of tangible property that is not physically
injured.

#### Occurrence versus claims-made

**An occurrence form** responds to injury or damage **taking place during the
policy period**, whenever the claim arrives.

**A claims-made form** responds to claims **first made during the policy
period**, and adds two mechanisms:

- **The retroactive date.** Injury or damage before it is not covered, no
  matter when claimed. A retroactive date that moves forward on renewal
  quietly destroys years of coverage — the thing to watch for.
- **Extended reporting periods.** A **basic** tail is automatic and short; a
  **supplemental** tail is bought, usually unlimited in time, and must be
  purchased within a short window after the policy ends.

Claims-made exists for long-tail exposures — where injury may not appear for
decades — because an insurer cannot price a promise whose claims will arrive
forty years later.

### Coverage B — Personal and Advertising Injury Liability

Covers injury arising from a list of **offences**, not from an accident. The
list:

- **false arrest, detention or imprisonment**
- **malicious prosecution**
- **wrongful eviction**, wrongful entry, or invasion of the right of private
  occupancy
- **slander or libel** — oral or written publication disparaging a person or
  organisation, or their goods
- **violation of a person's right of privacy**
- **use of another's advertising idea**
- **infringement of copyright, trade dress or slogan** in the insured's
  advertisement

Two exam points: **these are offences, not occurrences**, so the trigger is
the committing of the offence; and **patent and trademark infringement are
generally not covered** — the list names copyright, trade dress and slogan.

### Coverage C — Medical Payments

Pays medical expenses for bodily injury on the insured's premises or arising
from operations, **regardless of fault**, provided the expenses are incurred
within a stated period — commonly **three years** — of the accident.

It exists to settle small injuries quickly and goodwill intact, before they
become liability claims. It **does not apply to the insured, employees, or
tenants**, and it does not apply where the injured person is covered by
workers' compensation.

## Supplementary payments

Paid **in addition to the limits**: defence costs, the cost of bonds to
release attachments, **premiums** on appeal bonds and bail bonds (commonly up
to $250), reasonable expenses at the insurer's request including lost earnings
(commonly up to $250 a day), court costs, and **post-judgment interest**.

## Who is an insured

The form defines it by the insured's structure:

- **Sole proprietor** — the individual and their spouse, for the conduct of
  the business.
- **Partnership or joint venture** — the partners and their spouses.
- **Limited liability company** — members and managers.
- **Corporation** — executive officers, directors and stockholders, acting
  within their duties.
- **Employees and volunteer workers**, for acts within the scope of their
  employment — **but not for bodily injury to a fellow employee**, and not for
  professional services.
- **Real estate managers** acting for the insured.
- **Newly acquired organisations**, automatically, for a limited period —
  commonly **90 days** or until the policy ends, whichever is first.

**The first named insured** has the distinct duties met in Module 2: it
receives notices, pays premium, may cancel, and handles the **premium audit**.

**Additional insureds** are added by endorsement, for liability arising out of
the named insured's work or premises.

## The six limits

The CGL's limit structure is examined more often than anything else in the
form.

| Limit | What it caps |
| --- | --- |
| **Each occurrence** | All damages from one occurrence, under A and C combined |
| **General aggregate** | Everything paid in the policy period **except** products-completed operations |
| **Products–completed operations aggregate** | Its own separate annual cap |
| **Personal and advertising injury** | Per person or organisation, under Coverage B |
| **Damage to premises rented to you** | Fire (and in later editions, certain other) damage to premises the insured rents |
| **Medical expense** | Per person, under Coverage C |

The points that get tested:

- **Products-completed operations has its own aggregate**, separate from the
  general aggregate. Exhausting one does not exhaust the other.
- **The aggregate is annual.** Once exhausted, the policy is finished for that
  period even though months remain — and the duty to defend ends with it.
- **Damage to premises rented to you** is the exception to the property damage
  exclusion for property in the insured's care: a tenant who burns the
  landlord's building has this, and nothing else.

## Key exclusions

- **Expected or intended injury.**
- **Contractual liability** — except for an **insured contract**, a defined
  list including leases, sidetrack agreements, easements, and the part of any
  contract assuming another's tort liability. This is a broad exception that
  effectively restores most commercial hold-harmless agreements.
- **Workers' compensation and employer's liability** — employees' injuries
  belong elsewhere.
- **Pollution**, with narrow exceptions.
- **Aircraft, auto and watercraft** — but **mobile equipment is covered**.
- **Damage to your product** and **damage to your work** — the policy covers
  the harm the product does, not the cost of the defective product itself.
  This is the **business risk** principle: replacing your own bad work is a
  cost of doing business, not an insurable accident.
- **Damage to property in your care, custody or control**, except the rented
  premises limit.
- **Recall of products** — the "sistership" exclusion.
- **Liquor liability**, for those in the business of serving alcohol.
- **Professional services.**

## Mobile equipment versus auto

**Mobile equipment** — bulldozers, farm machinery, forklifts, vehicles
maintained solely on the insured's premises, and vehicles whose purpose is to
carry permanently mounted equipment like drills or cranes — is **covered by
the CGL**.

**Autos** — vehicles subject to compulsory registration and used on public
roads — are **excluded** and belong on the commercial auto policy.

The line moves in one notable case: **self-propelled vehicles carrying
permanently attached equipment are mobile equipment, unless they are subject
to registration**, in which case they become autos.

## How this is examined

**Operations versus completed operations.**

**The two aggregates**, and that exhausting one does not exhaust the other.

**"Damage to your work" and "damage to your product"** — the product that
injures somebody is covered; the product itself is not.

**Coverage B's list of offences**, especially that patent and trademark are
absent.

**Medical payments pays without fault** and not to employees.

**Insured contract** as the exception to the contractual liability exclusion.

**Mobile equipment versus auto.**

## Check yourself

1. A contractor installs a faulty water heater. It leaks two years later,
   ruining a floor. Which exposure, and is the water heater itself covered?
2. A CGL has a $1m occurrence limit, $2m general aggregate and $2m
   products-completed operations aggregate. Premises claims have exhausted the
   general aggregate in July. A products claim arrives in September. Covered?
3. A visitor trips in the insured's lobby. The insured is plainly not
   negligent, but the visitor has a $3,000 hospital bill. Anything payable?
4. An employee is injured by a colleague's negligence. Does the CGL respond?
5. A restaurant's advertisement copies a competitor's slogan. Which coverage?
6. A tenant's negligence causes a fire that damages the landlord's building.
   Is that covered, given the care, custody or control exclusion?

## Answers

1. **Completed operations** — the work was finished and handed over. The
   **floor damage is covered**; the **water heater itself is not**, under the
   damage-to-your-product and damage-to-your-work exclusions.
2. **Yes.** Products-completed operations has its **own separate aggregate**,
   untouched by the premises claims.
3. **Yes** — Coverage C, medical payments, pays regardless of fault, for
   expenses incurred within the stated period.
4. **No.** Employee injuries are excluded; workers' compensation and
   employers' liability respond.
5. **Coverage B**, personal and advertising injury — infringement of slogan in
   an advertisement.
6. **Yes, up to the "damage to premises rented to you" limit**, which is the
   express exception to that exclusion.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
