-- Texas Exam Prep — content seed, chunk 15 of 27
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Workers'' Compensation and Employers'' Liability',
       'workers-compensation-and-employers-liability', 'The no-fault bargain, the three parts of the policy, and how the premium is actually calculated.', 4,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', c.id, $lesson$# A bargain struck a century ago

Before workers' compensation, an injured employee had to **sue the employer
and prove negligence** — and faced three defences that usually won:

- **Contributory negligence** — the worker's own carelessness contributed.
- **Assumption of risk** — the worker knew the job was dangerous and took it
  anyway.
- **The fellow servant rule** — the injury was caused by a co-worker, not the
  employer.

Injured workers rarely recovered, and when they did, employers faced ruinous
awards.

**Workers' compensation replaced that with a trade.** The employee gives up
the right to sue and the chance of a large damages award. The employer gives
up the three defences and accepts liability **without regard to fault**. The
employee gets certain, prompt, limited benefits; the employer gets
predictability.

## Exclusive remedy

**The benefits provided by the workers' compensation statute are the
employee's exclusive remedy against the employer for a work-related injury.**

This single sentence is the most examined fact in the topic. It is why the
CGL excludes employee injuries, why the employer cannot be sued for pain and
suffering, and why the arrangement works at all.

The exceptions where an employee may sue outside the system are narrow:
**intentional injury by the employer**, and in some states injury caused by
**gross negligence** or by the employer's failure to carry required coverage.

**Third parties are not protected.** An employee injured by a defective
machine still sues the manufacturer, and the compensation insurer subrogates
against it.

> **Texas is the notable exception in the United States.** It is the only
> state that does not compel most private employers to carry workers'
> compensation. An employer that opts out — a "non-subscriber" — **loses the
> three common law defences** and can be sued directly. That is Texas-specific
> and examined in the Texas statutes module; the blueprint explicitly notes
> that this general section does not deal with state law specifics.

## Who is covered

**An employee** — anybody the employer directs and controls as to the manner
of the work. The label on the relationship matters less than the control test.

**An independent contractor** is not an employee: they control how the work is
done, supply their own tools, and serve multiple clients. An employer using
uninsured subcontractors may nevertheless be treated as their statutory
employer.

Commonly excluded or optional, varying by state: **domestic servants, casual
labour, farm workers, sole proprietors, partners, and corporate officers**,
who may often elect in or out.

Separate **federal systems** cover workers the state acts do not:

- **The Federal Employers' Liability Act (FELA)** — railroad workers. Note
  that FELA is **not** a no-fault system; it preserves the right to sue but
  removes the common law defences.
- **The Longshore and Harbor Workers' Compensation Act** — maritime workers
  on navigable waters other than seamen.
- **The Jones Act** — seamen.
- **The Federal Employees' Compensation Act** — civilian federal employees.

## Compensability: arising out of and in the course of employment

An injury is compensable if it **arises out of** the employment (the work
caused it) **and occurs in the course of** the employment (during work, at the
workplace, doing work).

The recurring boundaries:

- **The commute is generally not covered** — the "going and coming" rule. But
  travel **on the employer's business** is.
- **A lunch break off premises** is usually outside; on premises, usually
  inside.
- **Horseplay** generally takes the injured instigator outside the system; an
  innocent bystander usually stays inside.
- **Occupational disease** is covered where it arises from conditions
  characteristic of the work — repetitive strain, hearing loss, exposure
  illnesses — even though there is no accident and the onset is gradual.

## The benefits

Set by statute, not by the policy. Four categories:

**Medical** — usually **unlimited**, with no deductible and no dollar cap.
This surprises candidates and is worth remembering.

**Disability income**, replacing lost wages at a percentage of the worker's
average weekly wage — commonly around **two-thirds** — subject to state
maximum and minimum amounts, and usually **after a short waiting period**,
which is often retroactive if the disability lasts beyond a set duration. Four
classes:

- **Temporary total** — cannot work at all, but will recover.
- **Temporary partial** — can work in a reduced capacity, will recover.
- **Permanent partial** — a lasting impairment; often paid on a **schedule**
  setting a number of weeks per body part.
- **Permanent total** — cannot return to any gainful employment.

**Rehabilitation** — medical and vocational, to return the worker to
employment.

**Death benefits** — burial expenses up to a stated amount, and income
benefits to surviving dependants.

## The policy's three parts

**Part One — Workers' Compensation.** The insurer pays **whatever the
statute requires**. There is **no dollar limit**, because the obligation is
the state's, not the policy's. The states listed in the declarations (Item
3.A) are where this applies.

**Part Two — Employers' Liability.** Covers the employer's liability for
work-related injury **that falls outside the compensation statute**. This is
where the limits live, commonly written as three: **bodily injury by accident
each accident / bodily injury by disease policy limit / bodily injury by
disease each employee.**

It answers exposures such as:

- **Third-party-over actions** — the injured employee sues a manufacturer,
  which then sues the employer for contribution.
- **Consequential bodily injury** to a family member.
- **Loss of consortium** claims by a spouse.
- **Dual capacity** — the employer is sued in a second role, such as the
  maker of the machine that caused the injury.

**Part Three — Other States Insurance.** Extends Part One to states listed in
Item 3.C where the insured **may** begin operations during the policy period.
A state named in **neither** 3.A nor 3.C has no coverage — and adding it after
an injury is too late. **Monopolistic states cannot be covered here at all**,
because in those states coverage must be bought from the state fund.

## Premium determination

Examined more often than candidates expect.

> **Premium = (payroll ÷ 100) × rate × experience modification factor**

- **Payroll** is per **$100** of remuneration, by **classification code**. A
  business with clerical and roofing staff pays very different rates on each.
- **The rate** reflects the hazard of the classification.
- **The experience modification factor** compares this employer's actual
  losses with those expected for its class and size. **Above 1.0 means worse
  than average and a higher premium; below 1.0 means better and a credit.**
  This is the mechanism that rewards safety.

Because payroll is not known in advance, the policy is written on an
**estimated** payroll and a **deposit premium** is paid at inception. At the
end of the period the insurer conducts a **premium audit** of the actual
payroll and issues an additional premium or a return. **The insured must
permit the audit and keep records** — a policy condition.

Larger employers may use **retrospective rating**, where the final premium
depends on the employer's own losses during the period, within a maximum and
minimum.

## How an employer obtains coverage

- **The voluntary market** — a standard insurer.
- **An assigned risk pool or state fund** — for employers the voluntary market
  will not write.
- **A monopolistic state fund** — in a handful of states, the only source, and
  employers' liability must then be bought separately by endorsement to the
  CGL.
- **Qualified self-insurance**, for employers with the financial capacity and
  the regulator's approval.

## How this is examined

**Exclusive remedy**, and the three defences the employer surrendered.

**Medical benefits are unlimited**; disability income is not.

**Part One has no limit; Part Two carries the limits.**

**Other States Insurance** — a state in neither 3.A nor 3.C is uncovered.

**The premium formula**, and what an experience modification above 1.0 means.

**Deposit premium and audit.**

**The going and coming rule.**

## Check yourself

1. An employee is injured by a co-worker's carelessness. Can the employer rely
   on the fellow servant rule?
2. An employee is hurt by a defective press. Who may be sued, and by whom?
3. Is there a dollar limit on medical benefits?
4. An employer with operations in Oklahoma has only Texas in Item 3.A and
   nothing in 3.C. An Oklahoma employee is injured. Covered?
5. An employer's experience modification factor is 1.25. What does that mean
   for the premium?
6. An employee slips in the car park on the way home from work. Compensable?

## Answers

1. **No.** The employer surrendered contributory negligence, assumption of
   risk and the fellow servant rule as part of the bargain, and pays without
   regard to fault.
2. The employee may sue **the press manufacturer** (a third party); the
   **employer may not be sued**, by exclusive remedy. The compensation insurer
   subrogates against the manufacturer.
3. **No.** Medical benefits are generally unlimited under the statute.
4. **No.** A state appearing in neither 3.A nor 3.C has no coverage, and it
   cannot be added retroactively.
5. It is **25% worse than expected** for its class, so the premium is
   increased by 25%.
6. **Usually yes** — the employer's own car park is generally treated as
   premises, so the going and coming rule does not bar it.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Crime',
       'crime', 'Five crimes the exam insists you distinguish, and the coverage that answers the one that costs most.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', c.id, $lesson$# Words that mean the same thing in conversation and different things here

Most of this topic is definitions. The exam tests them relentlessly, because
in ordinary speech burglary, robbery and theft are interchangeable and in
insurance they are not.

## The five definitions

**Theft** is the **broadest** term: the unlawful taking of property. Burglary
and robbery are both kinds of theft.

**Burglary** is **the taking of property from inside premises, by somebody who
unlawfully entered or left, with visible signs of forced entry or exit.**

Two elements: **forcible entry** and **visible marks**. No marks, no burglary.
A thief who walks through an unlocked door has not committed burglary for
insurance purposes, however obviously they have stolen something.

**Robbery** is **taking property from a person, by violence or the threat of
violence.**

The element is **a person put in fear**. Robbery requires a victim who is
present and threatened. A pickpocket is not committing robbery, because there
is no threat.

**Mysterious disappearance** is property that **vanishes with no explanation
and no evidence of how**. Not a crime so much as a category — property that
is simply gone.

The practical consequence: **an insured who cannot prove burglary or robbery
falls back on mysterious disappearance**, and many forms exclude or limit it
precisely because it cannot be investigated.

**Forgery and alteration** is the **signing of another's name without
authority**, or the altering of a financial instrument — cheques, drafts,
promissory notes.

### Holding them apart

| | Where | How | Proof needed |
| --- | --- | --- | --- |
| **Burglary** | Inside premises | **Forced entry or exit** | **Visible marks** |
| **Robbery** | From a **person** | **Force or threat of force** | A person put in fear |
| **Theft** | Anywhere | Any unlawful taking | Broadest |
| **Mysterious disappearance** | Anywhere | Unknown | None available |

One sentence that carries all four: **burglary breaks in, robbery threatens a
person, theft covers both and more, and mysterious disappearance is what is
left when you cannot say which.**

## Employee dishonesty

**The largest crime exposure most businesses have is not a stranger. It is an
employee.**

**Employee dishonesty coverage (fidelity)** covers **loss of money,
securities and other property caused by the dishonest acts of employees** —
theft, embezzlement, forgery.

What to know:

- **The employee must intend to cause the employer a loss and obtain a
  financial benefit.** Simple negligence, or a mistake, is not dishonesty.
- It is written on one of two bases: **per loss**, where the limit applies to
  each dishonest act or scheme regardless of how many employees were involved,
  or **per employee**, where it applies separately to each.
- **Discovery of a dishonest act by an employee ends coverage for that
  employee immediately**, since the risk is no longer fortuitous.
- **Coverage is generally excluded for loss proved only by an inventory
  computation or profit-and-loss comparison.** A shortage on the books is not
  by itself proof of theft — though such records may support a claim otherwise
  proved.

## Discovery and loss-sustained forms

The trigger question, and a favourite:

- **A loss-sustained form** covers losses **occurring during the policy
  period** and discovered during it or within a short period afterwards.
- **A discovery form** covers losses **discovered during the policy period**,
  whenever they occurred.

**The discovery form is broader**, because employee dishonesty is typically
found long after it began — the average embezzlement runs for years before
anybody notices.

## The crime coverage forms

Commercial crime is assembled from insuring agreements, bought individually:

- **Employee theft** (fidelity).
- **Forgery or alteration**.
- **Inside the premises — theft of money and securities**, covering theft,
  disappearance and destruction.
- **Inside the premises — robbery or safe burglary of other property.**
- **Outside the premises**, covering money, securities and property in the
  care of a **messenger**.
- **Computer fraud** and **funds transfer fraud**.
- **Money orders and counterfeit money.**

Two roles the forms define: a **custodian** is the insured, a partner, or an
employee with care and custody of property inside the premises; a
**messenger** is one of those people **outside** the premises. A **watchperson**
is retained specifically to guard the premises, and some coverages require one
to be on duty.

## What is excluded

- **Acts of the insured** — the owner cannot steal from himself and claim.
- **Loss proved only by inventory or profit-and-loss computation.**
- **Accounting or arithmetical errors.**
- **Trading losses** and **voluntary parting** — property handed over because
  the insured was tricked into it, which is why social engineering fraud
  became a separate insuring agreement.
- **War, nuclear hazard, governmental action.**
- **Vandalism** damage in some forms, and damage to the premises, unless
  specifically covered.

## Bonds versus crime insurance

Both address dishonesty, and they are different instruments — covered fully in
the bonds lesson. In short: **a fidelity bond guarantees the honesty of a
named person or position**, while **employee dishonesty insurance covers the
employer's loss** from employees generally.

## How this is examined

**Burglary requires visible marks of forced entry.** This is the single most
reliable crime question.

**Robbery requires a person threatened.**

**Discovery versus loss-sustained**, and which is broader.

**Employee dishonesty excludes loss proved only by inventory shortage.**

**Coverage for an employee ends on discovery of a dishonest act by them.**

## Check yourself

1. A thief enters through an unlocked window, steals a laptop and leaves no
   marks. Is this burglary?
2. A courier carrying the day's takings is threatened with a knife and hands
   over the bag. Which crime, and which insuring agreement?
3. A bookkeeper diverts $80,000 over four years. The scheme is discovered in
   year five, after the policy in force during the theft has expired. Which
   form responds?
4. An annual stocktake shows $30,000 of missing inventory and nothing else.
   Is that a covered employee dishonesty loss?
5. An employer discovers an employee stole $500 two years ago and keeps them
   on. The employee steals again. Covered?

## Answers

1. **No.** Burglary requires **visible signs of forced entry or exit**. It is
   theft, and may be a mysterious disappearance claim depending on the form.
2. **Robbery** — property taken from a person by threat of violence. The
   **outside the premises** insuring agreement, the courier being a
   **messenger**.
3. **A discovery form**, which covers losses **discovered** during the policy
   period whenever they occurred. A loss-sustained form would likely not
   respond.
4. **No.** Loss proved **only** by inventory computation is excluded.
5. **No.** Coverage for that employee ended on discovery of the first
   dishonest act.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
