-- Texas Exam Prep — content seed, chunk 15 of 28
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Personal Auto',
       'personal-auto', 'Four parts, several definitions of "your covered auto", and the uninsured motorist coverage that catches everybody.', 2,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', c.id, $lesson$# The most widely owned policy there is

A personal auto policy is a package of four separately purchased coverages,
each with its own limit and its own set of insureds.

## The four parts

| Part | Coverage |
| --- | --- |
| **A** | **Liability** — bodily injury and property damage to others |
| **B** | **Medical payments** |
| **C** | **Uninsured motorists** (and, where written, underinsured) |
| **D** | **Damage to your auto** — collision and other than collision |

## Part A — Liability

Pays damages the insured is legally responsible for, from an auto accident.
It includes **defence**, and **defence costs are in addition to the limit**.

### Split limits and combined single limit

**Split limits** are written as three numbers: **bodily injury per person /
bodily injury per accident / property damage per accident.** Under 100/300/50:

- **$100,000** is the most for any one injured person;
- **$300,000** is the most for all bodily injury in one accident;
- **$50,000** is the most for property damage in one accident.

A four-claimant accident with $90,000 of injury each: each claim is within the
$100,000 per-person limit, but the $360,000 total exceeds the $300,000
per-accident limit, so **$300,000** is paid.

**A combined single limit** is one figure covering bodily injury and property
damage in any proportion. A $300,000 CSL can pay $250,000 of injury and
$50,000 of damage, or any other split. It is more flexible and generally more
expensive.

### Who is an insured under Part A

- **The named insured and any family member**, for any auto — including cars
  they do not own.
- **Any person using "your covered auto"** with permission. This is
  **permissive use**, and it is why lending the car lends the insurance.
- **Any person or organisation legally responsible** for an insured's use of a
  covered auto — a passenger's employer, for example.

### Key exclusions

- **Intentional injury.**
- **Property owned by or in the insured's care, custody or control** — you
  cannot use your liability coverage to fix your own garage.
- **Vehicles with fewer than four wheels**, and vehicles used as a **public or
  livery conveyance** — the ride-hailing exclusion, now commonly bought back
  by endorsement.
- **Employees covered by workers' compensation.**
- **Using a vehicle without a reasonable belief of being entitled to.**
- **Vehicles available for regular use** that are not covered autos — the
  reason a company car you drive daily is not covered by your personal policy.
- **Business use of vehicles**, other than a private passenger auto, pickup or
  van.

## Part B — Medical payments

Pays **reasonable and necessary medical and funeral expenses**, for bodily
injury caused by an accident, **regardless of fault**, incurred within a
stated period — commonly **three years** — of the accident.

Who is covered:

- **The named insured and family members**, while occupying **any** auto, or
  as pedestrians struck by a motor vehicle.
- **Any other person occupying "your covered auto."**

It is a small limit, often $5,000 or $10,000 per person, and it is primary:
it pays quickly without waiting for a liability determination.

## Part C — Uninsured and underinsured motorists

The coverage the exam loves, because its logic runs backwards from the rest of
the policy.

**UM pays the insured what the *other* driver's liability policy would have
paid, had they had one.** The insured must be **legally entitled to recover**
— the other driver must be at fault. This is the crucial point: **UM is not
no-fault coverage.** If the insured caused the accident, UM pays nothing.

**Uninsured motorist** applies where the at-fault driver:

- has **no insurance**;
- is a **hit-and-run** driver who cannot be identified; or
- has insurance from an insurer that is **insolvent** or **denies coverage**.

**Underinsured motorist** applies where the at-fault driver **has insurance,
but not enough** to cover the loss. It pays the difference between the other
driver's limit and the insured's UIM limit.

Two further points:

- **UM bodily injury is standard; UM property damage is not** available in
  every state, and where it is, often carries a deductible.
- **Stacking** — combining the UM limits of several vehicles or policies — is
  permitted in some states and prohibited in others.

> Texas's rules on uninsured and underinsured motorists, and on personal
> injury protection, sit in Chapter 1952 of the Texas Insurance Code. The
> general mechanism is here; the Texas requirements, including which coverages
> must be offered and how they may be rejected, are examined in the Texas
> statutes module.

**Personal injury protection** is a broader first-party coverage found in
some states, paying medical expenses, lost wages and replacement services
regardless of fault — and, unlike UM, without requiring anybody to be at
fault.

## Part D — Damage to your auto

Physical damage to the vehicle itself, written with a deductible.

**Collision** — impact with another vehicle or object, or the vehicle
overturning. **Fault is irrelevant.** Hitting a wall is collision; so is
being hit.

**Other than collision** (comprehensive) — everything else: **fire, theft,
vandalism, glass breakage, falling objects, explosion, earthquake, windstorm,
hail, water, flood, riot, contact with a bird or animal, and missiles**.

The classic distinction: **hitting a deer is other than collision; swerving to
avoid a deer and hitting a tree is collision.**

**Specified (named) perils** is a cheaper third option, covering a named list
— fire, lightning, theft, windstorm, hail, explosion, earthquake, flood, riot,
and the like — rather than all non-collision causes.

Also in Part D:

- **Transportation expenses** — a modest daily amount for a rental car
  following a covered loss, subject to a maximum and, for theft, a waiting
  period.
- **Loss to non-owned autos** the insured is driving is covered to the same
  extent.
- **Excluded**: wear and tear, mechanical breakdown, road damage to tyres,
  freezing, electronic equipment not permanently installed, and custom
  furnishings in a pickup or van unless declared.

**Loss settlement is actual cash value** or the cost of repair, whichever is
less. **A total loss pays ACV, which is why a new car can be worth
substantially less than its loan** — the gap that GAP coverage fills.

## Types of auto

The blueprint names these explicitly, and they matter more in commercial auto:

- **Owned** — titled to the insured and listed on the policy.
- **Non-owned** — not owned by, hired by or borrowed by the insured, but used
  in the insured's business, typically an employee's own car.
- **Hired** — leased, rented or borrowed.
- **Temporary substitute** — used while a covered auto is out of service for
  breakdown, repair, servicing, loss or destruction. **Covered
  automatically.**
- **Newly acquired auto** — covered automatically, usually for **14 or 30
  days** depending on whether it is an addition or a replacement and on the
  coverage; the insured must notify the insurer within that window. An
  **additional** vehicle generally gets broader automatic coverage than a
  **replacement**, which inherits only the coverage the replaced vehicle had.
- **Trailers** owned by the insured are usually covered for liability.

## Duties after an accident

Beyond the general duties: **notify the police in a hit-and-run** (UM
requires it, usually within 24 hours), **submit to physical examination** and
to **examination under oath**, and **allow inspection of the vehicle before
repair**.

## How this is examined

**Split limit arithmetic** with several claimants.

**Collision versus other than collision** — the deer.

**UM requires the other driver to be at fault**, and covers hit-and-run and
insolvent insurers.

**UIM pays the difference**, not the whole loss again.

**Permissive use** — the borrowed car.

**Newly acquired auto** notification periods, and addition versus
replacement.

**Public or livery conveyance** exclusion for ride-hailing.

## Check yourself

1. Under 250/500/100, three people are injured with claims of $200,000,
   $200,000 and $150,000. What is paid for bodily injury?
2. The insured hits a deer. Collision or other than collision?
3. The insured is at fault in an accident and is badly injured. The other
   driver is uninsured. Does UM pay the insured's injuries?
4. An at-fault driver carries $30,000 of bodily injury coverage. The insured's
   damages are $90,000 and their UIM limit is $100,000. Roughly what does UIM
   pay?
5. A friend borrows the insured's car and causes an accident. Whose policy is
   primary?
6. The insured's car is totalled. It was bought last year for $38,000, is now
   worth $26,000, and the loan balance is $31,000. What does Part D pay?

## Answers

1. Each claim is within the $250,000 per-person limit, but they total
   $550,000 against the $500,000 per-accident limit. **$500,000** is paid.
2. **Other than collision.** Contact with an animal is a comprehensive loss.
3. **No.** UM requires the insured to be **legally entitled to recover** from
   the other driver — the other driver must be at fault.
4. **$60,000** — the difference between the at-fault driver's $30,000 and the
   insured's $90,000 of damages, within the $100,000 UIM limit.
5. **The car owner's.** Liability follows the car; the permissive user is an
   insured.
6. **$26,000** less the deductible — actual cash value. The **$5,000 gap** to
   the loan is the insured's, unless GAP coverage was bought.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Business Auto',
       'business-auto', 'The numbered symbols that decide what is covered, plus garagekeepers and drive other car.', 3,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', c.id, $lesson$# Same risks, different machinery

The business auto policy covers the same exposures as a personal auto policy —
liability, medical payments, uninsured motorists, physical damage — for a
business. What is different is **how it describes which vehicles are
covered**, and that mechanism is what gets examined.

## Covered auto designation symbols

Rather than listing vehicles, the declarations put a **number next to each
coverage**. The number says which class of autos that coverage applies to.

| Symbol | Meaning |
| --- | --- |
| **1** | **Any auto** — the broadest available |
| **2** | Owned autos only |
| **3** | Owned **private passenger** autos only |
| **4** | Owned autos **other than** private passenger |
| **5** | Owned autos subject to **no-fault** laws |
| **6** | Owned autos subject to **compulsory uninsured motorist** law |
| **7** | **Specifically described** autos |
| **8** | **Hired** autos only |
| **9** | **Non-owned** autos only |
| **19** | Mobile equipment subject to compulsory or financial responsibility law |

The consequences:

- **Symbol 1 is available only for liability.** It is the broadest, covering
  owned, hired and non-owned autos alike, including vehicles acquired after
  the policy began.
- **Physical damage cannot use symbol 1**, because an insurer will not insure
  the hull of a vehicle it has never seen. Physical damage uses **2, 3, 4, 7**
  or a combination.
- **A business that owns no vehicles but whose staff drive their own** needs
  **symbols 8 and 9** — hired and non-owned — with no owned-auto coverage at
  all.
- **Symbol 7 covers only what is listed**, so a newly purchased vehicle must
  be reported. Symbols 2, 3 and 4 pick up newly acquired autos automatically.

A question describing a fact pattern and asking "which symbol?" is really
asking whether the vehicle is owned, hired or non-owned.

## Hired and non-owned

**Hired autos** are leased, rented, hired or borrowed — but **not** vehicles
borrowed from employees. Coverage is usually **excess** over the owner's own
insurance, and the premium is based on **cost of hire**.

**Non-owned autos** are vehicles used in the business but not owned, hired or
borrowed by it — chiefly **employees' own cars** used on company errands. The
business's liability arises because the employee was acting in the scope of
employment. Coverage is **excess** over the employee's own policy, which
remains primary.

**Hired and non-owned liability is the coverage a business with no vehicles
still needs**, and the one it most often forgets to buy.

## Physical damage

The same three options as personal auto — **collision**, **other than
collision** (comprehensive), and **specified causes of loss** — plus:

- **Towing and labour** at the place of disablement.
- **Loss of use** and **rental reimbursement**, by endorsement.
- **Transportation expenses** following theft.

## Auto dealers and garagekeepers

A vehicle dealer or repair shop has an exposure nobody else does: **it holds
other people's cars.** Two coverages address it.

**Garage liability** (now within the auto dealers coverage form) covers the
dealer's liability from **garage operations** — the premises, the operations,
and the autos.

**Garagekeepers coverage** covers **damage to customers' autos in the
insured's care, custody or control**. This is the exposure the CGL and the
business auto policy both exclude, and it is examined regularly.

It is written on one of three bases:

- **Legal liability** — pays only when the insured is **legally liable** for
  the damage. Cheapest.
- **Direct primary** — pays for damage to the customer's auto **regardless of
  fault**, and pays first, before the customer's own insurance.
- **Direct excess** — pays regardless of fault, but **only after the
  customer's own insurance** is exhausted.

The distinction to hold: **legal liability requires negligence; the two direct
forms do not. Primary pays first; excess pays after the customer's policy.**

A dealer also needs **dealer's physical damage** ("false pretense" and similar
coverages) for its own inventory.

## Drive other car

**Drive Other Car** is an endorsement for an individual — typically an
executive with a company car and **no personal auto policy of their own.**

The problem it solves: the business auto policy covers them while driving the
company car, but not while driving a rented car on holiday or borrowing a
friend's vehicle. Their personal exposure is uninsured because they own no
personal policy.

**DOC extends the business auto policy's liability, medical payments,
uninsured motorists and physical damage to the named individual and their
spouse while using autos they do not own** — other than the company car
itself, which is already covered.

It is named-individual coverage, added by endorsement for each person.

## Individual named insured

A related endorsement broadens a business auto policy for an **individual**
named insured — a sole proprietor whose business and personal use are the same
vehicles — to give something close to personal auto coverage for family
members and non-owned vehicles.

## Mobile equipment

The same line as in the CGL. **Mobile equipment** — bulldozers, farm
machinery, forklifts, vehicles maintained solely on premises, vehicles whose
purpose is to carry permanently mounted equipment — is covered by the **CGL**,
not the auto policy.

**But:** where such a vehicle is **subject to compulsory or financial
responsibility law** because it travels on public roads, it becomes an
**auto** for insurance purposes, which is what **symbol 19** addresses.

## Trucking and motor carriers

Businesses hauling goods for others carry additional requirements:

- **Federal filings** — endorsements guaranteeing public liability limits set
  by federal regulation for interstate carriers.
- **Motor truck cargo** — the carrier's liability for goods being hauled,
  written as inland marine.
- **Trailer interchange** — physical damage to trailers of others in the
  insured's possession under an interchange agreement.
- **Non-trucking liability** ("bobtail") — the owner-operator's liability
  while the truck is being used **outside** the motor carrier's business.

## How this is examined

**Symbol 1 is liability only**; physical damage cannot use it.

**A business with no owned vehicles** needs hired and non-owned — symbols 8
and 9.

**Garagekeepers: legal liability versus direct primary versus direct excess.**

**Drive Other Car is for an individual with no personal auto policy.**

**Non-owned coverage is excess** over the employee's own policy.

**Mobile equipment belongs on the CGL** unless registration makes it an auto.

## Check yourself

1. An accounting firm owns no vehicles, but its staff drive their own cars to
   clients. Which symbols does it need?
2. A repair shop damages a customer's car while test-driving it. Which
   coverage, and which basis would pay even if the shop were not negligent?
3. Why can physical damage not be written under symbol 1?
4. An executive drives a company car and owns no personal policy. She rents a
   car on holiday and causes an accident. What was needed?
5. A forklift is used only inside the insured's warehouse. Which policy covers
   liability arising from it?
6. An employee causes an accident driving their own car on a company errand.
   Which policy is primary?

## Answers

1. **8 and 9** — hired and non-owned autos.
2. **Garagekeepers**, on a **direct primary** or **direct excess** basis.
   Legal liability alone would require negligence.
3. Because symbol 1 means **any auto**, including vehicles the insurer has
   never seen or rated. An insurer will not cover the hull of an unknown
   vehicle.
4. A **Drive Other Car** endorsement on the business auto policy.
5. **The CGL.** It is mobile equipment, not an auto.
6. **The employee's own policy.** The business's non-owned coverage is
   **excess** over it.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
