-- Texas Exam Prep — content seed, chunk 16 of 27
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '9de6577b-bb16-5031-9916-7726f5831b08', '1549f9c3-59b6-59d8-aac7-8a6f00a174d6', c.id, 'Bonds',
       'bonds', 'Why a bond has three parties and insurance has two, and what that changes.', 6,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '9de6577b-bb16-5031-9916-7726f5831b08', c.id, $lesson$# Not insurance, though it is sold by insurers

A bond and an insurance policy look similar and behave differently. The
difference is the whole topic.

## Two parties versus three

**An insurance policy has two parties**: the insurer and the insured. The
insurer accepts a risk and expects some losses; premiums are priced to pay
them.

**A bond has three**:

- **The principal** — the party whose performance or honesty is guaranteed.
- **The obligee** — the party protected, who required the bond.
- **The surety** — the party guaranteeing the principal to the obligee.

**The surety guarantees the principal's performance to the obligee. If the
principal fails, the surety pays the obligee — and then recovers from the
principal.**

That last clause is the crux. **A surety expects no losses.** Suretyship is
underwritten as a credit decision, not a risk decision: the surety is
satisfied the principal can and will perform, and treats any payment as an
advance to be repaid.

Two consequences follow directly, and both are examined:

- **The principal must indemnify the surety.** An insured never repays an
  insurer; a principal always repays a surety.
- **Bond underwriting examines the principal's character, capacity and
  capital** — credit, experience, financial statements, work in progress.

## Surety bonds

### Contract bonds

Used in construction, where an owner needs assurance the job will be finished.

- **Bid bond** — guarantees that if the contractor is awarded the job, they
  will **enter into the contract** at the bid price and furnish the required
  performance bond. Protects the owner against a contractor who bids low and
  walks away, leaving the owner with the next-lowest bid.
- **Performance bond** — guarantees the work will be **completed** per the
  contract. If the contractor defaults, the surety must complete the job,
  arrange for its completion, or pay the owner's cost of completing it.
- **Payment bond** (labour and material) — guarantees that **subcontractors
  and suppliers are paid**, so they do not file liens against the owner's
  property.
- **Maintenance bond** — guarantees the work against **defects** for a stated
  period after completion.
- **Supply bond** — guarantees delivery of materials per a supply contract.
- **Completion bond** — given to a **lender** rather than an owner,
  guaranteeing the project is finished free of liens.

The bid–performance–payment sequence is the most common exam question in this
lesson: **the bid bond gets you the contract, the performance bond finishes
the work, the payment bond pays the subcontractors.**

### Court bonds

- **Judicial bonds** guarantee a party in litigation will meet its
  obligations: **appeal bonds**, **attachment bonds**, **injunction bonds**,
  **replevin bonds**.
- **Fiduciary bonds** guarantee that a person appointed by a court to manage
  another's affairs — an **executor, administrator, guardian, trustee or
  receiver** — will do so faithfully.
- **Bail bonds** guarantee a defendant's appearance in court.

### Public official bonds

Guarantee that an elected or appointed official will **faithfully perform the
duties of office and account for public funds.**

### Licence and permit bonds

Required by a public authority before a licence issues. They guarantee the
holder will **comply with the law governing the activity** and compensate
those harmed by non-compliance. **Insurance producers in many states must
carry one**, which is the example closest to home.

## Fidelity bonds

**A fidelity bond guarantees the honesty of a person handling money or
property.** It is the one class of bond closest to insurance, and the exam
tests the difference from employee dishonesty coverage.

Three forms of coverage:

- **Name schedule** — covers **named individuals**, each with a stated
  amount. Adding a person requires notifying the surety.
- **Position schedule** — covers **positions** rather than people, so whoever
  occupies "head cashier" is covered.
- **Blanket** — covers **all employees**, without naming anybody.

Blanket forms come in two shapes: **commercial blanket**, where the limit
applies **per loss** however many employees were involved, and **blanket
position**, where the limit applies **to each employee**, so a three-employee
conspiracy has three limits available.

**Blanket position provides more coverage for the same limit** where several
employees collude, which is the distinction to remember.

## Bonds versus insurance, side by side

| | Insurance | Surety bond |
| --- | --- | --- |
| Parties | **Two** | **Three** |
| Expectation of loss | Losses expected, priced in | **No loss expected** |
| Repayment | Insured never repays | **Principal must indemnify the surety** |
| Underwriting | Risk selection | **Credit judgement** |
| Cancellation | Usually cancellable | Often non-cancellable for the bond's term |
| Premium | Rate for assumed risk | A **service fee** for the guarantee |

## How this is examined

**The three parties, and who is who** in a fact pattern. The contractor is the
principal; the project owner is the obligee; the bonding company is the
surety.

**The principal must reimburse the surety.**

**Bid versus performance versus payment bond.**

**Blanket position versus commercial blanket** where several employees are
involved.

**A bond is a credit instrument**, not a risk transfer.

## Check yourself

1. A contractor is bonded on a school project. Who is the principal, who the
   obligee, who the surety?
2. A contractor abandons a job half-finished. The surety pays the owner
   $400,000 to complete it. Does the contractor owe anything?
3. A contractor submits the low bid and then refuses to sign. Which bond, and
   what does it protect the owner against?
4. Subcontractors are unpaid and threaten liens on the owner's property. Which
   bond?
5. Four employees conspire to steal $200,000. The employer has a $75,000
   blanket position bond. Roughly what is available?
6. Why does a surety expect no losses?

## Answers

1. The **contractor** is the principal, the **school district** the obligee,
   the **bonding company** the surety.
2. **Yes — the full $400,000.** The principal must indemnify the surety.
3. The **bid bond**, protecting the owner against the extra cost of going to
   the next bidder.
4. The **payment bond** (labour and material).
5. **$300,000** — blanket position applies the limit **to each employee**, so
   four employees give four limits.
6. Because the bond is a **credit judgement**: the surety underwrites the
   principal's ability and willingness to perform, and any payment is
   recoverable from the principal.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '9de6577b-bb16-5031-9916-7726f5831b08', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '858d9378-6837-5721-8736-5adc0bb90504', '1549f9c3-59b6-59d8-aac7-8a6f00a174d6', c.id, 'Professional Liability',
       'professional-liability', 'The coverages that answer for advice, expertise and decisions — all excluded from the CGL.', 7,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '858d9378-6837-5721-8736-5adc0bb90504', c.id, $lesson$# When the injury is caused by judgement, not by an accident

**The CGL excludes professional services.** It covers accidents — a customer
slipping, a product failing. It does not cover the consequences of getting
professional advice wrong, because that is not an accident and cannot be
priced like one.

Professional liability fills the gap, and it differs from the CGL in three
structural ways:

- **The trigger is usually claims-made**, not occurrence, because professional
  claims surface years later.
- **It commonly covers economic loss**, not just bodily injury and property
  damage. A negligent audit causes no physical harm at all.
- **Many forms require the insured's consent to settle**, because a settlement
  implies professional failure and may be reportable.

## The standard of care

The insured is judged against **what a reasonably prudent member of that
profession would have done in the same circumstances**. This is a higher and
more specific standard than the ordinary reasonable-person test of general
negligence, and it is why the profession's own practices are usually decisive.

## Errors and omissions

**E&O covers financial loss suffered by a client because of the insured's
negligent act, error or omission in performing professional services.**

The general-purpose form, used for professions whose failures cost money
rather than health: **insurance agents and brokers**, real estate agents,
accountants, architects and engineers, consultants, technology providers,
lawyers (usually "lawyers professional liability").

**An insurance producer's own E&O** is the closest example. The claim that
brings it: failing to place requested coverage, placing the wrong limit,
letting a policy lapse, or giving advice on coverage that turns out wrong.

## Medical malpractice

**Covers physicians, surgeons, dentists, nurses and other health care
providers** for injury arising from professional services.

Two related forms:

- **Professional liability** for the individual practitioner.
- **Hospital or health care facility professional liability** for the
  institution, plus a **general liability** part for ordinary premises
  accidents.

Points that appear:

- **Consent to settle is common**, because settlements are reported to
  national practitioner databanks and affect licensure.
- **Tail coverage matters enormously**, because a claim may arise many years
  after treatment — particularly where a child was the patient, since the
  limitation period may not begin until they reach majority.
- **Medical payments under a CGL** is a different thing entirely: it pays a
  visitor's medical bills without fault and has nothing to do with
  malpractice.

## Directors and officers

**D&O covers the personal liability of directors and officers for wrongful
acts in managing the organisation** — breaches of duty, misstatements,
misleading statements, neglect or errors in their capacity as officers.

Who sues: **shareholders, employees, competitors, customers, regulators**.
The claims are typically about decisions rather than accidents — a
misrepresentation in a prospectus, a sale at an inadequate price, a failure to
supervise.

The three standard insuring agreements:

- **Side A** — pays the **individual directors and officers** where the
  company cannot or does not indemnify them, such as in insolvency or where
  indemnification is legally barred.
- **Side B** — reimburses **the company** for indemnifying its directors and
  officers.
- **Side C** — covers **the entity itself** for securities claims.

**Side A is the coverage a director personally cares about**, because it is
the one that survives the company's failure. That is the examinable point.

## Employment practices liability

**EPLI covers claims by employees and applicants arising from the employment
relationship**: wrongful termination, discrimination, harassment, retaliation,
failure to promote, wrongful discipline, defamation in the employment context.

It exists because **the CGL excludes it** and **workers' compensation does not
reach it** — these are not bodily injuries at work, they are employment
decisions. It is claims-made, and usually carries a deductible or retention the
employer bears on every claim, since small claims are frequent.

## Cyber liability and data breach

**The third-party half of cyber**, complementing the first-party coverage in
the commercial property lesson.

It covers what the insured **owes others** after a cyber event:

- **Liability for a privacy breach** — claims by individuals whose personal
  data was exposed.
- **Regulatory defence and penalties**, where the law permits them to be
  insured.
- **Network security liability** — where the insured's compromised systems
  harmed a third party.
- **Media liability** — defamation or infringement in the insured's online
  content.

**Funds transfer fraud** and **social engineering** — where an employee is
deceived into wiring money to a fraudster — sit on the first-party side, and
are often sub-limited because the exposure is large and the control is human
rather than technical.

Why cyber is bought separately: standard forms respond to **physical damage to
tangible property**, and **data is generally not tangible property**. Many
forms now also carry express cyber exclusions.

## Liquor liability

**Covers those in the business of manufacturing, distributing, selling,
serving or furnishing alcohol** for liability arising from that activity.

**The CGL excludes it for those in the business.** The exclusion does not
apply to a host who is not in the alcohol business, so an ordinary company
holding a party retains **host liquor liability** under its CGL.

The exposure arises from **dram shop laws** — statutes making a server liable
for injury caused by a patron served while obviously intoxicated, or served
under age. Where a state has a dram shop act, a restaurant or bar without
liquor liability coverage is running an uninsured exposure.

The exam wants two things: **the CGL covers host liquor liability but excludes
those in the alcohol business**, and **dram shop laws are the reason.**

## Claims-made mechanics, once more

Because nearly every form here is claims-made:

- **The retroactive date** bars acts before it, whenever the claim arrives.
  Watch for a renewal that advances it.
- **A basic extended reporting period** is automatic and short.
- **A supplemental extended reporting period** — the "tail" — is purchased,
  must be bought within a short window after expiry, and is what a
  professional retiring or changing insurer needs.
- **Prior acts coverage** on a new policy, with the retroactive date preserved,
  is the alternative to buying a tail.

## How this is examined

**The CGL excludes professional services** — which is why every one of these
exists.

**Side A D&O** protects individuals when the company cannot indemnify them.

**Host liquor liability is covered by the CGL; those in the business are
excluded.**

**Consent to settle** is a professional liability feature.

**Claims-made retroactive dates and tails.**

**EPLI covers employment decisions, which are neither CGL nor workers'
compensation claims.**

## Check yourself

1. An insurance agent fails to add a newly purchased building to a client's
   policy and it burns. Which coverage responds?
2. A company holds a Christmas party; a guest drinks too much and injures
   somebody driving home. Does the CGL respond?
3. A corporation becomes insolvent and cannot indemnify its directors, who are
   personally sued. Which D&O insuring agreement?
4. An employee sues for wrongful termination. CGL, workers' compensation, or
   something else?
5. A surgeon retires. Claims may arise for years. What must be arranged?
6. A hacker steals customer records and the customers sue. First-party or
   third-party cyber coverage?

## Answers

1. The agent's **errors and omissions** policy.
2. **Yes** — the company is not in the alcohol business, so **host liquor
   liability** remains covered by the CGL.
3. **Side A**, which pays the individuals directly where the company cannot.
4. **Employment practices liability.** The CGL excludes it and workers'
   compensation does not reach employment decisions.
5. A **supplemental extended reporting period** (tail), bought within the
   window after the policy ends — or prior acts coverage on a new policy with
   the retroactive date preserved.
6. **Third-party** — cyber liability. The customers' claims are what the
   insured owes others.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '858d9378-6837-5721-8736-5adc0bb90504', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '88047c29-a279-5436-aa7a-24977ea5abb2', '1549f9c3-59b6-59d8-aac7-8a6f00a174d6', c.id, 'Umbrella and Excess Liability',
       'umbrella-and-excess-liability', 'More limit on top of what you have — and, in an umbrella, some coverage the underlying policies never had.', 8,
       'draft', 12
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '88047c29-a279-5436-aa7a-24977ea5abb2', c.id, $lesson$# Two things that look the same and are not

Both sit above a primary policy. Only one of them broadens coverage.

## Excess liability

**An excess policy provides additional limits over specified underlying
policies, following their terms.**

It is described as **"following form"** — it covers what the underlying policy
covers, no more and no less, and it begins where the underlying limit ends.
If the primary policy excludes something, so does the excess.

An excess policy buys **height**, not **breadth**.

## Umbrella liability

**An umbrella does three things**, and the third is what distinguishes it:

1. **It provides excess limits** over the underlying policies — like an
   excess policy.
2. **It drops down** to replace an underlying policy whose aggregate has been
   exhausted by other claims.
3. **It covers some losses the underlying policies exclude**, subject to a
   **self-insured retention**.

That third function is the examined one. **Where a claim is covered by the
umbrella but not by any underlying policy, the umbrella pays — after the
insured bears the self-insured retention.**

### The self-insured retention

**The SIR is the amount the insured pays on a claim the umbrella covers but no
underlying policy does.** Commonly $10,000 or $25,000.

It is not a deductible in the ordinary sense: **it applies only where there is
no underlying coverage.** Where an underlying policy does respond, the
umbrella simply sits above its limit and the SIR is irrelevant.

What an umbrella typically covers beyond the underlying policies: **personal
injury offences** not in the underlying form, **worldwide coverage**,
**liability assumed under contract** beyond the underlying's insured contract
definition, and certain **watercraft and aircraft** exposures.

## Underlying limit requirements

An umbrella requires the insured to **carry and maintain stated underlying
limits** — commonly $1,000,000 per occurrence on general liability,
$1,000,000 on auto, and $500,000 or $1,000,000 on employers' liability.

**If the insured lets an underlying policy lapse or carries less than
required, the umbrella responds as though the required underlying limit were
in place**, and the insured absorbs the shortfall. That is a reliable exam
point: the umbrella does not become primary just because the primary vanished.

## Personal umbrella

The personal version sits above homeowners and personal auto, typically
requiring $300,000 or $500,000 of underlying liability on each.

- **Limits start at $1,000,000** and are bought in millions.
- It covers **personal injury** offences — libel, slander, false arrest,
  invasion of privacy — which a homeowners policy typically does not.
- It **excludes business and professional exposures**, intentional acts, and
  the insured's own injuries.
- It is cheap relative to its limit, because the underlying policies absorb
  the frequent small claims and the umbrella sees only the rare severe one.

## How the layers stack

A commercial programme might read:

| Layer | Limit |
| --- | --- |
| **Primary CGL** | $1,000,000 |
| **Umbrella** | $5,000,000 excess of the primary |
| **Excess (first layer)** | $10,000,000 excess of $6,000,000 |
| **Excess (second layer)** | $25,000,000 excess of $16,000,000 |

A $4,000,000 judgment: the CGL pays $1,000,000, the umbrella pays $3,000,000,
the excess layers pay nothing. Each layer is only reached when everything
beneath it is exhausted.

## How this is examined

**Umbrella broadens; excess does not.**

**The self-insured retention applies only where no underlying policy
responds.**

**An insufficient or lapsed underlying policy leaves the insured to fill the
gap**, not the umbrella.

**Drop-down** where the underlying aggregate is exhausted by other claims.

**Layering arithmetic** with a judgment spread across policies.

## Check yourself

1. A claim is excluded by the CGL but covered by the umbrella. The SIR is
   $25,000 and the loss is $300,000. What does the umbrella pay?
2. The same insured's CGL aggregate is exhausted in October by earlier claims.
   A new covered claim arrives in November. What does the umbrella do?
3. An umbrella requires $1,000,000 of underlying auto liability. The insured
   carries $500,000 and has a $3,000,000 loss. What is the insured's share?
4. Does an excess policy cover a loss the primary excludes?
5. A personal umbrella insured is sued for slander. The homeowners policy does
   not cover it. Is the umbrella likely to?

## Answers

1. **$275,000** — the loss less the $25,000 self-insured retention, which
   applies because no underlying policy responds.
2. It **drops down** to respond in place of the exhausted underlying
   aggregate.
3. **$500,000.** The umbrella responds as though the required $1,000,000 were
   in place, so the insured absorbs the shortfall between the $500,000
   actually carried and the $1,000,000 required.
4. **No.** An excess policy follows form — it adds limit, not breadth.
5. **Yes.** Umbrellas typically cover personal injury offences such as
   slander, subject to the self-insured retention.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '88047c29-a279-5436-aa7a-24977ea5abb2', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
