-- Texas Exam Prep — content seed, chunk 16 of 30
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '65f6bec4-114d-558c-9035-89adbd274ada', '9f729b3f-d119-5250-beea-518a3bc8de3e', c.id, 'Territory and the Terrorism Risk Insurance Act',
       'territory-and-the-terrorism-risk-insurance-act', 'Where a policy works geographically, and the federal backstop that made terrorism insurable again.', 10,
       'draft', 11
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '65f6bec4-114d-558c-9035-89adbd274ada', c.id, $lesson$# Two provisions about where and what

Both are small, both appear in the blueprint twice — once under policy
provisions and contract law, once under casualty policy provisions — and both
are easy marks if you have read them once.

## Territory

**The territory (or policy territory) provision states where coverage
applies.** A policy is not worldwide unless it says so.

The usual definition in general liability and auto forms covers:

- **The United States**, including its territories and possessions;
- **Puerto Rico**; and
- **Canada**.

That is the core. Forms then extend it in two ways:

- **International waters or airspace**, but only in transit between places in
  the territory above.
- **Anywhere in the world** for a narrow set of exposures — typically
  **products** manufactured or sold in the territory that cause injury
  elsewhere, and the **independent activities of a person temporarily
  outside** the territory on the insured's business — **provided the suit is
  brought within the territory**.

That proviso is the examined point. **A worldwide extension usually still
requires that the lawsuit be brought in the United States (or Canada).** A
product made in Texas that injures somebody in Germany is covered if the suit
is filed in a US court; a German judgment obtained in a German court
generally is not.

Property forms take a different approach: **coverage attaches to described
premises**, and property away from the premises is covered only by specific
extensions or by an inland marine form, which is where property genuinely in
transit belongs.

In **personal auto**, the territory is the United States, its territories and
possessions, Puerto Rico and Canada. **Mexico is not included** — a driver
going to Mexico needs a Mexican policy from a Mexican insurer, because Mexico
does not recognise foreign auto insurance. This is a favourite question.

## The Terrorism Risk Insurance Act

### Why it exists

Before September 2001, terrorism was not excluded from most commercial
property and liability policies — it was simply not thought about, and was
covered by silence. The losses that followed made insurers move to exclude
it, and reinsurers to withdraw. Commercial property development stalled where
lenders required terrorism coverage that no longer existed.

**TRIA, enacted in 2002 and extended several times since, is a federal
backstop: the government shares in insured losses from certified acts of
terrorism, so that private insurers can afford to offer the coverage.**

It is a **reinsurance programme**, not an insurance policy. Nobody buys a
policy from TRIA.

### How it works

**Certification.** Losses are covered by the programme only for an act of
terrorism **certified by the Secretary of the Treasury**, in consultation with
other federal officials. Certification requires that the act be violent or
dangerous to human life, property or infrastructure, committed as part of an
effort to coerce the United States civilian population or influence policy,
and that aggregate insured losses **exceed a statutory trigger**.

**Mandatory offer.** **An insurer writing commercial property and casualty
insurance must offer terrorism coverage** on terms not differing materially
from the rest of the policy. This is the obligation that matters to a
producer.

**The insured may decline.** Coverage is not compulsory for the buyer.
Where the insured rejects it, the insurer may attach a terrorism exclusion.
**The rejection should be in writing**, and the premium for the coverage must
be **separately stated** so the insured knows what they are accepting or
declining.

**Loss sharing.** Each insurer retains a deductible calculated as a
percentage of its own earned premium. Above that, the federal government pays
a share of losses and the insurer the remainder, subject to an annual
aggregate cap on the whole programme.

### What it does and does not cover

- It applies to **commercial** lines. Personal lines are outside the
  programme, although personal policies are generally silent on terrorism and
  so tend to cover it.
- **Nuclear, biological, chemical and radiological** losses are generally
  excluded from the coverage offered, unless the underlying policy covers
  them.
- **Domestic as well as foreign** acts have been certifiable since the 2007
  reauthorisation removed the requirement that the act be committed on behalf
  of a foreign interest.
- **Workers' compensation is different.** A workers' compensation insurer
  **may not exclude terrorism at all**, because state law requires the policy
  to cover statutory benefits whatever the cause. The insured has no right to
  decline it there.

That last point is the trap. **Everywhere else the insured may reject
terrorism coverage; in workers' compensation they may not.**

## How this is examined

**Mexico** in personal auto territory.

**The worldwide products extension**, and the requirement that suit be
brought within the policy territory.

**The mandatory offer** — the insurer must offer, the insured may decline,
the premium must be separately stated, the rejection should be written.

**Certification by the Secretary of the Treasury**, not by the insurer or the
state regulator.

**Workers' compensation cannot exclude terrorism.**

## Check yourself

1. An insured drives from Houston to Monterrey. Does the personal auto policy
   respond to an accident there?
2. A product manufactured in the United States injures a consumer in France,
   who sues in a French court. Is the CGL's worldwide extension likely to
   respond?
3. Who certifies an act of terrorism for TRIA purposes?
4. A commercial insured does not want terrorism coverage. May the insurer
   simply leave it out of the quote?
5. May a workers' compensation policy exclude terrorism?

## Answers

1. **No.** Mexico is outside the policy territory; a Mexican policy from a
   Mexican insurer is required.
2. **No.** The extension generally requires the **suit to be brought within
   the policy territory**.
3. **The Secretary of the Treasury**, in consultation with other federal
   officials.
4. **No.** The insurer must **offer** the coverage with the premium
   separately stated; the insured then declines, preferably in writing.
5. **No.** Statutory benefits must be paid whatever the cause, so terrorism
   cannot be excluded from workers' compensation.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '65f6bec4-114d-558c-9035-89adbd274ada', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', '1549f9c3-59b6-59d8-aac7-8a6f00a174d6', c.id, 'Commercial General Liability',
       'commercial-general-liability', 'Three coverages, four exposures, six limits — the form most commercial liability questions are built on.', 1,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', c.id, $lesson$# The business's liability policy

The CGL covers a business's liability to **third parties** — customers,
visitors, passers-by, the users of its products. Not its employees (workers'
compensation), not its vehicles (commercial auto), not its professional
advice (professional liability).

## The four exposures

Traditionally grouped as **premises and operations**, **products and completed
operations**, **contractual**, and **personal and advertising injury**. The
blueprint names the first two explicitly.

**Premises** — somebody is injured on the insured's property. A customer
slips in a supermarket aisle.

**Operations** — somebody is injured by the insured's work **while it is in
progress**, whether at the insured's premises or elsewhere. A plumber floods
a client's kitchen mid-job.

**Products** — injury or damage caused by a product the insured made or sold,
**after it has left the insured's possession**.

**Completed operations** — injury or damage arising from the insured's work
**after it is finished** and handed over. A deck collapses two years after the
builder left.

**Products and completed operations are grouped together** because they share
a characteristic: the loss happens when the insured is no longer there, often
long afterwards. They also share **their own separate aggregate limit**.

The dividing line is tested directly: **work in progress is operations;
work handed over is completed operations.**

## The three coverages

### Coverage A — Bodily Injury and Property Damage Liability

The core. Pays sums the insured becomes **legally obligated to pay as
damages** because of bodily injury or property damage caused by an
**occurrence** in the coverage territory.

**An occurrence is an accident, including continuous or repeated exposure to
substantially the same general harmful conditions.** The word does the work
of excluding the deliberate: intentional injury is not an occurrence.

**Bodily injury** means bodily injury, sickness or disease, including death.
**Property damage** means physical injury to tangible property, including loss
of use, **and** loss of use of tangible property that is not physically
injured.

#### Occurrence versus claims-made

**An occurrence form** responds to injury or damage **taking place during the
policy period**, whenever the claim arrives.

**A claims-made form** responds to claims **first made during the policy
period**, and adds two mechanisms:

- **The retroactive date.** Injury or damage before it is not covered, no
  matter when claimed. A retroactive date that moves forward on renewal
  quietly destroys years of coverage — the thing to watch for.
- **Extended reporting periods.** A **basic** tail is automatic and short; a
  **supplemental** tail is bought, usually unlimited in time, and must be
  purchased within a short window after the policy ends.

Claims-made exists for long-tail exposures — where injury may not appear for
decades — because an insurer cannot price a promise whose claims will arrive
forty years later.

### Coverage B — Personal and Advertising Injury Liability

Covers injury arising from a list of **offences**, not from an accident. The
list:

- **false arrest, detention or imprisonment**
- **malicious prosecution**
- **wrongful eviction**, wrongful entry, or invasion of the right of private
  occupancy
- **slander or libel** — oral or written publication disparaging a person or
  organisation, or their goods
- **violation of a person's right of privacy**
- **use of another's advertising idea**
- **infringement of copyright, trade dress or slogan** in the insured's
  advertisement

Two exam points: **these are offences, not occurrences**, so the trigger is
the committing of the offence; and **patent and trademark infringement are
generally not covered** — the list names copyright, trade dress and slogan.

### Coverage C — Medical Payments

Pays medical expenses for bodily injury on the insured's premises or arising
from operations, **regardless of fault**, provided the expenses are incurred
within a stated period — commonly **three years** — of the accident.

It exists to settle small injuries quickly and goodwill intact, before they
become liability claims. It **does not apply to the insured, employees, or
tenants**, and it does not apply where the injured person is covered by
workers' compensation.

## Supplementary payments

Paid **in addition to the limits**: defence costs, the cost of bonds to
release attachments, **premiums** on appeal bonds and bail bonds (commonly up
to $250), reasonable expenses at the insurer's request including lost earnings
(commonly up to $250 a day), court costs, and **post-judgment interest**.

## Who is an insured

The form defines it by the insured's structure:

- **Sole proprietor** — the individual and their spouse, for the conduct of
  the business.
- **Partnership or joint venture** — the partners and their spouses.
- **Limited liability company** — members and managers.
- **Corporation** — executive officers, directors and stockholders, acting
  within their duties.
- **Employees and volunteer workers**, for acts within the scope of their
  employment — **but not for bodily injury to a fellow employee**, and not for
  professional services.
- **Real estate managers** acting for the insured.
- **Newly acquired organisations**, automatically, for a limited period —
  commonly **90 days** or until the policy ends, whichever is first.

**The first named insured** has the distinct duties met in Module 3: it
receives notices, pays premium, may cancel, and handles the **premium audit**.

**Additional insureds** are added by endorsement, for liability arising out of
the named insured's work or premises.

## The six limits

The CGL's limit structure is examined more often than anything else in the
form.

| Limit | What it caps |
| --- | --- |
| **Each occurrence** | All damages from one occurrence, under A and C combined |
| **General aggregate** | Everything paid in the policy period **except** products-completed operations |
| **Products–completed operations aggregate** | Its own separate annual cap |
| **Personal and advertising injury** | Per person or organisation, under Coverage B |
| **Damage to premises rented to you** | Fire (and in later editions, certain other) damage to premises the insured rents |
| **Medical expense** | Per person, under Coverage C |

The points that get tested:

- **Products-completed operations has its own aggregate**, separate from the
  general aggregate. Exhausting one does not exhaust the other.
- **The aggregate is annual.** Once exhausted, the policy is finished for that
  period even though months remain — and the duty to defend ends with it.
- **Damage to premises rented to you** is the exception to the property damage
  exclusion for property in the insured's care: a tenant who burns the
  landlord's building has this, and nothing else.

## Key exclusions

- **Expected or intended injury.**
- **Contractual liability** — except for an **insured contract**, a defined
  list including leases, sidetrack agreements, easements, and the part of any
  contract assuming another's tort liability. This is a broad exception that
  effectively restores most commercial hold-harmless agreements.
- **Workers' compensation and employer's liability** — employees' injuries
  belong elsewhere.
- **Pollution**, with narrow exceptions.
- **Aircraft, auto and watercraft** — but **mobile equipment is covered**.
- **Damage to your product** and **damage to your work** — the policy covers
  the harm the product does, not the cost of the defective product itself.
  This is the **business risk** principle: replacing your own bad work is a
  cost of doing business, not an insurable accident.
- **Damage to property in your care, custody or control**, except the rented
  premises limit.
- **Recall of products** — the "sistership" exclusion.
- **Liquor liability**, for those in the business of serving alcohol.
- **Professional services.**

## Mobile equipment versus auto

**Mobile equipment** — bulldozers, farm machinery, forklifts, vehicles
maintained solely on the insured's premises, and vehicles whose purpose is to
carry permanently mounted equipment like drills or cranes — is **covered by
the CGL**.

**Autos** — vehicles subject to compulsory registration and used on public
roads — are **excluded** and belong on the commercial auto policy.

The line moves in one notable case: **self-propelled vehicles carrying
permanently attached equipment are mobile equipment, unless they are subject
to registration**, in which case they become autos.

## How this is examined

**Operations versus completed operations.**

**The two aggregates**, and that exhausting one does not exhaust the other.

**"Damage to your work" and "damage to your product"** — the product that
injures somebody is covered; the product itself is not.

**Coverage B's list of offences**, especially that patent and trademark are
absent.

**Medical payments pays without fault** and not to employees.

**Insured contract** as the exception to the contractual liability exclusion.

**Mobile equipment versus auto.**

## Check yourself

1. A contractor installs a faulty water heater. It leaks two years later,
   ruining a floor. Which exposure, and is the water heater itself covered?
2. A CGL has a $1m occurrence limit, $2m general aggregate and $2m
   products-completed operations aggregate. Premises claims have exhausted the
   general aggregate in July. A products claim arrives in September. Covered?
3. A visitor trips in the insured's lobby. The insured is plainly not
   negligent, but the visitor has a $3,000 hospital bill. Anything payable?
4. An employee is injured by a colleague's negligence. Does the CGL respond?
5. A restaurant's advertisement copies a competitor's slogan. Which coverage?
6. A tenant's negligence causes a fire that damages the landlord's building.
   Is that covered, given the care, custody or control exclusion?

## Answers

1. **Completed operations** — the work was finished and handed over. The
   **floor damage is covered**; the **water heater itself is not**, under the
   damage-to-your-product and damage-to-your-work exclusions.
2. **Yes.** Products-completed operations has its **own separate aggregate**,
   untouched by the premises claims.
3. **Yes** — Coverage C, medical payments, pays regardless of fault, for
   expenses incurred within the stated period.
4. **No.** Employee injuries are excluded; workers' compensation and
   employers' liability respond.
5. **Coverage B**, personal and advertising injury — infringement of slogan in
   an advertisement.
6. **Yes, up to the "damage to premises rented to you" limit**, which is the
   express exception to that exclusion.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
