-- Texas Exam Prep — content seed, chunk 20 of 28
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '4a2ea53d-58b0-5534-afb5-31d5aca09281', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Unfair and Prohibited Trade Practices',
       'unfair-and-prohibited-trade-practices', 'Chapter 541''s list of prohibited acts, the private right of action with treble damages, and the one defendant it does not reach.', 5,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '4a2ea53d-58b0-5534-afb5-31d5aca09281', c.id, $lesson$# The chapter a producer is disciplined under

**§541.003** states the prohibition in one sentence: **a person may not engage
in an unfair method of competition or an unfair or deceptive act or practice
in the business of insurance.** Everything else in the chapter either defines
what that means or provides a remedy.

**§541.002(2)** defines **"person"** broadly — an individual, corporation,
association, partnership, reciprocal or interinsurance exchange, Lloyd's plan,
fraternal benefit society or other legal entity engaged in the business of
insurance, **"including an agent, broker, or adjuster."** The chapter reaches
the producer personally, not only the company.

**§541.008** — the chapter **"shall be liberally construed and applied to
promote the underlying purposes."** Where a provision is capable of two
readings, the consumer-protective one is intended.

## The prohibited practices — Subchapter B

### §541.051 Misrepresentation regarding a policy or insurer

Covers estimates, illustrations, circulars and statements misrepresenting a
policy's **terms**, its **benefits or advantages**, or the **dividends** to be
received; false statements about dividends previously paid; misleading
representations about an insurer's **financial condition**; a policy **name or
title** that misrepresents its true nature; and — §541.051(5) —
misrepresentation to a policyholder **to induce them to lapse, forfeit or
surrender an existing policy.**

That last one is **twisting**, and it also appears as a ground for discipline
at §4005.101(b)(7).

### §541.052 False information and advertising

An advertisement, announcement or statement containing an **untrue, deceptive
or misleading** assertion about the business of insurance.

**§541.052(b)** lists where it applies, and the list was updated in 2007:
newspaper or magazine, notice or circular or pamphlet or letter or poster,
radio or television, **through the Internet**, or **"in any other manner."**
A social media post is covered.

### The advertising rules beneath §541.052

**Chapter 541 says what an advertisement may not do; 28 TAC Chapter 21,
Subchapter B says it in detail.** The rules run 28 TAC §21.101–.120 and cover the form
and content of advertisements, identification of the policy and insurer,
description of benefits, premiums, testimonials, use of statistics,
disparagement, comparisons and a general prohibition.

**28 TAC §21.115 is the one written for property and casualty**, and it is
short enough to know outright. It is about a single word.

**28 TAC §21.115(a)** — **no advertisement may use the word "dividends", or similar
words or illustrations, in a manner that states or implies that future
dividends are guaranteed or certain to occur.**

**28 TAC §21.115(b)** defines the word broadly and then carves out the case that
matters: **"dividends" includes every return of premium and payment to
policyholders on a particular policy that is predicated on the insurer's
financial performance or earnings** — but it **does not include** a return of
premium under a **nondiscretionary provision or endorsement** clearly providing
for payment under a **rating plan approved or promulgated by the Department.**

So the line is between the **discretionary** and the **contractual**. A payment
that depends on how the insurer performs is a dividend and may never be
promised. A return of premium the policy already obliges the insurer to make,
under an approved rating plan, is not a dividend at all and may be described as
what it is.

**28 TAC §21.111** covers **comparisons**, which is the advertising face of the
twisting problem at §541.051(5).

### §541.053 Defamation of an insurer

A statement that is **false, maliciously critical of, or derogatory to the
financial condition of an insurer** *and* is **calculated to injure** a person
engaged in the business of insurance.

**Both limbs are required.** A true statement about a weak insurer is not
defamation under this section; neither is an idle false one made with no
intent to injure.

### §541.054 Boycott, coercion or intimidation

Committing, **through concerted action or an agreement to commit**, an act of
boycott, coercion or intimidation **resulting in or tending to result in an
unreasonable restraint of, or monopoly in, the business of insurance.**

Note **"concerted action or an agreement"** — this is an antitrust provision.
One person acting alone is generally outside it.

### §541.055 False financial statement

**With intent to deceive**, filing or publishing a false statement of an
insurer's financial condition; or making a false entry, or wilfully omitting a
true entry of a material fact, in an insurer's books **with intent to
deceive** an examiner or a public official.

### §541.059 Deceptive name, word, symbol, device or slogan

Using a business name or slogan **the same as or deceptively similar to** one
already adopted by an insurance entity.

**§541.059(b)** gives the defence: whoever demonstrates **first continuous
actual use** has not violated the section.

### §541.060 Unfair settlement practices

The claims-handling list, and the most heavily examined section in the
chapter. It is an unfair practice to:

1. **misrepresent a material fact or policy provision** relating to coverage;
2. **fail to attempt in good faith to effectuate a prompt, fair and equitable
   settlement** of a claim **where liability has become reasonably clear** —
   including using one clear coverage to pressure settlement of another;
3. **fail to promptly provide a reasonable explanation** of the basis in the
   policy for a **denial** or a compromise offer;
4. **fail within a reasonable time to affirm or deny coverage**, or to submit
   a **reservation of rights**;
5. **refuse, fail or unreasonably delay a first-party settlement offer** on
   the basis that other coverage may be available or that third parties are
   responsible;
6. **enforce a full and final release when only a partial payment has been
   made**, unless the payment settles a doubtful or disputed claim;
7. **refuse to pay a claim without conducting a reasonable investigation**;
8. on a **Texas personal automobile policy**, delay or refuse settlement
   **solely because other insurance of a different kind** is available; or
9. **require the claimant to produce federal income tax returns** as a
   condition of settlement — unless a court orders it, the claim involves a
   **fire loss**, or the claim involves **lost profits or income**.

**"Reasonably clear" in (2) is the operative phrase.** The duty to settle
promptly attaches once liability is reasonably clear, not once it is proved.

**§541.060(b)** is the limitation to remember: **this subsection does not
give a cause of action to a third party** asserting a claim against an
insured covered under a liability policy. A claimant suing the insured cannot
sue the insured's insurer under §541.060.

### §541.061 Misrepresentation of an insurance policy

Misrepresenting a policy by an **untrue statement of material fact**;
**failing to state a material fact** necessary to make other statements not
misleading; making a statement **in a manner that would mislead a reasonably
prudent person** to a false conclusion; a **material misstatement of law**; or
**failing to disclose** a matter required by law to be disclosed.

**Silence is covered.** Two of the five limbs are failures to speak, which is
the distinction from §541.051.

## Rebating and discrimination

The blueprint lists **rebating** and **discrimination** as sub-topics here,
citing §541.056 and §544.002 respectively.

**§541.056 does not exist.** Chapter 541 runs .051 to .055 and then jumps to
.059; sections .056, .057 and .058 were repealed. **Rebating is now at
§1806.104** (casualty), **§1806.053** (automobile) and **§1806.153** (fire),
and it is taught in Module 2 and in `reference/statutes/IN.1806-key-provisions.md`.

**Chapter 544 has not been obtained**, so the Texas discrimination provisions
are not taught here. The general prohibition on discriminating among insureds
of **like hazards** is in §1806.053(1). See `docs/module-5-source-gaps.md`.

## Remedies

### Administrative — Subchapter C

Investigation (**§541.101**), charges and notice of hearing (**§541.102**),
hearing (**§541.103**), determination (**§541.107**), and a **cease and desist
order** (**§541.108**), with the penalties covered in the enforcement lesson:
**$1,000 / $5,000** administrative under §541.110, **$50 / $500 wilful** civil
under §541.111.

### The private action — Subchapter D

This is what makes Chapter 541 matter commercially.

**§541.151** — **a person who sustains actual damages may bring an action**
against another person for damages caused by a practice defined in Subchapter
B, or enumerated as a deceptive trade practice under §17.46(b) of the Business
& Commerce Code where the plaintiff relied on it to their detriment.

> **§17.46(b), Business & Commerce Code**, is the DTPA's own list of deceptive
> trade practices, and §541.151 imports it: a practice enumerated there is
> actionable under Chapter 541 **where the plaintiff relied on it to their
> detriment**. The DTPA also runs its own remedies in **Subchapter E of Chapter
> 17**, which is one of the four bodies of law §4004.105 requires an adjuster's
> continuing education to cover.

**§541.152(a)** — a prevailing plaintiff may obtain **actual damages, court
costs and reasonable and necessary attorney's fees**, an **injunction**, or
any other relief the court thinks proper.

**§541.152(b)** — **on a finding that the defendant acted knowingly, the trier
of fact may award up to three times actual damages.** Treble damages, and
**§541.002(1)** defines **"knowingly"** as **actual awareness** of the falsity,
unfairness or deceptiveness — though "actual awareness may be inferred if
objective manifestations indicate" it.

**§541.152(c)** — **this does not apply to an action against the Texas
Windstorm Insurance Association.** TWIA cannot be hit with treble damages.

**§541.153** — a court **shall** award the defendant costs and attorney's fees
if it finds the action **groundless and brought in bad faith**, or brought for
harassment.

**§541.154(a)** — written notice must be given to the defendant **not later
than the 61st day before the date the action is filed**, advising them of the
specific complaint and the amount of actual damages and expenses, including
attorney's fees. **§541.154(c)** waives it where notice is impracticable
because the action must be filed to beat the limitations period, or is
asserted as a **counterclaim**.

**§541.162 — the limitations period is two years**, running from the date the
practice occurred or the date the plaintiff discovered it or should have
discovered it with reasonable diligence — **extendable by 180 days** where the
defendant's conduct was solely calculated to induce delay.

## How this is examined

**§541.060(2)** — good-faith settlement once liability is **reasonably
clear**.

**§541.060(b)** — **no third-party cause of action** against the insured's
liability insurer.

**Treble damages require a "knowing" violation**, and **do not apply to
TWIA**.

**Two-year limitations, plus 180 days** in the induced-delay case.

**61 days' written notice** before suit.

**Defamation needs both falsity/derogation and intent to injure.**

**Boycott requires concerted action.**

**An advertisement may never state or imply that future dividends are
guaranteed** — 28 TAC §21.115(a) — and a non-discretionary return of premium
under an approved rating plan is not a "dividend" for that purpose.

**Tax returns may be demanded only on a court order, a fire loss, or a lost
profits claim.**

## Check yourself

1. An adjuster tells a claimant the policy excludes their loss when it does
   not. Which section?
2. An insurer's liability is clear but it delays settlement to pressure the
   claimant on an unrelated part of the claim. Which section?
3. A pedestrian injured by an insured sues the insured's liability insurer
   under §541.060. Will it succeed?
4. A jury finds an insurer knowingly committed an unfair practice causing
   $200,000 of actual damages. What is the maximum award of damages?
5. Same finding, but the defendant is TWIA. What changes?
6. An insured discovers in March 2026 an unfair practice that occurred in
   2021. Is the action time-barred?
7. An insurer demands a claimant's tax returns to settle a stolen-vehicle
   claim. Permitted?

## Answers

1. **§541.060(a)(1)** — misrepresenting a material fact or policy provision
   relating to coverage. Also §541.061.
2. **§541.060(a)(2)(B)** — using a clear coverage to influence settlement of
   another portion.
3. **No.** §541.060(b) expressly denies a cause of action to a third party
   asserting a claim against an insured under a liability policy.
4. **$600,000** — up to three times actual damages under §541.152(b), plus
   costs and attorney's fees.
5. **No treble damages.** §541.152(c) excludes actions against the Texas
   Windstorm Insurance Association.
6. **Not necessarily.** §541.162 runs two years from occurrence **or**
   discovery, so a March 2026 discovery starts the clock then.
7. **No.** §541.060(a)(9) permits it only on a court order, for a fire loss,
   or where the claim involves lost profits or income.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '4a2ea53d-58b0-5534-afb5-31d5aca09281', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
