-- Texas Exam Prep — content seed, chunk 22 of 25
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '8c0f54c3-56b6-5422-8ecc-b77835ded5f3', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Texas Workers'' Compensation',
       'texas-workers-compensation', 'The one state where coverage is optional — what a non-subscriber gives up, what it keeps, and the benefit formulas.', 13,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '8c0f54c3-56b6-5422-8ecc-b77835ded5f3', c.id, $lesson$# The state that made it elective

Module 4 described the workers' compensation bargain: the employee gives up
the right to sue, the employer gives up the three common law defences, and
benefits are paid without regard to fault. It also noted that **Texas is the
exception**. This lesson is that exception, from the Labor Code.

Note the code. **Texas workers' compensation is in Title 5 of the Labor Code,
not the Insurance Code** — which is why §31.002(2) makes administering it a
duty of the Department, and why the exam reaches outside the Insurance Code
for it.

## Coverage is elective

**§406.002(a)** — **"Except for public employers and as otherwise provided by
law, an employer may elect to obtain workers' compensation insurance
coverage."**

That single sentence is the most distinctively Texan provision in the module.
**Public employers are outside the election**; a private employer chooses.

**§406.002(b)** — an employer who **elects** to obtain coverage is subject to
the subtitle. So the whole apparatus of exclusive remedy and statutory
benefits follows the election, and an employer that does not elect is outside
it.

**§406.003** — an employer may obtain coverage **through a licensed insurance
company or through self-insurance** as provided by the subtitle.

**§406.004** — an employer who obtains coverage must **notify the division**.
**§406.005** — the employer must **notify its employees**, and failing to do
so is an **administrative violation**. An employee is entitled to know which
system they are in.

## The non-subscriber

An employer that does not elect coverage is a **non-subscriber**. It is
outside the compensation system, so exclusive remedy does not protect it — and
**§406.033** sets the terms on which it can be sued.

### What the non-subscriber loses

**§406.033(a)** — in an action by an employee not covered by workers'
compensation, for injury or death sustained in the course and scope of
employment, **it is not a defence that:**

1. **the employee was guilty of contributory negligence**;
2. **the employee assumed the risk** of injury or death; or
3. **the injury or death was caused by the negligence of a fellow employee.**

These are the same three defences Module 4 described the employer as
surrendering in the ordinary bargain. **The Texas non-subscriber surrenders
them without getting exclusive remedy in return** — which is the whole point,
and the reason most employers subscribe.

### What the non-subscriber keeps

This is the nuance the exam separates, and it is easy to overstate the
non-subscriber's exposure.

**§406.033(d)** — **the plaintiff must prove negligence** of the employer, or
of an agent or servant acting within the general scope of their employment.
**A non-subscriber is not strictly liable.** No negligence, no recovery — which
is very different from the no-fault system it opted out of.

**§406.033(c)** — the employer **may** defend on the ground that the injury
was caused:

1. **by an act of the employee intended to bring about the injury**; or
2. **while the employee was in a state of intoxication.**

So two defences survive: **intentional self-injury and intoxication.**

**§406.033(b)** — the section does not reinstate or otherwise affect the
availability of common law defences generally, including the three it removes.

### What cannot be waived

**§406.033(e)** — **a cause of action under this section may not be waived by
an employee before the employee's injury or death.** Any pre-injury agreement
to waive it is **void and unenforceable.**

A non-subscriber cannot hand new hires a waiver at induction and be done with
it. The examinable shape: **pre-injury waiver void; post-injury settlement is
a different matter.**

## The benefits

Where coverage exists, **Chapter 408** sets what is paid. **§408.081(b)** —
income benefits are paid **weekly as and when they accrue**, without an order
from the commissioner, with interest on accrued but unpaid benefits.

Four kinds of income benefit, and the order runs from the injury to its
permanent consequences.

### Temporary income benefits

**§408.101(a)** — payable where the employee **has a disability and has not
reached maximum medical improvement**.

**§408.102(a)** — TIBs **continue until the employee reaches maximum medical
improvement**. MMI is the hinge the rest of the chapter turns on.

**§408.103(a)** — the amount is:

- **70 percent** of the employee's average weekly wage **less** their weekly
  earnings after the injury; or
- **75 percent** of that difference **for the first 26 weeks**, if the
  employee **earns less than $10 an hour.**

**§408.105** allows **salary continuation** in lieu of TIBs.

### Impairment income benefits

**§408.121(a)** — entitlement begins **the day after the employee reaches
maximum medical improvement**, and ends at the earlier of the employee's death
or the expiry of a period computed at **three weeks for each percentage point
of impairment.**

**§408.126** — the amount is **70 percent of the average weekly wage.**

So a 15 percent impairment rating buys **45 weeks** of IIBs. That arithmetic
is the likely question.

**§408.122** — a claimant may not recover IIBs unless an impairment rating has
been certified. **§408.124** — the rating follows the guidelines that section
adopts.

### Supplemental income benefits

**§408.142(a)** — payable on the expiry of the IIB period where the employee:

1. has an **impairment rating of 15 percent or more**;
2. **has not returned to work, or has returned earning less than 80 percent**
   of their average weekly wage, **as a direct result of the impairment**;
3. **has not elected to commute** a portion of the impairment income benefit;
   and
4. has complied with the requirements adopted under §408.1415.

**§408.142(b)** — an employee not entitled at the time of the final IIB
payment because they were earning at least 80 percent may **become** entitled
within **one year** after the IIB period ends, if they then earn less than 80
percent for at least **90 days** as a direct result of the impairment.

**The 15 percent threshold and the 80 percent earnings test are the two
figures here.**

### Lifetime income benefits

**§408.161(a)** — paid **until the death of the employee** for a closed list
of catastrophic injuries:

- **total and permanent loss of sight in both eyes**;
- **loss of both feet** at or above the ankle;
- **loss of both hands** at or above the wrist;
- **loss of one foot at or above the ankle and one hand at or above the
  wrist**;
- **an injury to the spine resulting in permanent and complete paralysis of
  both arms, both legs, or one arm and one leg**;
- **a physically traumatic brain injury** resulting in a permanent major
  neurocognitive disorder requiring occasional supervision in routine daily
  self-care and rendering the employee permanently unemployable; and
- **third degree burns covering at least 40 percent of the body** and
  requiring grafting, or covering the majority of the relevant areas that
  subsection describes.

**§408.161(b)** — **total and permanent loss of use of a body part is the loss
of that body part.** An unusable hand counts as a lost hand.

**§408.161(c)** — the amount is **75 percent of the average weekly wage**,
**increased at three percent a year.** LIBs are the only income benefit with a
built-in escalator.

### Death and burial

**§408.181(b)** — a death benefit is **75 percent of the average weekly wage**,
paid to the legal beneficiary. It may be paid **monthly** only on the
beneficiary's request, with the carrier's agreement, under rules the
commissioner adopts (§408.181(c)).

**§408.186(a)** — burial benefits are the **lesser of the actual reasonable
burial expenses incurred or $10,000**, paid to whoever incurred the liability.
**§408.186(b)** — where the employee died away from their usual place of
employment, the carrier pays the reasonable cost of **transporting the body**,
not exceeding the cost of transporting it to that usual place.

## The percentages, side by side

| Benefit | Rate | Measured against |
| --- | --- | --- |
| **Temporary income** | **70%** (75% for the first 26 weeks under $10/hr) | AWW **less post-injury earnings** |
| **Impairment income** | **70%** | AWW |
| **Lifetime income** | **75%**, **+3% a year** | AWW |
| **Death** | **75%** | AWW |
| **Burial** | lesser of actual cost or **$10,000** | — |

**70 for the two that are about recovering; 75 for the two that are about not
recovering.** That is the memory hook worth carrying.

## How this is examined

**Coverage is elective in Texas, except for public employers.**

**A non-subscriber loses contributory negligence, assumption of risk and the
fellow servant rule** — but **the employee must still prove the employer was
negligent**, and **intentional self-injury and intoxication remain defences.**

**A pre-injury waiver is void.**

**Three weeks of impairment income per percentage point.**

**15 percent impairment and 80 percent of wages** for supplemental income
benefits.

**Lifetime income benefits are 75 percent with a 3 percent annual increase**,
for the listed catastrophic injuries.

**$10,000** burial cap.

## Check yourself

1. A private Texas employer decides not to carry workers' compensation. Is
   that lawful?
2. An employee of that non-subscriber is injured partly through their own
   carelessness and partly through a supervisor's. What defences are gone, and
   what must the employee still prove?
3. The same non-subscriber shows the employee was drunk at the time. Does that
   help?
4. The employer asks every new hire to sign away the right to sue for
   workplace injury. Is that effective?
5. An employee with a $1,000 average weekly wage reaches MMI with a 20 percent
   impairment rating. How long do impairment income benefits run, and at what
   weekly amount?
6. What two conditions of earnings and impairment open supplemental income
   benefits?
7. An employee loses the total and permanent use of both hands. Which benefit,
   at what rate?
8. A covered employee dies. What is paid for burial?

## Answers

1. **Yes.** §406.002(a) — coverage is elective except for public employers and
   as otherwise provided by law.
2. Gone: **contributory negligence, assumption of risk and the fellow servant
   rule** (§406.033(a)). The employee must still **prove the employer's
   negligence**, or that of an agent or servant acting within the scope of
   employment (§406.033(d)).
3. **Yes.** §406.033(c) preserves two defences — that the employee **intended**
   the injury, or was **intoxicated**.
4. **No.** §406.033(e) — a pre-injury waiver is **void and unenforceable**.
5. **60 weeks** — three weeks per percentage point — at **70 percent** of the
   average weekly wage, so **$700 a week** (§408.121(a), §408.126).
6. An **impairment rating of 15 percent or more**, and **not having returned
   to work or earning less than 80 percent** of the average weekly wage as a
   direct result of the impairment (§408.142(a)).
7. **Lifetime income benefits**, at **75 percent** of the average weekly wage
   with a **three percent annual increase** — §408.161(b) treats total and
   permanent loss of use as loss of the body part.
8. The **lesser of the actual reasonable burial expenses or $10,000**
   (§408.186(a)), plus reasonable transport of the body where the employee
   died away from their usual place of employment.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '8c0f54c3-56b6-5422-8ecc-b77835ded5f3', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
