-- Texas Exam Prep — content seed, chunk 23 of 27
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '18f35c36-92f6-5338-901e-2f125a4954df', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Continuing Education',
       'continuing-education', 'Twenty-four hours, three of them ethics, half of them in a classroom — and the 90-day cliff that ends a licence.', 11,
       'draft', 12
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '18f35c36-92f6-5338-901e-2f125a4954df', c.id, $lesson$# Keeping the licence current

Module 5's renewal lesson gave the two-year term and the cliffs after expiry.
**Chapter 4004 is the other half of renewal: the education that has to happen
inside that term**, and its figures are examined directly.

**§4004.001** — the Department has **exclusive jurisdiction** of all matters
relating to the continuing education of agents licensed under the code. No
other body sets, waives or enforces it.

## The core numbers

**§4004.053(a)** — an individual holding a **general property and casualty
licence** — or a general life, accident and health licence, a life agent
licence, an adjuster licence, a managing general agent licence, or a personal
lines property and casualty licence — must complete **24 hours of continuing
education during the licence period.**

The same subsection settles the question candidates ask next: **holding more
than one licence does not multiply the requirement.** If an individual holds
several licences for which continuing education is required, they are **not
required to complete more than 24 hours for all of them** in the period.

**§4004.054** — of those hours, **three hours must be ethics**, in each
licence renewal period.

**§4004.051(c)** — **at least 50 percent of all required hours must be
completed in a classroom setting or a classroom-equivalent setting approved by
the Department.** On 24 hours that is 12.

**§4004.051(b)** — **all required hours must be completed before the
expiration date** of the licence.

**§4004.053(b)** — a **limited** life, accident and health licence or a
**limited** property and casualty licence carries a different rule: **five
hours annually**, not 24 per period.

> **The shape to hold: 24 hours per two-year period, 3 of them ethics, at
> least 12 in a classroom, all of it before the licence expires.** A limited
> licence is 5 hours a year.

## Exemptions and extensions

**§4004.052(a)** — on the agent's **timely written request**, the Department
may **extend** the time to comply, or **exempt** the agent from some or all of
the requirements for a licensing period, where it determines the agent cannot
comply because of **illness, medical disability, or another extenuating
circumstance beyond the agent's control.** The Commissioner prescribes the
criteria by rule.

**§4004.052(b)** is the one most likely to be asked: **an individual who has
continuously held an agent licence under the code for at least 20 years is
exempt** from the continuing education requirements of the chapter.

**§4004.052(c)** — the Commissioner may provide other reasonable exemptions
by rule.

## Credit for association membership

**§4004.0535** — the Commissioner may by rule authorise the Department to
grant **not more than four hours** of continuing education credit to an agent
who is an **active member of a state or national insurance association.**

Two limits make this narrower than it first looks, and both are examinable.
**§4004.0535(c)** — credit granted under this section may **not** be used to
satisfy:

1. the hours required to be completed **in a classroom** or classroom
   equivalent under §4004.051; or
2. the **ethics** requirement under §4004.054.

So the four hours come off the general balance only. **§4004.0535(d)** — the
agent must give the Department a **sworn affirmation** that they are an active
member and have either reviewed the association's educational materials or
attended its educational presentations, for the hours claimed.

**§4004.051(d)** — separately, the Department **may** accept hours completed
in other professions or in connection with professional designations in an
insurance-related field.

## Failing to complete it

**§4004.055** is short and unforgiving.

**§4004.055(a)** — the Department **may not renew** a licence if the holder
fails to:

1. **complete the applicable requirement not later than the 90th day after
   the last day of the licensing period**; or
2. **pay an applicable fine** related to the failure to complete it on time.

So there is a **90-day window after the period ends** in which the deficiency
can still be cured. Miss that and the licence cannot be renewed at all — which
lands the agent in §4003.007's bands from the renewal lesson.

**§4004.055(b)** — the Department **may not issue a new licence** to somebody
previously licensed who fails to provide evidence of completion for the
expired, non-renewed, cancelled or revoked licence, or to pay the related
fine. **The deficiency follows the person**, not the licence: starting again
does not wash it off.

**§4004.055(c)** — **completing the education after the licence expires is
not a defence** in a disciplinary action under §4005.101, §4005.109 or any
other provision. Catching up cures the renewal obstacle; it does not undo the
violation.

## Programme and provider requirements

**§4004.101–.104** cover certification of programmes, the certification fee,
provider registration, and independent contractors.

**§4004.105** is worth recognising because it names chapters taught elsewhere
in this module: a continuing education programme **for adjusters** licensed
under Chapter 4101 must include education relating to **Chapter 541**,
**Chapter 547**, **Subchapter A of Chapter 542**, and **Subchapter E of
Chapter 17, Business & Commerce Code**.

**§4004.151–.152** — the Department administers the continuing education and
precertification training programmes required by rules under **Chapter 4008**,
the product-line certificate chapter referenced in the discipline lesson.

Later subchapters impose additional education for those selling **annuities**
(§4004.201–.203) and **Medicare-related products** (§4004.251–.252). Neither
is within a general lines property and casualty producer's ordinary work, but
both exist.

## How this is examined

**24 hours**, and that **several licences do not mean more than 24**.

**Three hours of ethics.**

**At least 50 percent in a classroom** or approved equivalent.

**20 years of continuous licensure is an exemption.**

**Four hours maximum** for association membership, and that it counts toward
**neither** the classroom portion **nor** the ethics requirement.

**90 days after the period ends** to cure, or the licence cannot be renewed.

**Completing late is not a defence** to discipline.

## Check yourself

1. An agent holds both a general property and casualty licence and a general
   life, accident and health licence. How many hours must they complete?
2. How many of those must be ethics, and how many must be in a classroom?
3. An agent has held a licence continuously for 22 years. What do they owe?
4. An agent claims four hours for active membership of a state insurance
   association. May those hours satisfy the ethics requirement?
5. An agent's licence period ended on 31 March and they are three hours
   short. Until when can they fix it?
6. An agent completes the missing hours four months after expiry and argues
   there is now no violation. Is that right?

## Answers

1. **24** — §4004.053(a) caps the total at 24 for all licences held, not 24
   each.
2. **Three** hours of ethics (§4004.054), and **at least 12** — 50 percent of
   24 — in a classroom or approved classroom-equivalent setting
   (§4004.051(c)).
3. **Nothing.** §4004.052(b) exempts an individual who has continuously held
   an agent licence for at least 20 years.
4. **No.** §4004.0535(c) bars association credit from satisfying either the
   classroom hours or the ethics requirement.
5. **The 90th day after the last day of the licensing period** — §4004.055(a).
   After that the Department may not renew.
6. **No.** §4004.055(c) — completion after expiry is **not a defence** in a
   disciplinary action. It removes the obstacle to a new licence; it does not
   undo the failure.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '18f35c36-92f6-5338-901e-2f125a4954df', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '70750c55-c337-5ecd-bc9a-4dac927476a3', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'The Property and Casualty Guaranty Association',
       'the-guaranty-association', 'What happens to a claim when the insurer fails — the $300,000 cap, the workers'' compensation exception, and the insured too big to be protected.', 12,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '70750c55-c337-5ecd-bc9a-4dac927476a3', c.id, $lesson$# When the insurer cannot pay

Every other chapter in this module regulates an insurer that exists.
**Chapter 462 answers the question of what happens when one stops existing.**

The Texas Property and Casualty Insurance Guaranty Association pays claims
against an **impaired insurer** — one placed in receivership or otherwise
determined unable to meet its obligations. It is the reason the surplus lines
lesson's warning matters: a surplus lines insurer is **not** a member, so
nothing here stands behind that policy.

## The covered claim

**§462.201** — a claim is a **covered claim** if all five are true:

1. it is an **unpaid** claim;
2. it is made under a policy to which the chapter applies, **issued by an
   insurer authorized to engage in business in this state** (or assumed by
   one under an assumption certificate);
3. it **arises out of the policy and is within the coverage and applicable
   limits** of the policy;
4. the issuing or assuming insurer **is an impaired insurer**; and
5. it is made by a **liability claimant or insured who is a resident of this
   state at the time of the insured event**, or is a **first-party claim for
   damage to property permanently located in this state.**

Two consequences follow from (3) and (5). **The association never pays more
than the policy would have** — it steps into the insurer's shoes, not above
them. And **residency or Texas-located property is the hook**: an out-of-state
claimant on an out-of-state risk is another state's association's problem.

**§462.205** — a corporation or other non-individual entity is a resident of
**the state where its principal place of business is located.**

**§462.204** — **an affiliate of the impaired insurer may not be a claimant.**

## The limits

This is the examined part of the chapter.

**§462.213(a)** — except as provided by subsection (b) and §462.252, **an
individual covered claim may not exceed $300,000.**

**§462.213(b)** is the exception that matters: **the association shall pay the
full amount of a covered claim arising out of a workers' compensation claim
made under a workers' compensation insurance policy.** No $300,000 cap on
workers' compensation.

That pairing is the reliable question. **Everything else is capped at
$300,000; workers' compensation is paid in full.**

**§462.213(c)** closes the obvious route around the cap: **derivative claims
by more than one person arising from the same occurrence are considered
collectively as a single claim.** Three family members claiming from one
accident share one $300,000 limit, not three.

**§462.202(a)** — **a claim for unearned premium is a covered claim, and may
not exceed $25,000.** So a policyholder whose insurer fails mid-term recovers
the unused premium, within its own much smaller cap.

**§462.214** — the association's liability for **shareholder derivative
actions**, or other claims for economic loss incurred in the claimant's
capacity as a shareholder, under a policy in force on or after 1 January 1992,
is limited to **$300,000 for each policy, including defence costs, regardless
of the number of claimants.**

## The insured too large to be protected

**§462.212** — **except for a workers' compensation claim governed by Title 5,
Labor Code**, a covered claim **does not include** any claim arising from the
policy of an insured **whose net worth exceeded $50 million** on 31 December
of the year preceding the date the insurer became impaired.

The reasoning is that the association exists to protect people who cannot
absorb an insurer's failure, and a company of that size can. Two details:

- **Net worth is measured on a consolidated basis**, including the insured's
  **parent, subsidiary and affiliated companies**.
- If the insured **refuses to provide** the financial information the
  association requests, the association **may deem the net worth to exceed
  $50 million** — and in any lawsuit contesting the point, **the insured bears
  the burden of proof** and pays the association's costs and reasonable
  attorney's fees incurred in trying to get the information.

**Workers' compensation is carved out of this too.** It is carved out of the
cap in §462.213(b) and out of the net worth exclusion in §462.212. An injured
worker's statutory benefits do not depend on how large their employer is.

## Funding

**§462.151 onwards** — the association is funded by **assessments on member
insurers**, in the manner provided by §§462.159–462.168. Membership is not
optional; it is the industry insuring itself against its own failures, the
same structure as TWIA and the FAIR Plan.

**§462.160 and §462.168** — **the total assessment of a member insurer in a
year may not exceed two percent of that insurer's net direct written premiums
for the preceding calendar year**, in the lines for which the assessment is
made.

**§462.157(c)** — an assessment for administrative expenses incurred by a
supervisor, conservator or court-appointed receiver for a **nonmember or
unauthorized insurer** operating in Texas **may not exceed $1 million in each
calendar year.**

**§462.109** — where a member insurer fails to pay an assessment when due, the
Commissioner may as an alternative **assess a fine**, not exceeding the
**lesser of five percent of the unpaid assessment per month or $100 per
month.**

## Related provisions

**§462.203** — an **administration expense** incurred in processing or paying
a claim against the receivership or conservatorship estate is itself a covered
claim where the impaired insurer has insufficient assets to pay the costs of
administering the estate.

**§462.254** — where a claim could be recovered from more than one state's
guaranty association, the claimant seeks recovery **first from the association
of the insured's residence**; a **first-party property** claim goes first to
the association **where the property is located**, and a **workers'
compensation** claim first to the association of **the claimant's residence**.
That allocates between states rather than letting a claimant choose.

**§462.308** — the association may **recover** what it paid from an
**affiliate of the impaired insurer** whose liabilities were satisfied by its
payments, and from certain insureds on workers' compensation claims — but
**not** from an insured exempt from federal income tax under §501(c)(3).

## How this is examined

**$300,000** as the individual covered claim cap.

**Workers' compensation is paid in full**, with no cap — and is also outside
the net worth exclusion.

**$25,000** for unearned premium.

**$50 million net worth** excludes an insured, measured on a consolidated
basis.

**Derivative claims from one occurrence are one claim.**

**Two percent** of net direct written premiums as the annual assessment cap.

**Surplus lines insurers are not members**, so nothing stands behind a surplus
lines policy — the link back to Chapter 981.

## Check yourself

1. An insurer fails. A homeowner has a $450,000 covered fire claim within the
   policy limit. What does the association pay?
2. The same insurer wrote a workers' compensation policy, and an injured
   worker's benefits will exceed $300,000 over their lifetime. What is paid?
3. Three members of one family are injured in a single accident and each
   claims $200,000 against an impaired insurer's liability policy. What is
   available in total?
4. A company with a consolidated net worth of $80 million has a covered
   property claim against an impaired insurer. What does the association pay?
5. Same company, but the claim is under its workers' compensation policy.
   Does the answer change?
6. A policyholder paid a year's premium and the insurer fails after two
   months. Can they recover the unused portion, and up to how much?
7. A business insured through a surplus lines insurer that becomes insolvent
   asks the association to pay. Will it?

## Answers

1. **$300,000** — §462.213(a) caps an individual covered claim, even though
   the policy would have paid more.
2. **The full amount.** §462.213(b) — workers' compensation covered claims are
   paid in full, with no $300,000 cap.
3. **$300,000 in total.** §462.213(c) treats derivative claims arising from
   the same occurrence collectively as a single claim.
4. **Nothing.** §462.212 excludes claims arising from the policy of an insured
   whose net worth exceeded **$50 million**, measured on a consolidated basis
   including parent, subsidiary and affiliates.
5. **Yes.** Workers' compensation is expressly carved out of the net worth
   exclusion, so those benefits are still covered — and uncapped.
6. **Yes** — a claim for unearned premium is a covered claim, up to
   **$25,000** (§462.202(a)).
7. **No.** A surplus lines insurer is not a member of the association, and
   §981.101(b) requires the surplus lines document to say so in 11-point type.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '70750c55-c337-5ecd-bc9a-4dac927476a3', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
