-- Texas Exam Prep — content seed, chunk 25 of 26
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '3de21720-971c-500c-a78f-355ca91d23ef', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Company Types and Certificates of Authority',
       'company-types-and-authority', 'Admitted and non-admitted, domestic foreign and alien, and the Lloyd''s plan that is not Lloyd''s of London.', 16,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '3de21720-971c-500c-a78f-355ca91d23ef', c.id, $lesson$# Which insurers Texas lets you place business with

Two independent questions, and candidates blur them constantly.

**Where is the insurer organised?** Domestic, foreign or alien.

**Has Texas authorised it?** Admitted or non-admitted.

**They do not track each other.** A foreign insurer can be admitted; a
domestic one can lose its authority. The first question is about origin, the
second about permission.

## Domestic, foreign and alien

**Domestic** — organised under the laws of **this state**. Texas is its home.

**Foreign** — organised under the laws of **another state** of the United
States.

**Alien** — **§982.001(2)**: an insurance company **organised under the laws of
a foreign country.**

The trap is that "foreign" sounds like it should mean overseas. **In insurance
it means another state; overseas is alien.** An insurer from Oklahoma is
foreign in Texas; an insurer from Ontario is alien.

**§982.002** — Chapter 982 applies to **any insurance company organised under
the laws of another state or country** that wants to engage in, or is engaging
in, the business of insurance in Texas. So the chapter covers foreign and
alien together — everything that is not domestic.

**§982.004** — each **foreign** company must file an annual statement with the
Department **not later than 1 March** each year, and each **authorized alien**
company must file a financial statement by the same date.

## What "insurer" covers — the company types

**§801.001(2)** gives the taxonomy the blueprint asks for at TX.I.B.4, and it
is wider than most candidates expect. **"Insurer"** means the issuer of a
policy issued for a premium, insuring against a loss that may be insured
against under the law — and the term **includes**:

- a **fraternal benefit society**;
- a **Lloyd's plan**;
- a **mutual company of any kind**, including a **statewide mutual assessment
  association**, a **local mutual aid or burial association**, and a **county
  or farm mutual** insurance company;
- a **reciprocal or interinsurance exchange**;
- a **group hospital service corporation**; and
- a **health maintenance organization**, among the others that subsection
  lists.

Two things follow. **A "mutual company of any kind"** sweeps in the county and
farm mutuals that Chapter 542's and Chapter 2203's lists name separately — so
when a statute carves out county and farm mutuals, it is carving out a subset
of this definition. And the **capital stock company**, the ordinary
shareholder-owned insurer, is the implicit contrast: **a stock company is owned
by shareholders and earns profit for them; a mutual is owned by its
policyholders**, who are its members.

**§547.001** adds the other half of the vocabulary, defining **"alien or
foreign insurer"** as one organised under the laws of a country other than the
United States **or** a state other than this one — which is the same
distinction §982.001 draws, from the other direction.

## Transacting insurance

**§101.051(b)** — the acts that **constitute the business of insurance in this
state**, which is what makes an unauthorised insurer's conduct unlawful. They
include:

1. **making or proposing to make, as an insurer, an insurance contract**;
2. **making or proposing to make, as guarantor or surety, a guaranty or
   suretyship contract** as a vocation rather than incidentally;
3. **taking or receiving an insurance application**;
4. **receiving** premium or consideration, and the further acts that
   subsection lists.

The point for a producer: **"transacting insurance" starts long before a policy
issues.** Taking an application is enough.

## Admitted and non-admitted

**An admitted (authorized) insurer holds a certificate of authority from the
Department. A non-admitted (unauthorized) insurer does not.**

**§801.052** — a certificate of authority **authorizes the insurer to engage in
the business of insurance**, and **must state the specific kinds of insurance
authorized under it.** An insurer authorised for property is not thereby
authorised for life.

**§801.051(a)–(b)** — the Department **shall approve, deny or disapprove** an
application, and **shall** approve and issue the certificate under its seal
where the applicant has complied with the law.

**§801.053** — **a certificate of authority is effective until it is suspended
or revoked.** It does not expire and is not renewed annually, which is the
opposite of an agent's licence and is therefore examinable.

**§801.054** — in issuing a certificate, the Department **shall give preference
to an application submitted by a domestic company.**

**§801.057** — failure to file the annual statement has consequences under that
section; **§801.056** deals with failure to provide a complete set of
fingerprints. **§801.102** covers **denial of an application or revocation of a
certificate**, and **§801.151–.154** the circumstances in which issuance is
prohibited, a certificate is revoked, and a petition for issuance or
reinstatement may be made and granted.

### Why it matters to a producer

Three consequences run through the rest of this module:

- **The guaranty association covers only authorized insurers.** §462.201(2)
  requires the policy to have been issued by an insurer **authorized to engage
  in business in this state**. Place business with a non-admitted insurer and
  **nothing stands behind it** if the insurer fails.
- **Surplus lines is the regulated route to a non-admitted insurer** —
  Chapter 981 — and it exists precisely because unauthorised insurers are
  otherwise off limits.
- **Chapter 101** governs unauthorised insurers generally, and the emergency
  cease and desist power in **§83.051** reaches an unauthorized person engaging
  in the business of insurance in violation of it.

## False advertising by unauthorized insurers

**Chapter 547** sits alongside this and is short.

**§547.051** — **acts prohibited**: it governs what an unauthorized insurer
may not do by way of advertising in this state.

**§547.052** — the Department gives **notice of a violation to the insurer's
domiciliary state**, which is how a regulator reaches an insurer it does not
license.

**§547.053** — **enforcement action.**

It is also one of the chapters **§4004.105** requires an **adjuster's**
continuing education programme to cover.

## The Lloyd's plan

**§941.003** and the definitions in **§941.001** describe a form of insurer
unfamiliar outside Texas, and one the exam likes because its structure is
unusual.

**§941.001(3)** — a **"Lloyd's plan"** is an entity **engaged in the business
of writing insurance on the Lloyd's plan.**

**§941.001(4)** — an **"underwriter"** is an **individual, partnership, or
association of individuals** that writes insurance on the Lloyd's plan.

**§941.001(2)** — an **"attorney in fact"** is an attorney in fact **authorized
under a power of attorney to act for the underwriters** of a Lloyd's plan.

So the shape is: **individual underwriters, each liable for their own share,
acting through an attorney in fact.** That is the same idea as Lloyd's of
London — but **a Texas Lloyd's plan is a Texas entity under Chapter 941, not a
branch of Lloyd's of London.** Confusing the two is the standard error.

**§941.002** — Lloyd's plan insurance is **authorized**, with a **life
insurance prohibition** as that section describes. **§941.003** gives a
**limited exemption from the insurance laws** and states which chapters still
apply. **§941.004** covers **withdrawal from the business of insurance**.
**§941.051–.054** cover **formation**, the **attorney in fact**, a **deputy or
substitute attorney in fact**, and the **name** of the plan.

A Lloyd's plan is a **member of the guaranty association's covered insurer
list** — §462 and §542.052 both name Lloyd's plans among the insurers they
reach — and **§542A.001(4)** names a Lloyd's plan among the insurers that
chapter applies to.

## Reciprocals and exchanges

Not a downloaded chapter, but named repeatedly by chapters that are.
**§541.002(2)**, **§542.052** and **§542A.001(4)** all list a **reciprocal or
interinsurance exchange** alongside stock and mutual companies, county
mutuals, farm mutuals and Lloyd's plans. Recognise the term: **subscribers
insuring each other through an attorney in fact**, which is why it sits next
to the Lloyd's plan in every list.

## How this is examined

**Foreign means another state; alien means another country** — §982.001(2) and
§547.001 both.

**"Insurer" in §801.001(2) includes a mutual company of any kind**, a Lloyd's
plan, a reciprocal and a fraternal benefit society. **A stock company is owned
by shareholders; a mutual by its policyholders.**

**Taking an application is already transacting insurance** — §101.051(b).

**Admitted means holding a certificate of authority** — independent of where
the insurer was organised.

**A certificate of authority runs until suspended or revoked**, and **states
the specific kinds of insurance** authorised.

**The Department gives preference to a domestic applicant.**

**Only authorized insurers are behind the guaranty association** — which is
why a surplus lines policy has nothing behind it.

**A Texas Lloyd's plan is not Lloyd's of London**: individual underwriters
acting through an **attorney in fact**, under Chapter 941.

## Check yourself

1. An insurer organised in Louisiana writes in Texas. Domestic, foreign or
   alien?
2. An insurer organised in Bermuda writes in Texas. Which of the three?
3. Does holding a certificate of authority tell you where an insurer was
   organised?
4. When does a certificate of authority expire?
5. Two applications are equal on the merits, one from a domestic company and
   one from a foreign company. What does §801.054 require?
6. A client's insurer is non-admitted and becomes insolvent. Is the guaranty
   association available?
7. What is an attorney in fact, and which two kinds of insurer use one?

## Answers

1. **Foreign** — organised under the laws of **another state**.
2. **Alien** — organised under the laws of a **foreign country**
   (§982.001(2)).
3. **No.** The certificate is about **permission to do business in Texas**;
   domestic, foreign and alien is about **where it was organised**. A foreign
   insurer can be admitted and a domestic one can lose its authority.
4. **It does not.** §801.053 — it is effective **until suspended or revoked**.
5. **Preference to the domestic company's application.**
6. **No.** §462.201(2) requires a policy issued by an insurer **authorized to
   engage in business in this state**. Surplus lines is the regulated route to
   a non-admitted insurer, and §981.101(b) requires the document to warn that
   there is no guaranty association behind it.
7. Someone **authorized under a power of attorney to act for the
   underwriters** (§941.001(2)). A **Lloyd's plan** uses one, and so does a
   **reciprocal or interinsurance exchange**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '3de21720-971c-500c-a78f-355ca91d23ef', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
