-- Texas Exam Prep — Phase 3 schema
--
-- Generated by scripts/build-deploy-sql.mjs. Do not edit by hand; edit the
-- migrations in supabase/migrations/ and regenerate.
--
-- Run this ONCE against a project that already has the Phase 2 schema.
-- These statements are not idempotent: running them twice fails on an
-- existing type or table, which is the correct behaviour, not a bug.
--
-- ONE TRANSACTION PER MIGRATION, NOT ONE FOR THE FILE.
--
-- This phase adds a value to an enum type, and PostgreSQL will not
-- let a new enum value be used in the transaction that added it. The
-- whole file therefore cannot be atomic.
--
-- So a failure part-way leaves the migrations BEFORE it applied and
-- the rest not. That is recoverable but it is not nothing: note
-- which migration failed, fix the cause, and resume from that one
-- using supabase/deploy/steps/ rather than re-running this file.
--   - 20260301000000_assessment_types.sql
--   - 20260301000100_questions.sql
--   - 20260301000200_question_answers.sql
--   - 20260301000300_question_grants.sql
--   - 20260301000400_attempts.sql
--   - 20260301000500_attempt_grants.sql
--   - 20260301000600_scoring.sql
--   - 20260301000700_attempt_kind_module.sql
--   - 20260301000710_module_attempts.sql
--   - 20260301000800_start_attempt.sql

-- --------------------------------------------------------------------------
-- 20260301000000_assessment_types.sql
-- --------------------------------------------------------------------------

begin;

-- Phase 3 enums.
--
-- Kept separate from content_status and course_status for the same reason
-- those were kept apart from each other: a question's lifecycle and a course's
-- lifecycle are different things that happen to share vocabulary today, and
-- merging them means every future value added for one is silently offered to
-- the other.

-- How a student is practising. This drives the draw, the reveal rule and
-- whether the attempt counts toward readiness.
create type public.attempt_kind as enum (
  'mock',   -- 130 scored questions to the blueprint's counts; the measurement
  'quiz',   -- a handful on one lesson's topic
  'drill'   -- one topic, as many as asked for
);

-- When the student is allowed to learn whether they were right.
create type public.reveal_mode as enum (
  'immediate',  -- after each answer; study, not measurement
  'on_submit'   -- after the whole attempt, like the real exam
);

comment on type public.attempt_kind is
  'mock/quiz/drill. Only mock counts toward readiness, and only mock is drawn '
  'to the published blueprint counts.';

comment on type public.reveal_mode is
  'When is_correct may be written and read. A mock is always on_submit, '
  'enforced by a check constraint on attempts, because a mock scored with '
  'instant feedback measures nothing.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000100_questions.sql
-- --------------------------------------------------------------------------

begin;

-- Questions and their options.
--
-- THE CORRECT ANSWER IS NOT IN EITHER OF THESE TABLES. It lives in
-- question_answers, which no browser role may read. See
-- docs/phase-3-design.md.

create table public.questions (
  id          uuid primary key default gen_random_uuid(),
  course_id   uuid not null references public.courses (id) on delete cascade,

  -- Which blueprint topic this question tests. Required: a question that is
  -- not tagged cannot be drawn into a paper, so an untagged question is a
  -- question that does not exist as far as the product is concerned.
  topic_id    uuid not null,

  -- The lesson this question follows from, where there is one. Nullable
  -- because a mock question need not belong to any single lesson.
  lesson_id   uuid,

  stem        text not null,

  -- Shown only once the answer may be revealed. This is where the teaching
  -- happens: "the policy pays $74,000 because coinsurance applies before the
  -- deductible" is worth more than the mark.
  explanation text,

  status      public.content_status not null default 'draft',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- The composite foreign keys make the denormalised course_id provably
  -- consistent with the parents, rather than consistent by convention and a
  -- trigger. They also make it structurally impossible to tag a question with
  -- a topic from another course.
  constraint questions_topic_fk
    foreign key (topic_id, course_id)
    references public.topics (id, course_id) on delete cascade,
  constraint questions_lesson_fk
    foreign key (lesson_id, course_id)
    references public.lessons (id, course_id) on delete set null,

  constraint questions_stem_not_blank check (btrim(stem) <> ''),
  constraint questions_id_course_key unique (id, course_id)
);

create index questions_course_topic_idx
  on public.questions (course_id, topic_id) where status = 'active';
create index questions_lesson_idx on public.questions (lesson_id);

create trigger questions_set_updated_at
  before update on public.questions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------

create table public.question_options (
  id          uuid primary key default gen_random_uuid(),
  question_id uuid not null,
  course_id   uuid not null references public.courses (id) on delete cascade,
  body        text not null,

  -- Display order. NOT the answer: option 1 is no more likely to be correct
  -- than option 4, and nothing in the schema encodes otherwise.
  position    integer not null,

  constraint question_options_question_fk
    foreign key (question_id, course_id)
    references public.questions (id, course_id) on delete cascade,
  constraint question_options_body_not_blank check (btrim(body) <> ''),
  constraint question_options_position_positive check (position between 1 and 10),
  constraint question_options_question_position_key unique (question_id, position),
  constraint question_options_id_question_key unique (id, question_id)
);

create index question_options_question_idx
  on public.question_options (question_id, position);

comment on table public.questions is
  'Question stems. The correct answer is NOT here; see question_answers.';
comment on table public.question_options is
  'The options a student picks between. Deliberately carries no is_correct '
  'column: RLS filters rows and grants filter columns, and neither can hide '
  'one column of a row the caller is otherwise allowed to read. The answer '
  'therefore lives in a different table with different grants.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000200_question_answers.sql
-- --------------------------------------------------------------------------

begin;

-- The answer key.
--
-- This is the table the whole Phase 3 design exists to protect. Read
-- docs/phase-3-design.md before changing anything here.
--
-- The rule: NO browser role may read this table, by any route, ever. Not
-- through a policy, not through a view, not through an embedded PostgREST
-- resource. The only things that touch it are SECURITY DEFINER functions that
-- check the caller's identity first.

create table public.question_answers (
  -- One answer per question, so the question id IS the primary key. A
  -- separate surrogate key would permit two answer rows for one question,
  -- which is a state with no correct interpretation.
  question_id       uuid primary key,
  course_id         uuid not null references public.courses (id) on delete cascade,
  correct_option_id uuid not null,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint question_answers_question_fk
    foreign key (question_id, course_id)
    references public.questions (id, course_id) on delete cascade,

  -- The correct option must belong to THIS question. Without the composite
  -- reference, an answer key could point at an option of some other question
  -- and every attempt at this one would be marked wrong, with nothing in the
  -- schema objecting.
  constraint question_answers_option_fk
    foreign key (correct_option_id, question_id)
    references public.question_options (id, question_id) on delete cascade
);

create trigger question_answers_set_updated_at
  before update on public.question_answers
  for each row execute function public.set_updated_at();

alter table public.question_answers enable row level security;

-- Belt: no privilege at all for the API roles. A missing grant fails before
-- RLS is even consulted, so `select * from question_answers` with a browser
-- token is a permission error rather than an empty result. The difference
-- matters: an empty result invites someone to go looking for the filter.
revoke all on table public.question_answers from anon, authenticated;

-- Braces: RLS is on and there is NO policy for anon or authenticated. A table
-- with RLS enabled and no matching policy denies everything. Either mechanism
-- alone is sufficient; both are present because this is the one table where
-- being wrong is unrecoverable -- a leaked answer key cannot be un-leaked.
--
-- Note what is NOT here: no `question_answers_select_admin` policy. An admin
-- who needs to see the key uses the admin tooling, which runs its own checks;
-- adding a policy here would mean a single mistake in is_admin() exposes the
-- whole bank. Admin writes go through the importer, which connects as the
-- migration role.

comment on table public.question_answers is
  'The answer key. No grant to anon or authenticated, RLS on with no policy '
  'for them. Reached only by SECURITY DEFINER functions that verify the '
  'caller owns the attempt being scored. Never expose this through a view, a '
  'policy, or a PostgREST embed.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000300_question_grants.sql
-- --------------------------------------------------------------------------

begin;

-- Grants and policies for the readable half of the question bank.
--
-- Same posture as Phase 2: revoke Supabase's default blanket grants, then
-- grant back exactly what each role needs, then let RLS decide the rows.

alter table public.questions        enable row level security;
alter table public.question_options enable row level security;

revoke all on table public.questions        from anon, authenticated;
revoke all on table public.question_options from anon, authenticated;

-- Students read questions and options. They never write either: an attempt
-- records an answer in attempt_questions, it does not modify the bank.
grant select on table public.questions        to authenticated;
grant select on table public.question_options to authenticated;

-- Nothing for anon. Unlike the course syllabus, which is public marketing,
-- the question bank is the product. An anonymous visitor gets none of it --
-- not even the stems, which are most of the value and the easiest thing to
-- scrape.

-- ---------------------------------------------------------------------------

-- A question is visible when it is published AND its parent course is active
-- AND the reader holds a live enrollment. The whole chain is checked, so
-- archiving a course hides its questions without anyone cascading by hand.
create policy questions_select_enrolled
  on public.questions
  for select
  to authenticated
  using (
    status = 'active'::public.content_status
    and exists (
      select 1 from public.courses c
       where c.id = questions.course_id
         and c.status = 'active'::public.course_status
    )
    and public.is_enrolled_in_course(course_id)
  );

create policy questions_select_admin
  on public.questions for select to authenticated
  using (public.is_admin());

create policy questions_insert_admin
  on public.questions for insert to authenticated
  with check (public.is_admin());
create policy questions_update_admin
  on public.questions for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy questions_delete_admin
  on public.questions for delete to authenticated
  using (public.is_admin());

-- Options follow their question exactly. Expressed as a lookup against
-- questions rather than repeating the conditions, so the two can never drift:
-- if the question is invisible the option is invisible, by construction.
create policy question_options_select_visible_question
  on public.question_options
  for select
  to authenticated
  using (
    exists (
      select 1 from public.questions q where q.id = question_options.question_id
    )
  );

create policy question_options_insert_admin
  on public.question_options for insert to authenticated
  with check (public.is_admin());
create policy question_options_update_admin
  on public.question_options for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy question_options_delete_admin
  on public.question_options for delete to authenticated
  using (public.is_admin());

comment on policy question_options_select_visible_question
  on public.question_options is
  'An option is visible exactly when its question is. The EXISTS re-enters '
  'the questions table, so the questions policy does the work and there is '
  'one place to change the rule rather than two that must agree.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000400_attempts.sql
-- --------------------------------------------------------------------------

begin;

-- Attempts: one student sitting one paper.

create table public.attempts (
  id           uuid primary key default gen_random_uuid(),
  student_id   uuid not null references public.profiles (id) on delete cascade,
  course_id    uuid not null references public.courses (id) on delete cascade,

  kind         public.attempt_kind not null,
  reveal       public.reveal_mode  not null,

  -- The topic a drill is confined to, and the lesson a quiz follows. Both
  -- null for a mock, which spans everything.
  topic_id     uuid,
  lesson_id    uuid,

  started_at   timestamptz not null default now(),
  submitted_at timestamptz,

  -- Written only at submission, by score_attempt(). Null on an attempt in
  -- progress, which is also how "has this been scored?" is answered.
  correct_count  integer,
  question_count integer not null,

  -- Stamped so a stored result keeps the meaning it had when it was made.
  -- If READY_THRESHOLD ever moves, old attempts are not silently
  -- reinterpreted against the new bar.
  scale_version  integer not null default 1,

  -- A mock is ALWAYS revealed at the end. Enforced here rather than in the
  -- UI because readiness is computed from mock attempts: if the client could
  -- choose, the readiness figure would quietly change meaning depending on a
  -- radio button the student ticked.
  constraint attempts_mock_is_on_submit check (
    kind <> 'mock'::public.attempt_kind
    or reveal = 'on_submit'::public.reveal_mode
  ),

  -- A drill is about one topic; a mock is about all of them.
  constraint attempts_drill_has_topic check (
    (kind = 'drill'::public.attempt_kind) = (topic_id is not null)
  ),
  constraint attempts_mock_has_no_lesson check (
    kind <> 'mock'::public.attempt_kind or lesson_id is null
  ),

  constraint attempts_question_count_positive check (question_count between 1 and 200),
  constraint attempts_correct_within_total check (
    correct_count is null
    or correct_count between 0 and question_count
  ),
  -- A score without a submission, or a submission without a score, is a
  -- half-written attempt. Neither is a state the reader should have to handle.
  constraint attempts_scored_iff_submitted check (
    (submitted_at is null) = (correct_count is null)
  ),

  constraint attempts_topic_fk foreign key (topic_id, course_id)
    references public.topics (id, course_id) on delete cascade,
  constraint attempts_lesson_fk foreign key (lesson_id, course_id)
    references public.lessons (id, course_id) on delete set null,
  constraint attempts_id_student_key unique (id, student_id)
);

create index attempts_student_recent_idx
  on public.attempts (student_id, course_id, submitted_at desc nulls last);

-- ---------------------------------------------------------------------------

create table public.attempt_questions (
  attempt_id         uuid not null,
  student_id         uuid not null,
  question_id        uuid not null references public.questions (id) on delete cascade,
  position           integer not null,

  selected_option_id uuid references public.question_options (id) on delete set null,
  answered_at        timestamptz,

  -- THE ONE-BIT LEAK.
  --
  -- This column IS the answer, disclosed one question at a time. A student
  -- who answers, reads is_correct, and reconsiders has defeated the entire
  -- design -- the answer key stayed secret and told them anyway.
  --
  -- So it stays NULL until the reveal is allowed: written at submission for
  -- a mock or an on_submit attempt, and per answer only in immediate mode,
  -- where showing it is the whole point. score_attempt() is what writes it;
  -- nothing else may.
  is_correct         boolean,

  primary key (attempt_id, question_id),

  constraint attempt_questions_attempt_fk
    foreign key (attempt_id, student_id)
    references public.attempts (id, student_id) on delete cascade,
  constraint attempt_questions_position_positive check (position between 1 and 200),
  constraint attempt_questions_answered_iff_selected check (
    (selected_option_id is null) = (answered_at is null)
  ),
  constraint attempt_questions_attempt_position_key unique (attempt_id, position)
);

create index attempt_questions_question_idx
  on public.attempt_questions (question_id);

comment on column public.attempt_questions.is_correct is
  'Null until the answer may be revealed. Written by score_attempt() only. '
  'Populating it earlier would leak the answer key one bit at a time.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000500_attempt_grants.sql
-- --------------------------------------------------------------------------

begin;

-- Grants and policies for attempts.
--
-- Attempts are the first Phase 3 rows a student WRITES, so the posture is the
-- inverse of the question bank: they own their attempts and may create and
-- answer them, but they may not mark them.

alter table public.attempts          enable row level security;
alter table public.attempt_questions enable row level security;

revoke all on table public.attempts          from anon, authenticated;
revoke all on table public.attempt_questions from anon, authenticated;

grant select, insert on table public.attempts to authenticated;
grant select, insert, update on table public.attempt_questions to authenticated;

-- No UPDATE on attempts, and no DELETE on either.
--
-- A student cannot alter an attempt after creating it: not the kind, not the
-- reveal mode, and above all not correct_count. Scoring happens inside
-- score_attempt(), which runs as the owner and is therefore unaffected by
-- these grants. A student who could update attempts could simply write
-- themselves a perfect score, and readiness would mean nothing.
--
-- No DELETE, because "unlimited retakes with readiness from recent
-- performance" only holds if the record of recent performance cannot be
-- curated. Deleting the bad attempts and keeping the good ones is the same
-- as cheating, done slowly.

create policy attempts_select_own
  on public.attempts for select to authenticated
  using (student_id = (select auth.uid()));

create policy attempts_insert_own
  on public.attempts for insert to authenticated
  with check (
    student_id = (select auth.uid())
    and public.is_enrolled_in_course(course_id)
    -- An attempt cannot be born already scored.
    and submitted_at is null
    and correct_count is null
  );

create policy attempts_select_admin
  on public.attempts for select to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------

create policy attempt_questions_select_own
  on public.attempt_questions for select to authenticated
  using (student_id = (select auth.uid()));

create policy attempt_questions_insert_own
  on public.attempt_questions for insert to authenticated
  with check (
    student_id = (select auth.uid())
    -- Cannot be inserted pre-marked.
    and is_correct is null
  );

-- A student may record or change their selection while the attempt is open.
-- They may not touch is_correct: the WITH CHECK requires it to stay null,
-- and score_attempt() -- running as the owner -- is what fills it in.
create policy attempt_questions_update_own_unsubmitted
  on public.attempt_questions for update to authenticated
  using (
    student_id = (select auth.uid())
    and exists (
      select 1 from public.attempts a
       where a.id = attempt_questions.attempt_id
         and a.submitted_at is null
    )
  )
  with check (
    student_id = (select auth.uid())
    and is_correct is null
  );

create policy attempt_questions_select_admin
  on public.attempt_questions for select to authenticated
  using (public.is_admin());

comment on policy attempt_questions_update_own_unsubmitted
  on public.attempt_questions is
  'Answering and changing an answer, while the attempt is open. The WITH '
  'CHECK pins is_correct to null so a student cannot mark their own paper; '
  'score_attempt() writes it with owner rights. The submitted_at test is '
  'what stops an answer being changed after the score is known.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000600_scoring.sql
-- --------------------------------------------------------------------------

begin;

-- Scoring.
--
-- public.score_attempt(uuid) -> table
--
-- SECURITY DEFINER, and the second deliberate one in this project.
--
-- The Phase 1 post-mortem established that SECURITY DEFINER must be
-- JUSTIFIED, not assumed: it had been used reflexively on a function that did
-- not need it, and the rebinding of current_user it causes turned a security
-- trigger into a silent no-op. is_admin() is the only other one, and it
-- exists to break RLS recursion on profiles.
--
-- The justification here is direct and has no alternative. The caller must be
-- able to CAUSE a comparison against question_answers -- a table they may not
-- read, by design, and which this app has no service-role key to read on
-- their behalf. Definer rights are exactly the mechanism for "let the caller
-- trigger something they cannot do themselves", and the whole value of the
-- design is that the comparison happens where the student is not.
--
-- The obligations that come with it, all discharged below:
--   1. Verify the caller owns the attempt. FIRST, before anything else. A
--      definer function that skips its own authorisation is strictly worse
--      than no function, because it hands every caller the owner's rights.
--   2. Refuse an already-submitted attempt, so a score cannot be rewritten.
--   3. Never return the correct option id. It returns counts, not the key.
--   4. search_path pinned, so nothing is resolved through a schema the
--      caller controls.

create or replace function public.score_attempt(p_attempt_id uuid)
returns table (
  question_count integer,
  correct_count  integer,
  percentage     numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_student uuid;
  v_total   integer;
  v_correct integer;
begin
  -- (1) Authorisation, before anything else.
  --
  -- Note this reads attempts directly: as a definer function it bypasses RLS,
  -- so the ownership test here IS the access control rather than a
  -- convenience on top of it.
  select a.student_id into v_student
    from public.attempts a
   where a.id = p_attempt_id
     and a.submitted_at is null;   -- (2) refuse a re-score

  if v_student is null then
    -- Deliberately one message for three different situations: no such
    -- attempt, somebody else's attempt, and already submitted. Telling them
    -- apart would let a caller enumerate other students' attempt ids by
    -- watching which error comes back.
    raise exception 'attempt not found, not yours, or already submitted'
      using errcode = 'insufficient_privilege';
  end if;

  if v_student <> (select auth.uid()) then
    raise exception 'attempt not found, not yours, or already submitted'
      using errcode = 'insufficient_privilege';
  end if;

  -- Mark every answered question. The join to question_answers is the reason
  -- this function exists.
  update public.attempt_questions aq
     set is_correct = (aq.selected_option_id = ans.correct_option_id)
    from public.question_answers ans
   where aq.attempt_id = p_attempt_id
     and ans.question_id = aq.question_id
     and aq.selected_option_id is not null;

  -- Unanswered questions are wrong, not excluded. Scoring only what was
  -- attempted would let a student skip everything they were unsure of and
  -- report 100%.
  update public.attempt_questions aq
     set is_correct = false
   where aq.attempt_id = p_attempt_id
     and aq.selected_option_id is null;

  select count(*), count(*) filter (where aq.is_correct)
    into v_total, v_correct
    from public.attempt_questions aq
   where aq.attempt_id = p_attempt_id;

  update public.attempts a
     set submitted_at   = now(),
         correct_count  = v_correct,
         question_count = v_total
   where a.id = p_attempt_id;

  -- (3) Counts only. The correct option ids are never returned from here.
  return query
    select v_total,
           v_correct,
           case when v_total > 0
                then round((v_correct::numeric * 100) / v_total, 2)
                else null end;
end;
$$;

revoke all on function public.score_attempt(uuid) from public;
grant execute on function public.score_attempt(uuid) to authenticated;

comment on function public.score_attempt(uuid) is
  'Submits and marks an attempt. SECURITY DEFINER because the caller must be '
  'able to cause a comparison against question_answers, which they may not '
  'read. Verifies ownership first, refuses an already-submitted attempt, and '
  'returns counts rather than any part of the answer key.';

commit;

-- --------------------------------------------------------------------------
-- 20260301000700_attempt_kind_module.sql
-- --------------------------------------------------------------------------

begin;

-- Add 'module' to attempt_kind. Nothing else.
--
-- WHY THIS IS A MIGRATION ON ITS OWN
--
-- PostgreSQL refuses to use a new enum value in the transaction that added
-- it: "unsafe use of new value ... New enum values must be committed before
-- they can be used." The value and its first use must therefore be in
-- separate transactions, and the unit of transaction here is the migration.
--
-- This was originally one file with the table changes that follow, and it
-- worked -- but only because every consumer we had ran migrations through
-- `psql -f` with no explicit transaction, so each statement committed on its
-- own. It failed the moment the same file was wrapped in `begin; ... commit;`
-- for the deploy bundle. Anything that runs a migration atomically, which is
-- the ordinary and correct thing to do, would have hit it: the local test
-- harness simply never did.
--
-- So the split is not a workaround for the bundle. The bundle is what
-- revealed that the original file was only safe by accident.
--
-- Keep this file to the one statement. Adding a use of 'module' below would
-- reintroduce exactly the failure it exists to prevent.

alter type public.attempt_kind add value if not exists 'module';

commit;

-- --------------------------------------------------------------------------
-- 20260301000710_module_attempts.sql
-- --------------------------------------------------------------------------

begin;

-- The module tier, and the holdout flag.
--
-- The course teaches in three widening passes: a quiz after each lesson, a
-- test after each module, then a full mock. `attempts` could express the
-- first and the last -- lesson_id for a quiz, both null for a mock -- but had
-- no way to say "this attempt covers Module 3". This adds it.
--
-- The 'module' value of attempt_kind is added by the migration before this
-- one and MUST stay there: PostgreSQL will not let a new enum value be used
-- in the transaction that created it, and the checks below use it.
--
-- WHY A HOLDOUT FLAG SHIPS EMPTY
--
-- With a quiz after every lesson and a test after every module, a student has
-- seen almost every question in the bank before their first mock. The mock
-- then measures how well they remember our questions, not how well they know
-- insurance -- and readiness is computed from mocks.
--
-- The real fix is more questions, written mock-only. That is content work, not
-- schema work. The column exists now so that adding them later is a data
-- change rather than a migration against live attempt history, and so the
-- draw can already honour it. It is false everywhere until such questions
-- exist, and the results screen discloses how many questions the student had
-- seen before rather than pretending the number means more than it does.

alter table public.questions
  add column if not exists mock_only boolean not null default false;

comment on column public.questions.mock_only is
  'Reserved for mock papers: never drawn into a quiz, module test or drill. '
  'Empty until mock-only questions are written; see the migration header.';

alter table public.attempts
  add column if not exists module_id uuid;

-- Composite, against (id, course_id), for the same reason every other
-- reference in this schema is: it makes the denormalised course_id provably
-- consistent and makes a cross-course attempt structurally impossible.
alter table public.attempts
  add constraint attempts_module_fk foreign key (module_id, course_id)
    references public.modules (id, course_id) on delete set null;

-- Each kind names its own scope, and only its own.
--
--   quiz   -> lesson_id           a check on the lesson just read
--   module -> module_id           a test over the module just finished
--   drill  -> topic_id            remediation on one blueprint topic
--   mock   -> none                the whole blueprint
--
-- attempts_drill_has_topic already pins the drill case. These pin the rest,
-- so an attempt cannot claim to be a module test while carrying a lesson, or
-- a module test with no module at all.
alter table public.attempts
  add constraint attempts_module_has_module check (
    (kind = 'module'::public.attempt_kind) = (module_id is not null)
  );

alter table public.attempts
  add constraint attempts_quiz_has_lesson check (
    kind <> 'quiz'::public.attempt_kind or lesson_id is not null
  );

-- A module test is a measurement, like a mock. Immediate feedback would turn
-- it into a guided walk through the answers, which is what the lesson quiz is
-- already for.
alter table public.attempts
  add constraint attempts_module_is_on_submit check (
    kind <> 'module'::public.attempt_kind
    or reveal = 'on_submit'::public.reveal_mode
  );

create index if not exists attempts_module_idx
  on public.attempts (student_id, module_id)
  where module_id is not null;

commit;

-- --------------------------------------------------------------------------
-- 20260301000800_start_attempt.sql
-- --------------------------------------------------------------------------

begin;

-- Drawing a paper, server-side.
--
-- public.start_attempt(course, kind, lesson, module, topic, reveal) -> uuid
--
-- SECURITY DEFINER, and the THIRD in this project. The Phase 1 post-mortem
-- established that definer rights must be justified, not assumed, so here is
-- the justification and the alternative that was rejected.
--
-- THE HOLE THIS CLOSES
--
-- Until now a student held `insert` on attempt_questions, and RLS checked
-- only that the attempt was theirs. Nothing checked WHICH questions went in,
-- or HOW MANY. A student could insert five easy questions, label the attempt
-- a mock, score 100% -- and readiness is computed from mock attempts, so they
-- would be moving their own readiness figure. Every other part of this design
-- refuses to trust the client with scoring; the draw was the step that still
-- did.
--
-- WHY DEFINER RIGHTS
--
-- The fix is to revoke insert on attempt_questions (done below) and let the
-- paper be assembled only here. Once that insert is revoked, an INVOKER
-- function running as the student cannot insert either. Definer rights are
-- exactly the mechanism for "let the caller cause something they cannot do
-- themselves" -- the same justification as score_attempt().
--
-- The obligations that come with it, all discharged below:
--   1. Verify the caller is enrolled in the course, FIRST.
--   2. Never select an unpublished question, so the review gate holds here
--      too. A draft question is one nobody has checked the answer key of.
--   3. Never return, or expose, a correct option id. This function returns
--      an attempt id and nothing else.
--   4. search_path pinned.
--
-- SHORT DRAWS ARE HONEST
--
-- If a topic has fewer published questions than the blueprint asks for, the
-- paper is short and question_count records what was actually drawn. It does
-- not top up from another topic: a paper that quietly over-weights whatever
-- happens to be written is a worse lie than a short paper that admits it.
-- The caller compares question_count against the blueprint to tell the
-- student.

create or replace function public.start_attempt(
  p_course_id uuid,
  p_kind      public.attempt_kind,
  p_lesson_id uuid default null,
  p_module_id uuid default null,
  p_topic_id  uuid default null,
  p_reveal    public.reveal_mode default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_student uuid := (select auth.uid());
  v_attempt uuid;
  v_reveal  public.reveal_mode;
  v_drawn   integer;
begin
  -- (1) Authorisation, before anything else. As a definer function this
  -- bypasses RLS, so this test IS the access control.
  if v_student is null then
    raise exception 'not signed in' using errcode = 'insufficient_privilege';
  end if;

  if not exists (
    select 1 from public.enrollments e
     where e.student_id = v_student
       and e.course_id  = p_course_id
       and e.status     = 'active'::public.enrollment_status
       and (e.expires_at is null or e.expires_at > now())
  ) then
    raise exception 'not enrolled in this course'
      using errcode = 'insufficient_privilege';
  end if;

  -- A mock and a module test are measurements; the constraints on `attempts`
  -- already refuse anything else, but defaulting here means a caller cannot
  -- get a confusing constraint error for a choice they did not make.
  v_reveal := coalesce(
    case when p_kind in ('mock'::public.attempt_kind, 'module'::public.attempt_kind)
         then 'on_submit'::public.reveal_mode else p_reveal end,
    case when p_kind in ('mock'::public.attempt_kind, 'module'::public.attempt_kind)
         then 'on_submit'::public.reveal_mode else 'immediate'::public.reveal_mode end
  );

  insert into public.attempts
    (student_id, course_id, kind, reveal, lesson_id, module_id, topic_id, question_count)
  values
    (v_student, p_course_id, p_kind, v_reveal,
     case when p_kind = 'quiz'::public.attempt_kind   then p_lesson_id end,
     case when p_kind = 'module'::public.attempt_kind then p_module_id end,
     case when p_kind = 'drill'::public.attempt_kind  then p_topic_id  end,
     1)                      -- provisional; rewritten once the draw is known
  returning id into v_attempt;

  -- (2) The draw. Every branch filters on status = 'active', so the review
  -- gate that keeps a draft question away from a student holds here as well.
  if p_kind = 'mock'::public.attempt_kind then
    -- Blueprint-weighted: topics.question_count per topic, counts not
    -- percentages, so eight roundings cannot miss the total.
    insert into public.attempt_questions (attempt_id, student_id, question_id, position)
    select v_attempt, v_student, q.id, row_number() over (order by t.code, random())
      from public.topics t
      join lateral (
        select q.id
          from public.questions q
         where q.topic_id = t.id
           and q.status = 'active'::public.content_status
         order by random()
         limit coalesce(t.question_count, 0)
      ) q on true
     where t.course_id = p_course_id;

  elsif p_kind = 'quiz'::public.attempt_kind then
    -- Every published question for the lesson just read, minus any reserved
    -- for mocks. A quiz is a check on comprehension, so it is exhaustive.
    insert into public.attempt_questions (attempt_id, student_id, question_id, position)
    select v_attempt, v_student, q.id, row_number() over (order by random())
      from public.questions q
     where q.lesson_id = p_lesson_id
       and q.status = 'active'::public.content_status
       and not q.mock_only;

  elsif p_kind = 'module'::public.attempt_kind then
    -- Thirty across the module's lessons. Module 2 holds 100 questions; a
    -- test that used all of them would take two hours and nobody would
    -- finish it.
    insert into public.attempt_questions (attempt_id, student_id, question_id, position)
    select v_attempt, v_student, q.id, row_number() over (order by random())
      from public.questions q
      join public.lessons l on l.id = q.lesson_id
     where l.module_id = p_module_id
       and q.status = 'active'::public.content_status
       and not q.mock_only
     order by random()
     limit 30;

  elsif p_kind = 'drill'::public.attempt_kind then
    -- Remediation on one blueprint topic, offered after a bad topic score.
    insert into public.attempt_questions (attempt_id, student_id, question_id, position)
    select v_attempt, v_student, q.id, row_number() over (order by random())
      from public.questions q
     where q.topic_id = p_topic_id
       and q.status = 'active'::public.content_status
       and not q.mock_only
     order by random()
     limit 20;
  end if;

  select count(*) into v_drawn
    from public.attempt_questions aq where aq.attempt_id = v_attempt;

  -- An empty draw is not a paper. It happens when nothing in scope has been
  -- reviewed yet, and returning an attempt with no questions would show the
  -- student a blank exam rather than an explanation.
  if v_drawn = 0 then
    delete from public.attempts a where a.id = v_attempt;
    raise exception 'no published questions available for this selection'
      using errcode = 'no_data_found';
  end if;

  update public.attempts a set question_count = v_drawn where a.id = v_attempt;

  return v_attempt;
end;
$$;

revoke all on function public.start_attempt(uuid, public.attempt_kind, uuid, uuid, uuid, public.reveal_mode) from public, anon;
grant execute on function public.start_attempt(uuid, public.attempt_kind, uuid, uuid, uuid, public.reveal_mode) to authenticated;

comment on function public.start_attempt(uuid, public.attempt_kind, uuid, uuid, uuid, public.reveal_mode) is
  'Assembles a paper server-side and returns the attempt id. SECURITY DEFINER '
  'because the caller may no longer insert into attempt_questions; see the '
  'migration header for why that insert was revoked.';

-- THE REVOKE THAT MAKES THE ABOVE MEAN ANYTHING.
--
-- Without this, start_attempt() is merely a convenience and a student can
-- still hand-build a paper. Update stays: answering a question is an update
-- to selected_option_id, and attempt_questions_update_own_unsubmitted already
-- confines that to their own unsubmitted attempt.
revoke insert on table public.attempt_questions from authenticated;

drop policy if exists attempt_questions_insert_own on public.attempt_questions;

-- And the same for attempts itself. Leaving it would not be exploitable --
-- an attempt with no questions scores zero, which hurts the student who made
-- it -- but a half-closed door invites somebody to assume the other half is
-- open too. start_attempt() creates the attempt row; nothing else needs to.
revoke insert on table public.attempts from authenticated;

drop policy if exists attempts_insert_own on public.attempts;

commit;
